### ISSUE TITLE
/searchpath takes on more characters past the closing quotation mark"

### ISSUE THREAD

**Issue by acescheung** [stefankueng/grepWin#100]
When I used the /searchpath, it also included characters later in the command line as part of the search when I looked in the .ini file.

For example, a command line with this string:

"grepwin.exe" /portable /searchpath:"%~dp0" /searchfor:"\\qt\ |\\qt\*" /replacewith:"" /filemask:"*.txt" /utf8:yes /k:yes /size:2000 /executereplace /closedialog /searchpath:"%~dp0"

did not work, and the grepWin.ini file showed that the searchpath=[local directory]" /searchfor:"

A workaround is to move the /searchpath to the end of the command line. This allowed the command line to work as wanted, and the ini file showed the correct local directory.

Thanks for this great tool.

**Comment by stefankueng** [comment]
grepWin does not use console variables like "%~dp0", so your searchpath doesn't really work.
However: if the searchpath is left empty, grepWin will use the current directory instead.

**Comment by acescheung** [comment]
Dear Stefan,

 

Thank you for your helpful reply! And thank you again for the great program.

Kind regards,

Ace.
