### ISSUE TITLE
Test regex / a nice to have

### ISSUE THREAD

**Issue by intellekta** [stefankueng/grepWin#101]
after a successful regex search with results:
a click on ( Test regex ) should fill the field "Paste text to test the regex with:" from result text lines.

maybe optional like this
( Test regex ) - _[x]_ with serach _results_

thanks in advance

**Comment by stefankueng** [comment]
I don't think this would be a good feature:
- the result list only contains single lines, so if your regex should match over multiple lines it wouldn't help
- what if the result list contains hundreds or even thousands of lines? do you really want to include all that?
