### ISSUE TITLE
UTF8 problem at autocomplete Win10

### ISSUE THREAD

**Issue by pipiscrew** [stefankueng/grepWin#102]
hi,

First I used Greek words to search files, close the app,, second run, the autocomplete gives 'chinese'

![first](https://user-images.githubusercontent.com/3852762/63961081-6e32ef80-ca7f-11e9-875c-dc1a6bc92ae4.png)

![second run](https://user-images.githubusercontent.com/3852762/63961088-71c67680-ca7f-11e9-90a1-bf82ae76a9bb.png)

for your tests:

> Επιλέξτε Ημέρα

btw at presets is working fine

![snap307](https://user-images.githubusercontent.com/3852762/63961170-a5a19c00-ca7f-11e9-90e2-4f96c48b2689.png)

-edit-
previously on Win10x64^

now testing the same on Win7x64 is working.

**Comment by stefankueng** [comment]
Seems to be a problem only with the portable version.
