### ISSUE TITLE
"Installation directory must be on a local hard drive"

### ISSUE THREAD

**Issue by techjp** [stefankueng/grepWin#104]
I get this error every time I try to install grepWin on my Win10 Pro installation. I'm installing on the C: drive using the default path. I have tested with both `grepWin-1.9.2-x64.msi` and `grepWin-1.9.2-x64_user.msi` and get the same error.

I can provide more information about my Windows setup if it would be helpful, just let me know what is needed.

**Comment by stefankueng** [comment]
A simple web search provides lots of hits: Seems you have some problems with access rights.
try installing it from an admin console:
`msiexec /i "path\to\grepWin.msi"
`

**Comment by techjp** [comment]
That's odd. I actually have a right-click menu item to install MSIs as admin. It has always worked until now when I've needed to install an MSI as admin, but not this time.

I used to launch MSIs from an admin console when necessary, but this is actually the first time I have seen this particular error crop up so I didn't equate it to an admin issue.

Anyway, thanks for taking the time to reply.
