### ISSUE TITLE
Column "Kodierung" (encoding) in search results is empty

### ISSUE THREAD

**Issue by bauinformatiker** [stefankueng/grepWin#105]
I used grepwin also to find iso encoded Sourcecode in my LAMP-Projects (PHP/HTML/INCLUDES). But now the column "Kodierung" is empty :-(

I use Version 1.9.2.831 on Windows 10 prof.

**Comment by bauinformatiker** [comment]
Additional info: 
Same problem on local NTFS filesystem as on Windows fileserver. No matter if directorys are "normal" directories or "hardlinks" or Junctions.

Has anybody the same problem?

**Comment by stefankueng** [comment]
sorry for the very late reply:
the encoding column is only shown if the files are actually opened to search for text.
So if you leave the search string empty and only search for file patterns (e.g., "*.php"), then the files are not opened at all.
