### ISSUE TITLE
/searchfor broken if search ends with backslash

### ISSUE THREAD

**Issue by noelhibbard** [stefankueng/grepWin#108]
Example command line:
```
/searchfor:"C:\Windows\"
```

When launched the search box will contain:
```
C:\Windows"
```

I think it's treating the \ as an escape character for the " so the \ gets stripped leaving the " behind. I need my search to end with a backslash and can't find a combination that accomplishes this. Escaping/unescaping can be such a nightmare sometimes and this is a good example.

**Comment by stefankueng** [comment]
don't you mean
`/searchpath:"C:\Windows"`
?

`/searchfor` is for the search string.

**Comment by noelhibbard** [comment]
I am looking to search through a bunch of source code to replace some hard coded paths with relative paths. So no I am not confusing /searchpath and /searchfor.

**Comment by stefankueng** [comment]
using
`/searchfor:"C:\windows"`
I get only `C:\windows` in the search field, without the end quote.

**Comment by noelhibbard** [comment]
Geez.. I just realized my original question is wrong. I am trying to use:
/searchfor:"C:\Windows\"

The last backwards slash before the double quote seems to be escaping the double quote.

**Comment by noelhibbard** [comment]
I just realized GitHub was striping the backslash off my posts. I edited my original post so my syntax is in a code block so it doesn't get butchered.

**Comment by PCMedic67** [comment]
I get what @noelhibbard is saying.  I see the issue in 2 places.  If I run Grepwin from the command line and the Searchpath is  /searchpath:"C:\Test\" the remaining parameters end up in the search in field in the gui.  Same occurs with the searchfor parameter.  It appears that the command line doesn't like when the last character  is a \ or \" in the searchin or searchfor parameters.

_Doesn't work_
**Command:** grepWin-x64-2.0.4_portable.exe /searchpath:"C:\Test\" /searchfor:\\\\\\\\ServerName\\\\Share /regex:yes
**Search in field Result:** C:\Test" \searchfor:\\\\\\\\ServerName\\\\Share \regex:yes

_Doesn't work_
**Command:** grepWin-x64-2.0.4_portable.exe /searchpath:"C:\Test" /searchfor:\\\\\\\\ServerName\\\\Share\ /regex:yes
**Search in field Result:** C:\Test
**Search for field Result:** \\\\\\\\ServerName\\\\Share\ /regex:yes

_Doesn't work_
**Command:** grepWin-x64-2.0.4_portable.exe /searchpath:"C:\Test" /searchfor:\\\\\\\\ServerName\\\\Share\\ /regex:yes
**Search in field Result:** C:\Test
**Search for field Result:** \\\\\\\\ServerName\\\\Share\\ /regex:yes

_Works_
**Command:** grepWin-x64-2.0.4_portable.exe /searchpath:"C:\Test" /searchfor:\\\\\\\\ServerName\\\\Share /regex:yes
**Search in field Result:** C:\Test
**Search for field Result:** \\\\\\\\ServerName\\\\Share

But the GUI Regex test seems to work.

Thoughts?

![RegExTest](https://user-images.githubusercontent.com/34310100/101975799-4ed8bb00-3c0d-11eb-8ad4-f40f6c980e7a.png)

**Comment by stefankueng** [comment]
for paths, just use a forward slash instead of a backslash - grepWin will convert those automatically before use.

**Comment by stefankueng** [comment]
as for /searchfor: - use the new /searchini instead, it's much safer since there no escaping takes place at all:
https://tools.stefankueng.com/grepWin_cmd.html
