### ISSUE TITLE
Exact text searching of 12GB xml file returns wrong count, plus line numbers off by 1

### ISSUE THREAD

**Issue by plmojn** [stefankueng/grepWin#110]
I can correctly search an xml file in vim or Cygwin grep --count but exact text searching a single 12GB xml file using grepWin for <Tumor> gives me a count less than half found using other tools. 
The search phrase only appears once per line. 
Also the 1 million+ times it does find it in the file, the line numbers are off by -1 (first result shown on line 20 instead of correctly on line 21.) 
Tried UTF8 and Case sensitive search options; no difference. 
The found text also doesn't appear but I see that issue was already reported.
I have 24GB memory and plenty of free disk on my Win10 desktop.
Thanks, great tool, hope the above is clear enough

**Comment by stefankueng** [comment]
files that big don't get parsed completely for lines, they're only searched.
So line count is only done for the first 4GB.

As for the off-by-one line numbers: if you have inconsistent line endings, that can happen. For example, a LFCRLF sequence counts as two lines, but some editors count that as one.
