### ISSUE TITLE
Change order of search?

### ISSUE THREAD

**Issue by ghost** [stefankueng/grepWin#112]
Is there a way to change the order that files are searched eg by alphabetical filename or by last modified?

**Comment by stefankueng** [comment]
sorry, that's not possible: windows returns the files in it's own order (depends on OS version and filesystem).
If we would first fetch all files and only then start searching, that would take a lot (really: a lot) longer. Just think about the windows explorer: it first lists all files and then starts copying/deleting/whatever.
