### ISSUE TITLE
feature request: limit search on specific file types

### ISSUE THREAD

**Issue by mgroen1** [stefankueng/grepWin#115]
Currently (version 1.9.2) only possible to search in Binaries files (or exclude them), not possible to search in specific file types or extensions (I know these are not exactly the same),.

use case:
I would only like to search within Word, Excel, Powerpoint, and text files (not using regex),
so I would like to see checkmark to searfor .doc(x), .xls(x), .txt  to limit search results.

**Comment by stefankueng** [comment]
On the right above the search button is an edit box "file names match".
Enter "*. xls" to only search for Excel files there.

**Comment by mgroen1** [comment]
Hi,
thanks, I tried, but grepWin can't find results of type .pdf and .xlsx (while there should be results).
Older type .xls is found

Is this a bug in grepwin?

**Comment by stefankueng** [comment]
pdf and xlsx files are compressed, so you won't find plain text inside them.
grepWin does not decompress/unzip files but searches the files as they are.
