### ISSUE TITLE
How to delete path history?

### ISSUE THREAD

**Issue by Seventh7th-Son** [stefankueng/grepWin#116]
![No Delete function on path history](https://user-images.githubusercontent.com/5783243/73272026-b3368b80-41af-11ea-9445-2a0b94f3d43c.png)

**Comment by Seventh7th-Son** [comment]
Old file paths have been deleted from computer, but they still show on the path history.   Would like to remove the old data.

**Comment by stefankueng** [comment]
works like in most apps:
* cursor down to open the drop-list
* cursor down to the entry you want to delete
* hit `DELETE `key

or just use regedit, go to `HKCU\Software\grepWin\History` and delete everything there.

**Comment by Seventh7th-Son** [comment]
Thank you!

**Comment by RoyiAvital** [comment]
> or just use regedit, go to HKCU\Software\grepWin\History and delete everything there.

Could you add a button in *Settings* to *Clear History*?
Also, could we have an option in *Settings* to *Disable History* so no *History* will be preserved?

Thank You.
