### ISSUE TITLE
No Results under Win7 SP1

### ISSUE THREAD

**Issue by Werekorden** [stefankueng/grepWin#12]
Hi,
I was trying to use grepwin.  First I tried my regular expression with the onboard tool "Test Regex". After it worked I used the software on a folder with files that should be found by RegEx. Unfortunately it didn't found any. After that I designed a text file using Editor and suprise the file was found by grepwin.

Afterwards I put the expressions from the text files in a WORD document (docx) Office 2010. This time grepwin didn't found the Word-document but the text file.

It seems that docx Files are not searchable? Is this true because then the whole GREP-Search is not usable. That would be a shame because I love GREP.

**Comment by stefankueng** [comment]
docx files are zip-compressed xml files.
grepWin can only search for text - the text when compressed is not readable and therefore not searchable by grepWin anymore.

**Comment by Stamimail** [comment]
Is this true also for the old doc extension?
