### ISSUE TITLE
Feature Request:  Allow search pattern argument for editor command

### ISSUE THREAD

**Issue by RaiKoHoff** [stefankueng/grepWin#121]
I would like to use grepWin as external multi file search component for Notepad3 (https://github.com/rizonesoft/Notepad3).

It would be great, if you could add a placeholder parameter (beside %path% and %line%) for the used search pattern (e.g. %pattern%) to be passed to the editor component.

**Comment by stefankueng** [comment]
I don't think %pattern% would work: the search pattern can contain newlines and quotes and all sorts of special chars. passing such a string on a command line won't work.
and if we try to escape that string, how would you know on your end which chars are escaped and which are part of the real search string?

**Comment by leeoniya** [comment]
> and if we try to escape that string, how would you know on your end which chars are escaped and which are part of the real search string?

why not convert all string literals to equivalent regexs (on the np3 side), then all escapes are known if passed explicitly as `%regex_pattern%` to grepWin cli.

**Comment by RaiKoHoff** [comment]
@leeoniya : Oh, passing to grepWin is not the problem (using the ini-file for that purpose), the problem I like so solve is, calling the Editor from grepWin is via CLI (Notepad3 has the option to provide a search pattern (text (-m) or RegEx (-mr), so NP3 can find the pattern in the given %line%.
But @stefankueng is right, that might run into problems, as mentioned above ... 🤔.

I will check some other options, so closing this for now ...
