### ISSUE TITLE
Two weird characters added at the start of .reg files - þÿ

### ISSUE THREAD

**Issue by prodiJy2000** [stefankueng/grepWin#122]
Whenever I do a search and replace the build number to a new one, it screws up my *.reg files.
Two characters "**þÿ**" are added at the start of any .reg files.

![Screenshot](https://user-images.githubusercontent.com/62956351/78056697-89d2e100-7353-11ea-825f-f707fc292c54.png)

Other non .reg files are correct.
![screen2](https://user-images.githubusercontent.com/62956351/78056744-9b1bed80-7353-11ea-9a74-7a6e12526bdd.png)

Scooter Software says:
Between the two sides, the unedited side is reporting as UTF16 with a BOM and the other side is missing the BOM information. Those characters are probably a corruption of the tag at the beginning that marks if the file has a BOM.

**Comment by stefankueng** [comment]
are you sure you have the latest version of grepWin (1.9.2) ?
because replacing in utf-16 files works just fine for me.

**Comment by Rudolpher** [comment]
Quick clarification:
þ ÿ(Windows-1252/Latin-1) = FF FE = UTF-16 Big-Endian
ÿ þ = FE FF = UTF-16 Little-Endian
If the text file is opened as UTF-16 those byte sequences should display as nothing if they are present outside the first 2 bytes.

Would help to see the first 4 bytes of hex before and after edit. At a glance guessing something changed the encoding to UTF-32 BE which is 00 00 FE FF = NUL NUL þ ÿ, and the diff used not supporting it so reverting to default OS encoding.

**Comment by stefankueng** [comment]
@Rudolpher  wouldn't that be the problem of the diff viewer?
