### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/grepWin#123]
implement a dark mode for the dialogs.

**Comment by stefankueng** [comment]
![image](https://user-images.githubusercontent.com/665591/78170978-051bbc00-7454-11ea-89c6-513ac0475bd7.png)

**Comment by Feliipe93** [comment]
how to enable? im on windows 11 portable editions of grep

**Comment by GodlikeRU** [comment]
> how to enable? im on windows 11 portable editions of grep

I had the same problem. Turns out there's settings bottom on left middle side. Couldn't find it too. There's dark mode switch.
