### ISSUE TITLE
Open with Editor not parsing %path%

### ISSUE THREAD

**Issue by CADbloke** [stefankueng/grepWin#130]
Greetings

Firstly, thank you for writing grepWin, it's awesome. v2 dark mode looks good, thanks for that.

In "Settings" => Editor I set the command line to `"C:\Program Files (x86)\Notepad++\notepad++.exe" "&path%" -n%line%`, I get this error
![grepWinNPPerror-20-04-08a](https://user-images.githubusercontent.com/147329/78726069-68d24780-7974-11ea-87ca-4078336f3e69.png)

I tried `"&path%" -n%line%` in case it was just a suffix for the default editor but that just failed silently.

I'm sure the first [syntax is correct](https://superuser.com/questions/290409/opening-a-text-file-at-a-certain-line-shortcut). Or is it?

I think the problem may be related to https://github.com/stefankueng/grepWin/blob/master/src/SearchDlg.cpp#L1861 -  `Notepad++` may be interpreted as a regex at some point ?

Cheers
Ewen

**Comment by stefankueng** [comment]
why `"&path%"`? Shouldn't it be `"%path%"`

**Comment by CADbloke** [comment]
Oh dear. I’m so sorry. 
As HAL said, “it must be user error”.

**Comment by CADbloke** [comment]
Can confirm 2 things here
- I can't type or read
- `"C:\Program Files (x86)\Notepad++\notepad++.exe" "%path%" -n%line%` works as advertised. 
Thanks Stefan
