### ISSUE TITLE
"grepWin has stopped working" error message.

### ISSUE THREAD

**Issue by ghost** [stefankueng/grepWin#131]
When I launch grepWin.exe v2.0.0, it shows "grepWin has stopped working. A problem caused the program to stop working correctly" system error message in win7 x86.
v1.9.2 don't have this problem.

**Comment by stefankueng** [comment]
please check the event viewer in Windows, you should see an entry there relating to this.
That entry will have more information about what exactly went wrong.

**Comment by circcc** [comment]
오류 있는 응용 프로그램 이름: grepWin-2.0.0_portable.exe, 버전: 2.0.0.856, 타임스탬프: 0x5e8c5a67
오류 있는 모듈 이름: unknown, 버전: 0.0.0.0, 타임스탬프: 0x00000000
예외 코드: 0xc0000005
오류 오프셋: 0x002b06d6
오류 있는 프로세스 ID: 0x988
오류 있는 응용 프로그램 시작 시간: 0x01d60d66065f53b3
오류 있는 응용 프로그램 경로: C:\grepWin-2.0.0_portable.exe
오류 있는 모듈 경로: unknown
보고서 ID: 441bf408-7959-11ea-b616-e0699564e7cc

**Comment by stefankueng** [comment]
hmm - the "faulting module name" is "unknown". That doesn't help.

Please get the procdump tool from here:
https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

then open a command prompt and type:
`procdump -e -ma -w grepWin.exe`

then start grepwin and get it to crash.
A dmp file will be written where you started procdump. Zip that and attach it to this issue or provide a link to it so I can get it.

**Comment by circcc** [comment]
[grepWin.exe.1664.dmp.zip](https://github.com/stefankueng/grepWin/files/4457972/grepWin.exe.1664.dmp.zip)

**Comment by stefankueng** [comment]
Thanks for the dump.
It seems another tool is interfering with grepWin on your machine: there's a dll named dfh32.dll which inserts itself into the grepWin process and then causes the crash.
I don't know what that dll actually is, but from a quick web search it appears the "Most antivirus programs identify dfh32.dll as malware" - you might want to check your OS and system.

Closing this issue since the crash is not because of grepWin itself.
Sorry I can't be of more help...

**Comment by ghost** [comment]
dfh32.dll is not malware. it's part of Direct Folders.
I uninstalled Direct Folders, but grepWin is still crashed.
As I said v1.9.2 don't have this problem. so, it is grepWin itself problem.
I don't use grepWin, I'm using FindInFiles. 
My issue is just FYI. You don't have to fix it.
Thanks anyway.

**Comment by stefankueng** [comment]
does the crash happen when you start grepWin or when you e.g. start a search?

**Comment by Petewg** [comment]
Hello,
Just tried to upgrade from 1.9.2 to 2.0.0 but the program 
can't even start (crashing).
Reverting back to previous version it works flawlessly!

Please see below the error logs I was able to collect.

Windows error report:
\-------------------------

> Problem signature:
>   Problem Event Name:        BEX
>   Application Name:          grepWin.exe
>   Application Version:       2.0.0.856
>   Application Timestamp:     5e8c5a67
>   Fault Module Name:         grepWin.exe
>   Fault Module Version:      	2.0.0.856
>   Fault Module Timestamp:    5e8c5a67
>   Exception Offset:          000dc6ab
>   Exception Code:            c0000409
>   Exception Data:            00000000
>   OS Version:                6.1.7601.2.1.0.256.48
>   ....
>   ....

  
  
I did try ProcDump as suggested. Unfortunately could not get the dump file created; 
see below the output from two different calling methods.

Starting grepWin from windows Start menu -> programs -> grepwin
\-------------------------------------------------------

> ProcDump v9.0 - Sysinternals process dump utility
> Copyright (C) 2009-2017 Mark Russinovich and Andrew Richards
> Sysinternals - www.sysinternals.com
> 
> Waiting for process named grepWin.exe...
> 
> Process:               grepWin.exe (2388)
> Process image:         C:\Program Files\grepWin\grepWin.exe
> CPU threshold:         n/a
> Performance counter:   n/a
> Commit threshold:      n/a
> Threshold seconds:     n/a
> Hung window check:     Disabled
> Log debug strings:     Disabled
> Exception monitor:     Unhandled
> Exception filter:      [Includes]
>                        *
>                        [Excludes]
> Terminate monitor:     Disabled
> Cloning type:          Disabled
> Concurrent limit:      n/a
> Avoid outage:          n/a
> Number of dumps:       1
> Dump folder:           C:\dump\
> Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
> Queue to WER:          Disabled
> Kill after dump:       Disabled
> 
> 
> Press Ctrl-C to end monitoring without terminating the process.
> 
> [10:23:25] Exception: C0000005.ACCESS_VIOLATION
> [10:23:25] Exception: 80000003.BREAKPOINT
> [10:23:25] The process has exited.
> [10:23:25] Dump count not reached.
> 


Starting grepWin from explorer's context menu
\-------------------------------------------------------

> ProcDump v9.0 - Sysinternals process dump utility
> Copyright (C) 2009-2017 Mark Russinovich and Andrew Richards
> Sysinternals - www.sysinternals.com
> 
> Waiting for process named grepWin.exe...
> 
> Process:               grepWin.exe (3744)
> Process image:         C:\Program Files\grepWin\grepWin.exe
> CPU threshold:         n/a
> Performance counter:   n/a
> Commit threshold:      n/a
> Threshold seconds:     n/a
> Hung window check:     Disabled
> Log debug strings:     Disabled
> Exception monitor:     Unhandled
> Exception filter:      [Includes]
>                        *
>                        [Excludes]
> Terminate monitor:     Disabled
> Cloning type:          Disabled
> Concurrent limit:      n/a
> Avoid outage:          n/a
> Number of dumps:       1
> Dump folder:           C:\dump\
> Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
> Queue to WER:          Disabled
> Kill after dump:       Disabled
> 
> 
> Press Ctrl-C to end monitoring without terminating the process.
> 
> [10:25:14] The process has exited.
> [10:25:14] Dump count not reached.
> 
> 
> C:\dump>

Hope that helps to resolve the issue and many thanks for this nice tool.

**Comment by stefankueng** [comment]
> Hello,
> Just tried to upgrade from 1.9.2 to 2.0.0 but the program
> can't even start (crashing).
> Reverting back to previous version it works flawlessly!

> > [10:23:25] Exception: C0000005.ACCESS_VIOLATION
> > [10:23:25] Exception: 80000003.BREAKPOINT
> > [10:23:25] The process has exited.
> > [10:23:25] Dump count not reached.

The 80000003.BREAKPOINT indicates that you have some other tool running that acts as a debugger of some sorts.
That may be the cause of the crash, or at least that tool is the reason that procdump doesn't get to create the dump.

**Comment by Petewg** [comment]
> The 80000003.BREAKPOINT indicates that you have some other tool running that acts as a debugger of some sorts.

I can't see any kind of such tool running on my system, neither process or service.
I suspect that it might be something related to the windows version (Win7 in my case) .
Is it sure that this version (windows 7) is supported by grepWin 2.0.0 ?

**Comment by stefankueng** [comment]
just FYI: the fix for this is part of the submodule:
https://github.com/stefankueng/sktoolslib/commit/92c7afe88caa538ab512a42bfbe406a071dd53de
So no commit in this project for the fix.
