### ISSUE TITLE
Completely froze my PC

### ISSUE THREAD

**Issue by AndroYD84** [stefankueng/grepWin#132]
I tried searching a common word in a folder containing 370GB of tar.gz files, but after reading it didn't support searching inside archives, I clicked stop multiple times, and it wouldn't stop the operation, the PC was still perfectly responsive, I waited and nothing happened, so I decided to close it by clicking [X] and nothing happened, so I typed ALT+F4 and nothing happened.
However, I noticed that the very instant I tried to close it, suddenly ALL my hard drives started acting crazy and work at 100%, making my mouse laggier and unresponsive over time, until I couldn't do anything, couldn't even open the task manager, my PC was working like crazy and started playing beeps like when you overload it when I moved the mouse, I disconnected the external USB hard drive it was searching on, but all other hard drives were still acting crazy for a good 10 minutes (I waited out of fear of losing my work), until I finally could regain control of my PC after a black screen and see the application successfully closed, I got a glimpse on the Task Manager that SysMain was using all my hard drives at 100%.
I'm not sure what happened and can't think of a reason for it, but I suspect grepWin could have done something that made SysMain go crazy (it's a Windows feature known to cause slow downs to many users, but never in my life it went to such crazy level), it happened suddenly and exactly the moment I clicked [X], before none of my hard drives were acting like crazy at all and there were no lags, even when the stop button was unresponsive I could still do normal operations without noticing any slow downs.

**Comment by stefankueng** [comment]
do you have the latest version? I've made some improvements so it cancels faster.
Also: did you monitor the memory consumption? With such big files it could be that grepWin used too much memory and your system came to a halt because of memory swapping...

**Comment by AndroYD84** [comment]
Yes, I used the latest version on the [Releases tab](https://github.com/stefankueng/grepWin/releases), I'll try reproducing the problem when I have finished my work, I did not monitor the memory consumption as I could barely do any kind of operation, but next time I'll make sure I can.
