### ISSUE TITLE
Hovering over a file match in the search results may display stale data

### ISSUE THREAD

**Issue by chishold** [stefankueng/grepWin#134]
This concerns grepWin version is 2.0.0.856, 2020/04/07 12:44:32.

After a search, when I hover over a result, the popup text **may** show details from a previous search.

Here are some steps that reliably reproduce the issue for me:

1. Open grepWin.

2. Search for, say, _grepwin_. The result is:
	D:\Documents and Settings\184614A\My Documents\Installers\grepWin-2.0.0-x64.msi.dsc.txt

3. Hover over the result and the popup displays the contents of the relevant file:

![grepWin01](https://user-images.githubusercontent.com/4187954/80176732-25daca00-862c-11ea-9f9b-6074a4aca711.png) (My screen capture software could not capture the bottom of the grepWin window.)

4. Now search for, say, _getwindowtext_. The results are:
	D:\Documents and Settings\184614A\My Documents\Installers\GetWindowText.zip.dsc.txt
	D:\Documents and Settings\184614A\My Documents\Installers\GetWindowText_x64.zip.dsc.txt

5. Hover over the first result (of two) and the popup displays the same data as step 3 above:

![grepWin02](https://user-images.githubusercontent.com/4187954/80176762-3723d680-862c-11ea-923d-0ed07b3af55b.png)

6. Hover over the second result, however, and the correct data is shown.

7. Hover over the first result again and it now shows the correct data also:

![grepWin03](https://user-images.githubusercontent.com/4187954/80176765-38550380-862c-11ea-8a05-3ee6a4a6580c.png)

**Comment by stefankueng** [comment]
I don't know how this can even be possible: when a search is started, all the data from previous searches is cleared. So the tooltip can not show that data because that data isn't available anymore!

Do you have some system-optimizer tool installed that maybe caches the tooltip data?

**Comment by chishold** [comment]
I've been through my process list and can't find such a tool.

Here are full window screenshots of the scenario:

<img width="725" alt="Screenshot 2020-04-30 15 12 15" src="https://user-images.githubusercontent.com/4187954/80682886-e57cbf80-8af5-11ea-900c-2104b084cfc2.png">
<img width="725" alt="Screenshot 2020-04-30 15 14 38" src="https://user-images.githubusercontent.com/4187954/80682893-e7468300-8af5-11ea-8220-41560e5180f4.png">
<img width="725" alt="Screenshot 2020-04-30 15 14 50" src="https://user-images.githubusercontent.com/4187954/80682894-e7df1980-8af5-11ea-9fb8-7099dd5eff0b.png">
<img width="725" alt="Screenshot 2020-04-30 15 16 00" src="https://user-images.githubusercontent.com/4187954/80682895-e877b000-8af5-11ea-951a-3be9bcfb863d.png">
<img width="725" alt="Screenshot 2020-04-30 15 16 10" src="https://user-images.githubusercontent.com/4187954/80682901-e877b000-8af5-11ea-8bb1-7123c553370d.png">
