### ISSUE TITLE
Feature Request: Date Filters

### ISSUE THREAD

**Issue by opus131** [stefankueng/grepWin#14]
For my use-cases it would be extremely helpful if I could use the "Limit Search" filters to exclude files by dateCreated/dateModified rather than just by size. I wouldn't have to be done with fancy datepicker dialogs either -  a free-text input for a date string in the system locale, or a simple "older than/newer than" with a numeric input for the number of days would be sufficient.
Could a feature like that be added in a future version?

**Comment by Yyyyes** [comment]
Hi.
Same request for me since long.
Alternative would be to be able to give as SEARCH IN a file containing the list of files to look into.  (@FileLlist.txt)

**Comment by Yyyyes** [comment]
Hi,
Thanks.  I appreciate your responsivness. 
May I suggest to make the first date selection field disappear when "all dates" is selected?

**Comment by Yyyyes** [comment]
As I’m not sure you get to receive the comments when the topic is closed, I send it directly to you :

Yyyyes <https://github.com/Yyyyes>  commented a minute ago <https://github.com/stefankueng/grepWin/issues/14#issuecomment-392308827>  


Hi,
Thanks. I appreciate your responsivness.



May I suggest to make the first date selection field disappear (or grey) when "All dates" is selected?

 

 

De : Stefan Küng [mailto:notifications@github.com] 
Envoyé : samedi 26 mai 2018 14:51
À : stefankueng/grepWin
Cc : Yyyyes; Comment
Objet : Re: [stefankueng/grepWin] Feature Request: Date Filters (#14)

 

Closed #14 <https://github.com/stefankueng/grepWin/issues/14>  via  <https://github.com/stefankueng/grepWin/commit/783a7951a0e7931335015d1368f173c805df6fbf> 783a795.

**Comment by opus131** [comment]
@stefankueng Thank you very much for implementing my feature request so quickly, and for your fantastic products!

**Comment by stefankueng** [comment]
@Yyyyes : yes I receive notifications for comments also on closed issues.

About hiding the date control if "All dates" is selected: I don't think that's a good idea. UI-elements should not hide but get disabled. I'm even thinking of having the second date control visible but disabled.
