### ISSUE TITLE
Setting "content" does not save

### ISSUE THREAD

**Issue by komawoyo** [stefankueng/grepWin#142]
Windows 10 x64
Setting the radio to content does not save in . This is useful because I mainly use this program to search text in *.cpp and *.txt

Expected on startup:
![image](https://user-images.githubusercontent.com/18315233/81248848-241ce900-8fd2-11ea-8fc4-243032d24ef3.png)

**Comment by stefankueng** [comment]
it does remember the state (at least in the latest version).

**Comment by komawoyo** [comment]
latest version works fine. Ty

**Comment by komawoyo** [comment]
Acutally, this bug still exists in the latest version (grepWin-x64-2.0.0_portable)  : 

https://giant.gfycat.com/SmallLameAmericancrayfish.webm

**Comment by stefankueng** [comment]
well, it switches back to "files" whenever you search without text in the search box. E.g. when you search for file patterns.
It has to switch back then because the "content" view would be empty.

**Comment by komawoyo** [comment]
Ah I see, I felt the program was performing as unintended. Thanks for clarifying that this was by design.

Edit: I will actually edit the source and build a version to keep the showcontent to set to my preference :')
