### ISSUE TITLE
Option to Suppress "without backups" prompt

### ISSUE THREAD

**Issue by Brondahl** [stefankueng/grepWin#144]
I'm a developer. As a result in 99.9% of cases when I use the Replace functionality, I'm doing it in a git repo and thus don't need a backup.

I recognise that the prompt is valuable for some users, and a "Safety-On by Default" approach is sensible. But it would be really nice if I could change a setting to say "no, trust me, you don't need to ask".

Is that a possibility?

(Even better, would be if it could remember this per directory target. Or if it looked to see if it were in a git repo, but that seems like a LOT more effort)

**Comment by Brondahl** [comment]
I have looked for such a check-box and can't find one. If I'm just bad at looking, then "where is that option, please?"

**Comment by Brondahl** [comment]
(Alas, I know no C++ whatsoever, and thus can't submit a PR myself)

**Comment by Brondahl** [comment]
Wow! I'm ... astonished! Never seen a response like that at any point on any OS project. Thank you so much!

I think GH will message me when a release is created to ship the `2.0.1` milestone. Is that right?

**Comment by stefankueng** [comment]
Sorry, I actually don't know if you get notified of new releases.
I just use [chocolatey ](https://chocolatey.org/)to stay up to date with my tools.
