### ISSUE TITLE
[NotIssue] What the latest version supporting WinXP

### ISSUE THREAD

**Issue by VitRom** [stefankueng/grepWin#149]
Subj?

**Comment by stefankueng** [comment]
here are the very old versions:
https://sourceforge.net/projects/grepwin/files/Archive/

but I don't know which was the latest to support XP.

And as a hint to you that you should **not use XP anymore under any circumstances**, I'll leave it up to you to figure that out yourself.
Seriously: XP???

**Comment by VitRom** [comment]
> I don't know which was the latest to support XP

A bit strange to hear this from **the author** :rofl: 
Are there any signs to distinguish between the supporting or not versions? A build environment version shift for example or something? Dependency change?

> you should **not use XP anymore under any circumstances**

:rofl: "Don't tell me what to do and I'll not tell You where to f-off" (proverb)
I use **tools** regardless of a fashion trends or a marketing bullshit. I still even use (pls don't tell anybody!) DOS when it's suitable.

**Comment by stefankueng** [comment]
XP is not supported anymore for a long, long time. If you're still using it then you're a security risk not just for you but for everybody else: your PC most likely is part of a botnet now because of the many, many security issues that aren't fixed anymore.
So yes, I take the liberty to tell you to not use XP anymore, no matter how many f-words you reply with.
And yes: that means you won't get any help for me regarding that issue. I will not encourage the use of XP.

**Comment by VitRom** [comment]
Thank for your kindly assistance :rofl:
I have to spend some time and to do a binary search through releases, nothing scary.

And just to make some little things clear.
BTW it's so funny that your Anathema didn't touched the DOS about which I've said. May be you just knows nothing about a full tcp/ip stack for this OS? But it's exist. And works. And is used. And Win98/ME with KernelEx too. Well, doesn't matter.

Your grepWin is good, seems you're a good programmer, but as a sysadmin/engineer you're... er... well, "not so good" :smile: Trust the mine quarter century long experience in these areas. Somebody uses a tools that is and mind to make them works right, somebody replaces thoughts with a Faith -- in a usefulness of official updates, in a miriads of bots spawning around every corner (BTW I didn't use antiviruses about to 7 years) etc. etc.

But because it's a Faith I'm undisputably accept your opinion.
WBR!

**Comment by stefankueng** [comment]
haven't heard one good argument about why you still use XP, no reason given why you can't use something that's still supported.
Instead, you dismiss arguments as faith so you don't have to deal with them.

please disconnect yourself from the internet...
