### ISSUE TITLE
Search several paths (pipe symbol)

### ISSUE THREAD

**Issue by kpsuhg** [stefankueng/grepWin#151]
In the current version 2.0.1 of grepWin, it is no longer possible search several paths, separated by the pipe symbol. This used to work at least until version 1.92.

If I select multiple files or folders in Windows Explorer and select "search with grepWin" from the context menu, grepWin still opens up with "Search in" set to "<path_1>**|**<path_2>**|**...," but when I finally execute the search, I get an "Invalid path!" error.

Same if I enter "Search in" manually, using the pipe symbol to separate paths.

**Comment by stefankueng** [comment]
#150

**Comment by kpsuhg** [comment]
Sorry for the duplicate! Didn't notice the "closed" tab. Greenhorn ...
