### ISSUE TITLE
Update Russian translation Git ea6f610c and fix found typo

### ISSUE THREAD

**Issue by VictorVG** [stefankueng/grepWin#152]
I update Russian translation Git ea6f610c and fix found typo.  This file included 100% translations.

Updated translation is attached: in to [**Russian.lang.zip**](https://github.com/stefankueng/grepWin/files/4695250/Russian.lang.zip)

**Comment by stefankueng** [comment]
Thanks!
Pushed.

**Comment by VictorVG** [comment]
Big thaks!
