### ISSUE TITLE
Create backup file in a separate folder not working

### ISSUE THREAD

**Issue by hpwamr** [stefankueng/grepWin#153]
Hello @stefankueng ,
`grepWin version: 2.0.1.882 - 2020-05-21 15:21:57`

When I check `"Create backup files in a separate folder"`, all files are NOT backup in a separate folder.

![2020-05-29_172106](https://user-images.githubusercontent.com/34211772/83277000-bd09e300-a1d1-11ea-8a71-6816ba3b1a26.png)

![2020-05-29_172856](https://user-images.githubusercontent.com/34211772/83277146-efb3db80-a1d1-11ea-840a-0c7198b1009c.png)

**Comment by stefankueng** [comment]
the files are backed up in a folder named "grepWin_backup" that's created at the path you're searching in, not in every searched folder separately.
So if you search e.g. in `C:\` and the files that get replaced text are in `C:\subfolder1\subfolder2`, you'll find them in `C:\grepWin_backup\subfolder1\subfolder2\backupfile.txt`

**Comment by hpwamr** [comment]
> the files are backed up in a folder named "grepWin_backup" that's created at the path you're searching in, not in every searched folder separately.

Hello @stefankueng ,
I'm using  `grepWin-x64-2.0.1_portable version: 2.0.1.882 - 2020-05-21 15:21:57`

Yes, I understand the principle, but it's seems to not working correctly ?

I'm in "d:\temp" where there are 2 folders with many subfolders and many "resource files".
So, I filter on the filenames files **"*.rc"**

Now, I'm looking for all "*.rc" files in all folders/subfolder to replace for example: "UTF-8" by "UTF-16"
Boom, replace is done, but all "backup files" are locate in each corresponding sub-folders instead of a separate folder !

I confirm that the setting in "grepWin.ini", is `backupinfolder=1` when the settting "Create backup files in a separate folder" is "checked"! 

Also,

**Comment by stefankueng** [comment]
Ups, that was the hint: portable version.
Seems even for the portable version the registry is consulted instead of the ini file during the replace/backup function...
