### ISSUE TITLE
The path(s) which is searched recursively

### ISSUE THREAD

**Issue by hpwamr** [stefankueng/grepWin#155]
Hello @stefankueng ,
I'm using  `grepWin-x64-2.0.1_portable version: 2.0.1.882 - 2020-05-21 15:21:57`

When I try to search on "Multi-paths', I receive a error message 
```
"Invalid path! 
Path does not exist or is not accessible!"
```
Do I something wrong?

![2020-06-05_220012](https://user-images.githubusercontent.com/34211772/83918052-4001df00-a778-11ea-9569-073d9d698580.png)

**Comment by stefankueng** [comment]
#150
