### ISSUE TITLE
Ctrl+C (Copy) with selected file not working.

### ISSUE THREAD

**Issue by itsmehenning** [stefankueng/grepWin#157]
Hello,
i would like to copy with the keyboard shortcut Ctrl + C one or more selected files from the result list to another destination, but nothing happened with Ctrl + V. I always use the right mouse click on it and click on Copy. Then Ctrl + V for paste in working.
I am using the latest version 2.0.1 on Windows 10.
Regards

**Comment by stefankueng** [comment]
Ctrl+C works fine for me here. Both with 32-bit and 64-bit versions.
But it only works if the list control has the focus.
