### ISSUE TITLE
common part of path is not omitted when showing file contents

### ISSUE THREAD

**Issue by KOTRET** [stefankueng/grepWin#162]
in reference to #140: it works as expected, but only if the files are shown as plain list, not when showing their contents.

**Comment by stefankueng** [comment]
i need an example here. The content view does not show any path for me, only the filename.

**Comment by KOTRET** [comment]
here is an example ![example](https://user-images.githubusercontent.com/1357504/85827135-e93f6200-b785-11ea-91ce-fcf6508fab86.png)

**Comment by stefankueng** [comment]
ah yes: that's by design. That column should show the full path, because in the first column only the filename is shown.
Also the full path because you can search in multiple paths at the same time.

**Comment by KOTRET** [comment]
The reason to show the full path is valid for both: Files & Content. But if there is only one path (or if the elements have some common paths - but that is most probably annoying to implement), this still can be omitted.
