### ISSUE TITLE
[enhancement]Add "whole word" checkbox

### ISSUE THREAD

**Issue by rafi-d** [stefankueng/grepWin#168]
HI,
I know this can be done with regex, but this is a very commonly used option, so it will be much easier (like case-sensitive) to have it available also  in a checkbox. 

Much appreciated

Rafi

**Comment by kengui** [comment]
Yes, agree. First time use it find a long time.

**Comment by HelderMagalhaes** [comment]
> I know this can be done with regex [...]

True. Quick reference:
```
\b
    \b matches word boundaries. Searching for \bword\b finds word, but not subwords or words. 
```
([source](https://tools.stefankueng.com/regexhelp.html))

> [...] but this is a very commonly used option, so it will be much easier (like case-sensitive) to have it available also in a checkbox.

True as well. Especially useful for beginners.

**Comment by stefankueng** [comment]
dupe of #103
