### ISSUE TITLE
New Russian translation for grepWin 2.0.2

### ISSUE THREAD

**Issue by VictorVG** [stefankueng/grepWin#170]
[**grepWin 2.0.2 Russian translation**](https://github.com/VictorVG/Source/releases/tag/grepwin202rus)

* Correction of the distortion of the meaning of terms
* Fix typo
* Accelerators placed

**SHA-256**

8f09233ab610ff0b2a0553560df08a8fe4298f10b97b3c3141627d4ebe3e69fc *Russian.lang

**Comment by VictorVG** [comment]
Big thanks!

**Comment by stefankueng** [comment]
just added a few more strings. If you like to translate those too?

**Comment by VictorVG** [comment]
Ok! Ready - [**Russian.lang**](https://github.com/VictorVG/Source/releases/tag/grepwin202rus1) Git 2e3910ffd

also this file in to attach - [**Russian.lang.zip**](https://github.com/stefankueng/grepWin/files/4906639/Russian.lang.zip)

**Comment by stefankueng** [comment]
Thanks!

**Comment by VictorVG** [comment]
Mutually!

**Comment by VictorVG** [comment]
Convert  to UTF-8 - [**Russian.lang**](https://github.com/VictorVG/Source/releases/tag/grepwin202rus2)

Sorry! I didn’t notice that I accidentally committed to ASCII ...

**Comment by stefankueng** [comment]
the last file already was in utf8. Is something wrong with the file here: https://raw.githubusercontent.com/stefankueng/grepWin/main/translations/Russian.lang
?

**Comment by VictorVG** [comment]
Yes, I recommit it - working copy small error.

**Comment by stefankueng** [comment]
but the file in your repo is the same - I got the whole source.zip and when I extract the Russian.lang file, there's nothing to commit - git does not see any changes to commit.

**Comment by VictorVG** [comment]
- this is new commit - https://github.com/VictorVG/Source/releases/tag/grepwin202rus.1 

In my repo the same hashes for different tags were shown. I had to roll back from the point of failure and reload.

**Comment by stefankueng** [comment]
ok, done. Thanks!
