### ISSUE TITLE
Search option to get regex captures

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/grepWin#171]
implement a new search function:

- only works for regex searches
- the replace string is used as the capture string

So, for example you search for `([^@ \t\r\n]+)@([^@ \t\r\n]+\.[^@ \t\r\n]+)` and the replace string is `Email: $1@$2`, then you'll get in the search results all found email addresses in the format `Email: myname@hosting.com`

Then add some way to export all found captures, e.g. to a text file. Or even write all captures to a temp file and open it in notepad automatically when the search is done.

**Comment by nullnullnullnull0** [comment]
Taking the email address as an example, if 3 email addresses are on the same line, only the first one will appear in the search results.
txt:1@hosting.com 2@hosting.com 3@hosting.com
Search results:1@hosting.com

**Comment by feeas** [comment]
Can you add a matching part option under the export options? Instead of just match lines.

**Comment by stefankueng** [comment]
do a capture search, then export those matches
