### ISSUE TITLE
Plaintext log files that have a few particular unusual characters but are otherwise plaintext are misidentified as binary files

### ISSUE THREAD

**Issue by BujuArena** [stefankueng/grepWin#172]
To reproduce, search in a folder of IRC logs saved by mIRC.  When this issue was discovered, the folder had 1477 ```*.log``` files with evenly-varying file sizes from 1 KB to 589953 KB.  "Limit search" settings were set to "All sizes", "Include system items", "Include hidden items", "Include subfolders", "Include binary files", and "All dates".  "File Names match" was set to ```.*\.(lua|toc|c(pp|s)?|h|mm?|xml|unity|sh|[xy]ml|txt|log)$```.  More of the files misidentified were the largest files, but at least one of the ```*.log``` files that was misidentified was smaller than 10000 KB though, so size seems to not be a deciding factor; instead, it's suspected to cause bias toward having the unusual characters that causes the misidentification.

Current behavior:
Plaintext files can be misidentified as binary files and not show line matches properly.  When this happens, the match results say "binary" in the "Line" field and have an empty "Text" field.  When those files were opened in Notepad++ to find the result, the log was readable and the file was obviously not a purely unreadable binary file.  Some unusual characters were found that other users were able to type into IRC chats in most of the biggest log files, but that was not the majority of the text, and those unusual characters were able to be saved into the log file without breaking mIRC's loading of the log files on startup.

Expected behavior:
Large plaintext files with a few unusual characters are expected to not be identified as binary files.  Some sort of reasonable (or even configurable) threshold for proportion of plaintext to unusual characters for detecting whether a file is not plaintext is expected.

**Comment by stefankueng** [comment]
- if a file contains more than two double-null bytes (two 0 bytes after each other, with no other byte in between), it is considered binary.
- if a file contains a BOM and contains more than three null bytes, it is considered binary

since binary files are still searched, I think that's a reasonable assumption.

**Comment by BujuArena** [comment]
Unfortunately that assumption seems to not be reasonable with these misidentified files I have which have megabytes of plaintext with a few null characters in them.  Those 2 or 3 in a row somewhere should not make the whole file considered binary.  Maybe if that pattern exists every x bytes instead?

**Comment by stefankueng** [comment]
I'll add an option to configure the number of allowed null bytes. Maybe even make it depending on the file size.

**Comment by BujuArena** [comment]
Also, I noticed some are considered binary in various searches but did not appear in the results list when searching for ```\x{0}```.

**Comment by stefankueng** [comment]
That's another problem: using \x{0} requires wide-string search (unicode char), which isn't done with binary files.
Use \x00 instead: that works for all search types.

**Comment by stefankueng** [comment]
Also see issue #169
