### ISSUE TITLE
What about: Inverse Search (Not searchstring) AND Capture Search AND Search in found files

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#178]
hello, those new features,  " Inverse Search (Not searchstring) AND Capture Search AND Search in found files" , can you be more specific in telling us what each one is used for?

**Comment by stefankueng** [comment]
- inverse search (NOT searchstring): finds all files where the searchstring is not found
- search in found files: if you do a search, you can search again in all the files that were found in the search before (the ones listed at the bottom of the dialog). This speeds up the second search
- Capture search: enter a capture string in the "replace/capture" box. That is used to extract the regex captures. see #171 for an example
