### ISSUE TITLE
[Feature request] Add command line parameter to export search results to file

### ISSUE THREAD

**Issue by jogo-** [stefankueng/grepWin#180]
It would be great for automation to add such command line parameter to export the search results to a specified file, without showing any GUI :
/exportfile:"filename"

https://github.com/stefankueng/grepWin/issues/23#issuecomment-410164319

**Comment by stefankueng** [comment]
without showing any GUI will never happen: grepWin is an UI app. There are tons of command line regex tools available that never show any UI.
