### ISSUE TITLE
Escape key is invalid

### ISSUE THREAD

**Issue by maboroshin** [stefankueng/grepWin#181]
"Escape key closes grepWin" is on, but Escape key is invalid (can't close).

I tested between ```grepWin-x64-1.7.2_portable``` - ```grepWin-x64-2.0.3_portable``` on ```Windows 10 64bit 1909```.

**Comment by stefankueng** [comment]
strange, this works fine for me here.
is maybe a search still going on?

**Comment by f6fvy** [comment]
[OT] What about using Esc to stop a search ?

**Comment by maboroshin** [comment]
I Assume:  "Escape key closes grepWin" means grepWin's window closes.

But. Nothing happens on my desktop PC. And I used [KeyboardStateView](https://www.nirsoft.net/utils/keyboard_state_view.html), Pressed key is the ```ESC Key, 0x1b```.

I read stefankueng's comment and tried it on another laptop PC. I assumed that the cause was my desktop. But, Pressing the ESC key while searching does not stop the search. Also, the window doesn't close.

**Comment by maboroshin** [comment]
I understand Javascript well. Not C. So maybe...

I read code ```if (!DWORD(CRegStdDWORD(L"Software\\grepWin\\escclose", FALSE)))```. https://github.com/stefankueng/grepWin/blob/main/src/SearchDlg.cpp#L552

But I only use the portable version. Portable version are general known as not using a registry.

I checked "```HKEY_CURRENT_USER\Software\grepWin```" on registry. It is stored "windowposBookmarks" only in there.
