### ISSUE TITLE
Option to remove "search with grepWin" from Explorer context menu

### ISSUE THREAD

**Issue by AO-TERRA** [stefankueng/grepWin#183]
I would like to be able to remove the "search with grepWin" option from the Windows Explorer context menu.
It would be ideal if this could be a toggle option in the Settings menu.

**Comment by stefankueng** [comment]
run grepWin from a command line like this:
`grepWin.exe /unregister`
make sure that if you installed grepWin as an admin, you do this from an admin console.

**Comment by ashikns** [comment]
@stefankueng It looks like the windows 11 context menu entry is not removed with this command.

**Comment by stefankueng** [comment]
no, the windows 11 context menu is very different. Entries there can not be removed by editing the registry.
Just use the portable version of grepWin instead. I mean if you don't want context menu entries, you don't need the install version.

**Comment by DRSDavidSoft** [comment]
@stefankueng Any other way to remove from Windows 11 context menu and only keep the older Windows 10 menu?

**Update:** Found class in registry with key `3C557AFF-6181-4BBC-937D-E2FE8844DD49` that was pointing to `ExplorerCommandVerb.dll` and deleted it. Works fine!
