### ISSUE TITLE
search results column "Path" empty in grepWin versions after v1.9.2

### ISSUE THREAD

**Issue by nod5** [stefankueng/grepWin#185]
The search results column "Path" is empty in grepWin versions after v1.9.2 for me in Windows 10.

![path column empty](https://user-images.githubusercontent.com/11015788/88683735-68f97d00-d0f4-11ea-9de3-9408809438a5.png)

**Edit:** I was wrong. The column "Path" in versions > 1.9.2 shows relative path. The column is only empty for search result items that reside in the base search folder. In 1.9.2 and older the column showed the file's full folder path. I request an option to bring that behaviour back.

**Comment by stefankueng** [comment]
Well, I can't just bring that option back, since the new behavior was explicitly requested. And I don't want to add another option to the settings dialog for this. I think the new behavior is better than the old one, so I'll keep it as is.

**Comment by nod5** [comment]
@stefankueng Both behaviours could be supported without additional settings dialog entries if you add an extra column "Full Path" and make columns possible to hide via right click menu, like in Windows 10 File Explorer.
