### ISSUE TITLE
Regex: REPLACE DOES'N WORKING:  ?1\l\1:,\x20\l\2

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#187]
hello, I have this regex:

SEARCH: `(?s)<title>.*?<\/title>.*?(?s)<meta\x20name="keywords"\x20content="\K(\w+)|\G[^\w\r\n]+(\w+)`

REPLACE BY: `?1\l\1:,\x20\l\2`

The replacement doesn't work too well. here's what I get (that **?1;** should't be there)

`<meta name="keywords" content="?1perspectiva:, ?1:, prim?1:, planului?1:"/>`

**Comment by stefankueng** [comment]
?1 doesn't work in any regex flavor I know. It's always $1

**Comment by me-suzy** [comment]
works always only in notepad++ (and probably in subime text)
