### ISSUE TITLE
Allow to open another window on the same folder from grepWin itself

### ISSUE THREAD

**Issue by j4yk** [stefankueng/grepWin#189]
As a developer I want to open another grepWin window on the current folder from within grepWin itself, so that while searching for callers of a function I can keep my current grep results (content/line match view) and search for the next function in a call hierarchy. Otherwise I have to either find my Windows Explorer window with the folder to open another grepWin window, or search in the same window, but lose my previous search results (and the search term) in the process.

In other words, I would like something like a Fork, Clone, or Duplicate button in the window.

Instead of a call hierarchy there is also the case when I search for the definitions and usages of configuration parameters, environment variables, or Java properties (or similar) and find related functions/variables/... in the middle of the results. Then I also need a new grep in the same space. In contrast to the user story above, this is not tied to a programming language and therefore cannot be performed by the code introspection of a proper IDE, only through a plain text grep feature. So it might be less "out of scope" for grepWin than supporting the navigation of call hierarchies.

**Comment by stefankueng** [comment]
any suggestion on where to put such a button?
I'm thinking of putting it in the system context menu (right-click on the window titlebar or the icon on the left of the titlebar of the grepWin dialog window). But then most users won't even notice that it's there.
Adding a button to the dialog would have users notice it, but where? It shouldn't be in any of the group boxes because cloning doesn't belong to e.g. the "search" parameters or the "Limit search" options. Also not to the "search results" because those won't be cloned.
So: any suggestions?

**Comment by hpwamr** [comment]
Maybe there ? 🤔 

![2020-09-12_111946](https://user-images.githubusercontent.com/34211772/92992399-eb929c00-f4ea-11ea-8632-1b5a0f528f90.png)

**Comment by stefankueng** [comment]
I thought about that too. But isn't that a little bit too visible for such a rarely needed command?

**Comment by stefankueng** [comment]
Also: the problem with the checkbox sizes should be fixed in the latest version, are you not using 2.0.3?

**Comment by hpwamr** [comment]
> Also: the problem with the checkbox sizes should be fixed in the latest version, are you not using 2.0.3?

Affirmatif:  `grepWin-x64-2.0.3.936_portable (2020/07/12 19:31:43)`

**Comment by j4yk** [comment]
The link at the top right is fine for me. Find my ideas below if you would like to think about alternatives. It looks like you also clone the search expression into the new instance; will it be fully selected in the new instance so you can immediately type over it? If that is not possible I think it would be more practical to leave the search expression empty in the new instance. If I should open another issue for this, please let me know.

My suggestion would have been to add a button next to the "..." button of the search path text box because it essentially "Start[s] another grep in this directory." Though I am not certain which short text to put on such button because "Clone" and "Duplicate" are ambiguous with respect to the directory and "Fork" is a too technical metaphor. Maybe "+" or "⑂" and defer all explanation to the tool tip. With a single character on the button, the button could also be placed left of the text box.

Sticking with the call hierarchy use case, it would also be plausible to add this action as "Start another grep" in the context menu of a file hit entry of the "Content" results view. Or in the context menu of the "Search for:" text box as "New search in the same directory" or similar. Context menu entries might not be discovered as you mentioned.

Since the action starts a new search, a button labelled "New" or "New search" in the Search group box (next to the search text or at the bottom right) might also work, though it might not be intuitive enough what it does. On the other hand it does not hurt to just try out the button (or link)...

**Comment by stefankueng** [comment]
changed the link to a button and moved it right of the path-browse button as you suggested. That's much better.

and yes, the focus is automatically set to the search box when grepWin starts.
