### ISSUE TITLE
Can not open file with default application.

### ISSUE THREAD

**Issue by wangshuai-007** [stefankueng/grepWin#190]
My computer instaled SSMS 2017 and SSMS 2018.
Usually,I use SSMS 2017,So I set the SSMS 2017 is the default application of sql file.
But when I right click the file and click Open ,It will open in SSMS 2018.

**Comment by stefankueng** [comment]
The "open" context menu entry is from the shell menu. And the shell opens the file. Can't do anything in grepWin here.
