### ISSUE TITLE
Copied text results trailing space

### ISSUE THREAD

**Issue by owillebo** [stefankueng/grepWin#191]
After selecting 'Copy text result to clipboard' there is a trailing space behind the copied line which is not in the file.

For instance, I search for 'useless-object-inheritance', grepwin finds the following line;

'class Coords(object):  # pylint: disable=useless-object-inheritance'

This line has no trailing space.

Now when I select 'Copy text result to clipboard' and past it somewhere I get an additional space.

'class Coords(object):  # pylint: disable=useless-object-inheritance ' <= trailing space

I kindly ask to copy the result without the trailing space.

**Comment by stefankueng** [comment]
are you sure you're using the latest version? (2.0.3)
looks a lot like #156

**Comment by owillebo** [comment]
Thanks Stefan,

I should have given the version initially, excuse me, here it is now;
grepWin version 2.0.3.926
2020/07/13 19:31:43

With CRLF line endings I get an additional trailing (not leading) space for
any line in a file.

With LF line endings there are no extra spaces.

Following #156 issues is still there;
"The same search on the same file content with Macintosh EOL (CR) gives the
found line + all subsequent lines separated by spaces."
Only "subsequent" is now previous.

Have a nice day,

Okko
