### ISSUE TITLE
translations for grepWin 2.0.4

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/grepWin#192]
the language files are updated and need translating.
@VictorVG @rob-daneel @tetri @mlipok @wvxwxvw @maboroshin @hpwamr
if you have time to do the translations, that would be great!
I'd like to do the release sometimes next week.

**Comment by VictorVG** [comment]
I'll do it. Only the sources will be updated.

**Comment by VictorVG** [comment]
Ready and commited [**grepWin 2.0.4 Russian translation**](https://github.com/VictorVG/Source/commit/6aebefb18395c7fd95016ba05a0151b177f0ad3b) file also available as [**Russian.lang**](https://github.com/VictorVG/Source/releases/download/grepWin204/Russian.lang) in to my repo.

**Comment by stefankueng** [comment]
@VictorVG  thanks!

**Comment by VictorVG** [comment]
You are welcome

**Comment by rob-daneel** [comment]
Hello,

this is the updated Italian translation file.

Best regards.

[Italian.zip](https://github.com/stefankueng/grepWin/files/5246833/Italian.zip)

**Comment by stefankueng** [comment]
thanks!

**Comment by mlipok** [comment]
little to late.... but done.
https://github.com/stefankueng/grepWin/pull/196
