### ISSUE TITLE
Using the GUI to create the command line

### ISSUE THREAD

**Issue by mckuipers** [stefankueng/grepWin#194]
Hi

I've just looked at your tool and it looks really good!
Perhaps this already exists, but otherwise this would be great to have

Use the GUI to determine the search / replace, but then have a button that composes the command line version of it.

Why:
I have clone scripts for a number of projects. after cloning there are several files that need to be amended (made to work side by side with another version of the same app.
Right now I'm using a complex sed script while on windows.

I'd prefer to use your tool but it would be so cool if I could select in the GUI what I need, then it generates the command line that I can then copy into my script.

**Comment by stefankueng** [comment]
I think that's a too specific use case to be worth implementing. After all, the command line interface is not the main feature of grepWin (it's an UI tool after all). For command line searches, there are many command line grep tools out there.
