### ISSUE TITLE
Group referencing with $1 doesn't Work

### ISSUE THREAD

**Issue by Oz-Han** [stefankueng/grepWin#202]
Hi,

currently in use: grepwin 2.0.4.961

I replaced 
`ST(.)?56`
with 
`ST$157`

this turned 
 `ST.56`
into 
 `ST`

Using `\1` instead of `$1` worked just fine (the result being `ST.57`). 

Using `$1` in the "Test regex" window does work.

Kind regards
Oz

ps: love the tool! Thanks for your great work!

**Comment by stefankueng** [comment]
Since your replace string contains numbers right after the `$1` it's not possible for the regex engine to determine whether you meant `$1`, `$15` or `$157`. In that case you have to put the number in brackets: `${1}`.
So you have to use `ST${1}57` instead.

I'll update the docs...
