### ISSUE TITLE
Make "Search for" input possible see previous input

### ISSUE THREAD

**Issue by gemal** [stefankueng/grepWin#203]
if I place my cursor in "Search in" or "Replace with" fields and click arrow up or arrow down the previous input are show

But this is not the case with the "Search for" input

using 2.0.4.961 on Windows 10

**Comment by stefankueng** [comment]
works for me.
But if there's already text in that field and no previous search terms match that text, nothing is shown. So clear the text field first.
![image](https://user-images.githubusercontent.com/665591/95647923-c71ee500-0ad3-11eb-9aaf-3bf5f627a76e.png)
