### ISSUE TITLE
The "No backup" warning pops up despite having the option ticked

### ISSUE THREAD

**Issue by f6fvy** [stefankueng/grepWin#204]
Unless I misunderstand it, this warning should not pop up in these conditions. The backup file is created, as expected.

![grepWin_Backup](https://user-images.githubusercontent.com/12431844/97443300-292c7680-192b-11eb-8a27-619d2a8a5aa9.png)

**Comment by stefankueng** [comment]
Seems this was a user request: to avoid accidental clicks on replace instead of search.
https://github.com/stefankueng/grepWin/commit/c2cc8a6ea8e50602b2267ef8e67a0869e983eed2

**Comment by f6fvy** [comment]
Actually, I'm not against the warning regarding the empty string. The bug report was concerning the "without creating backups" in the alert text, despite the option was ticked. My report was probably not clear enough.

**Comment by sergeevabc** [comment]
@stefankueng, this issue does not seem to be resolved.
I have no backups despite checkbox is set, version 2.0.6.1006.
