### ISSUE TITLE
grepWin 2.0.4 is crashing in Virtualbox

### ISSUE THREAD

**Issue by irwir** [stefankueng/grepWin#207]
The issue related to Virtualbox and reported in #177 was not resolved, both 32-bit and 64-bit portable executable failed.

Virtualbox 6.1.16 with
Windows 10 20H2 19042.685 32-bit
or
Windows 10 2004 21277.1000 64-bit and 64-bit portable.
These are the currently installed versions, but grep failed in previous versions also.
There was no crash in the host Windows 8.1 64-bit and 64-bit portable.

How is was reproduced (32-bit).
Copy portable executable to `c:\bin` (no saved configuration).
Create `c:\test` directorry (empty)
Launch grep
Search in: `c:\test`
Text search
Search for: `abcd(`
Replace with: `dcba(`
Untick `subdirectories search` and `system items` checkboxes (not necessary)
Click `Replace` (to watch huge resources usage - start TaskManage before clicking)
Hang, crash, event log record...

Event log
> 
> Faulting application name: grepWin-2.0.4_portable.exe, version: 2.0.4.961, time stamp: 0x5f677215
> Faulting module name: grepWin-2.0.4_portable.exe, version: 2.0.4.961, time stamp: 0x5f677215
> Exception code: 0xc0000409
> Fault offset: 0x000c8f82
> Faulting process id: 0xae0
> Faulting application start time: 0x01d6d086ee36f005
> Faulting application path: C:\bin\grepWin-2.0.4_portable.exe
> Faulting module path: C:\bin\grepWin-2.0.4_portable.exe

**Comment by stefankueng** [comment]
any way to reproduce this without virtualbox?

**Comment by irwir** [comment]
Sorry, no idea - as said, it did not crash in the host.
Does the crash offset give any clue?

Maybe this [link](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) would be helpful in dealing with Virtualbox.

**Comment by stefankueng** [comment]
I hope you don't expect me to download 20GB and install virtualbox just to debug this...

**Comment by irwir** [comment]
`This` could hint on other issues. For example, it could be related to #132.
I made a report, how you deal with it is up to you.

**Comment by stefankueng** [comment]
closing as dupe of #226
also please see this: https://github.com/stefankueng/grepWin/issues/226#issuecomment-803135021

**Comment by irwir** [comment]
I cannot recall what were the issues of VirtualBox with Hyper-V long time ago, but it had to be turned off - and stays this way.

Checked 2.0.7 in the upcoming Windows 10 21H2 64-bit (4 GB of RAM) and the latest VB.
Task Manager was started and switched to Performance tab, then grepWin was doing a simple text search (not even replace).
CPU quickly went to 100%, memory usage went up too. Mouse was moving, progress bar was moving sometimes, but otherwise the system got hung. After maybe a minute grepWin was gone; CPU and memory went down to normal.
