### ISSUE TITLE
Administrative installs are installing on a per-user basis

### ISSUE THREAD

**Issue by codaamok** [stefankueng/grepWin#208]
In releases before 2.0.4, administrative installs installed correctly i.e. landing in Program Files if install as administrator or NT AUTHORITY\SYSTEM. In 2.0.4 this seems to be different where the installation always occurs in the executing context's appdata directory.

For example, if NT AUTHORITY\SYSTEM installed grepWin then the binary would be located in in `C:\Windows\system32\config\systemprofile\AppData\Roaming` and therefore unavailable for all users on the system.

Even if the user had local administrative rights and granted the installer elevation at the UAC prompt, it installs only in that user's appdata directory - still inaccessible for the rest of the users on the system.

I suspect it was the work done in this commit https://github.com/stefankueng/grepWin/commit/c731d939e97756b325cce48137cb0175ebc3e16e which introduced the changes.

From a system administrator point of view, this makes it difficult to distribute to systems en-masse and system-wide. Would you consider reverting the change or perhaps improving it?

Thanks!

**Comment by stefankueng** [comment]
this has already been fixed:
https://github.com/stefankueng/grepWin/commit/4e0028373f852348525e65dc9630a0d09a2e4126

seems I need to make a new release soon...
