### ISSUE TITLE
grepWin is not allowing me to search in specific files.

### ISSUE THREAD

**Issue by smogmanus** [stefankueng/grepWin#209]
Hello,

I use grepWin all the time.  Today I was  planning on updating specific Autohotkey files.  I noticed it is grayed out and has no option to ungray it.

Do you have any suggestions.  Love your software.

Brad Schrunk

**Comment by stefankueng** [comment]
what is grayed out?
what does updating autohotkey files have to do with this?

**Comment by stefankueng** [comment]
no answer for 20 days - closing now.
If you're willing to provide more info, I can reopen the issue.

**Comment by smogmanus** [comment]
Thank you it was user error

**Comment by smogmanus** [comment]
Just user error,  I love your software
