### ISSUE TITLE
allow to specify a file which contains the search parameters instead of passing them all on the command line

### ISSUE THREAD

**Issue by kirkw** [stefankueng/grepWin#211]
Situation, I have 4 LONG paths to search through, with a | to separate.
This is for a specific Project.  Which comes with it's own FILTERS on extensions and folders!

These Items seem to work TOGETHER for me.  It's kinda like:
What to search for (At the top)
And WHERE to search below that.

They seem to go together logically.  
Also, the commandline option doesn't work with | long Folders.  You cannot create such a shortcut, which is what I tried doing.

Finally, how do I remove some of the INCREMENTAL remembered options from the [/] list/dropdowns?
==

Again, these 4 paths are specific to this project.  When I switch back to other projects, my paths and file extensions/exclusions tend to change with the project...  A Single Context, and Saving more contexts like that would be REALLY NICE.

Bonus points to allow me a command line parameter to load a specific preset!

**Comment by stefankueng** [comment]
you can remove remembered entries from a dropdown like in most other apps:
with cursor up/down select the entry, then press shift+del

**Comment by stefankueng** [comment]
creating a shortcut with` /searchpath:"d:\path1|e:\anotherpath"` works fine for me.

**Comment by kirkw** [comment]
Okay, I have 4 folders, and JUST the 4 folders themselves EXCEED the ability to save the shortcut Command Line.
The limit is like 258 characters for the entire shortcut command line.  And there is the STRONG possibility I will have one more set of folders to be searching... (Additively).

My 4 search folders is 238 characters, leaving no room for the reference to EXE file.
And I was also hoping to LINK the long list of file extensions/exclusions, but there is not enough command line left.

THANK you for taking the time to answer.  The tool is much appreciated!

A command line /searchINI:"C:\...\somesearch.ini"

[settings]
searchpath=...|...|...|
skipfolders=
fileextensions=*.*|-*.dll|-*.exe|-*.svg|-*ttf|-*.swf|-*.eot|-*.nupkg|-*.jpg|-*.pdb|-*.png|-*.psd|-*.pdf|-*.woff|-*.otf
;whatever setting you want to allow...

would not have the limitation of the command line length.

But I tried to make the shortcut and run into the clipped last folder...
