### ISSUE TITLE
All version's : error writing paths to grepWin.exe in the Registry during PerMashine installation mode

### ISSUE THREAD

**Issue by VictorVG** [stefankueng/grepWin#212]
When the installation mode is selected for "all users", incorrect paths to grepWin.exe `%LocalAppDataFolder%\Programs\grepWin` are written to the Registry. According to the source code, this in theory should not be, but checking the Registry indicates that regardless of the installation mode of PerMashine or PerUser, the paths to the executable module are always written in the form `%LocalAppDataFolder%\Programs\grepWin\grepWin.exe` and when called from the OS context menu displays a message about an application search error, as well as it can be seen from its icon.

**Comment by stefankueng** [comment]
did you try version 2.0.5?

**Comment by VictorVG** [comment]
Yes, I checked it yesterday for v2.0.5.986 - this phenomenon is reproduced on all three machines used in the experiment. Here is a snippet of the Registry with one of them:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\grepWin]
@="search with grepWin"
"Icon"="C:\\Users\\*****\\AppData\\Local\\Programs\\grepWin\\grepWin.exe,-107"
"MultiSelectModel"="Player"

[HKEY_CLASSES_ROOT\*\shell\grepWin\command]
@="C:\\Users\\*****\\AppData\\Local\\Programs\\grepWin\\grepWin.exe /searchpath:\"%1\""
```
although the installation took place in C:\Program Files\grepWin

**Comment by stefankueng** [comment]
tried an install on a fresh VM (i.e. no previous grepWin installs) - it works as expected.
Please try a full uninstall first, then install it again.
Maybe the installer bug in 2.0.4 is interferring here.

**Comment by VictorVG** [comment]
Yes, I manually cleaned the OS by deleting all the old Registry entries - there were a couple of versions 2.0.3 and 2.0.4 - the .MSI installer does not clean them up, re-installed 2.0.5.986 and the error disappeared. Probably it was generated by one of the old installations on top of which new versions were installed as updates.

**Comment by stefankueng** [comment]
ok, so I'm closing this for now

**Comment by VictorVG** [comment]
Of course, because we understood what was happening and how to prevent this phenomenon now. And then we can come up with a way to eliminate it.
