### ISSUE TITLE
All files skipped on network share

### ISSUE THREAD

**Issue by belqit** [stefankueng/grepWin#214]
![image](https://user-images.githubusercontent.com/44238749/105478216-3398ab00-5ca3-11eb-997d-970fdba775e5.png)

**Comment by belqit** [comment]
But if I run it as Administrator it works...

**Comment by stefankueng** [comment]
If you've mounted the drives as Admin, then only Admin has access to it.
Also note that you've excluded "node_modules" from the search, maybe all your files are there?

**Comment by belqit** [comment]
![image](https://user-images.githubusercontent.com/44238749/105518911-1da5dd00-5cd9-11eb-9a01-ac978928eee1.png)

I noticed that is not a network share problem, is behaves like this in any folder.

until yesterday it worked...

**Comment by belqit** [comment]
![image](https://user-images.githubusercontent.com/44238749/105519444-b4729980-5cd9-11eb-8053-e8fd0880486a.png)

this was the problem 😂 sorry maybe I set it unintentionally
