### ISSUE TITLE
Feature request: avoid persisting settings when provided via command-line or INI file

### ISSUE THREAD

**Issue by HelderMagalhaes** [stefankueng/grepWin#215]
grepWin settings persist between sessions, which is a Good thing. Nevertheless, while attempting to speed up some tasks (via command-line parameters) I noticed that this neat feature became less useful. The rationale is that, when a complex configuration is loaded (via command-line parameters, for example), it's usually **not** a common configuration, so settings shouldn't be persisted for that session. This becomes a little more visible as #211 has recently landed.

Proposal was, therefore: if command-line parameters or INI file are used for persistent settings (_Search in_, _Search in_, etc.), skip saving any settings (i.e., skip `SaveSettings()`; also, `m_AutoComplete*`).

As this could not fit all users, a new setting could be added to control the behavior. Quick mock-up of the setting:
![grepWin-DontPersistSettings-Mockup](https://user-images.githubusercontent.com/557924/105677023-41d50a00-5ee3-11eb-94bf-ba59f2c0d267.png)
(Perhaps using positive logic? "[ ] Persist settings via command-line or INI file")

A more advanced approach/complete approach would be not saving only the settings affected by the command-line/INI file, but it would involve creating flags for every persistent setting.

**Comment by stefankueng** [comment]
since this is only useful when started via command line, how about another CL parameter `/nosavesettings` ?

**Comment by HelderMagalhaes** [comment]
> since this is only useful when started via command line, how about another CL parameter `/nosavesettings` ?

Like! 😉

> stefankueng closed this in 825db3c 6 days ago

A great enhancement for "preset" command-lines. Looking forward to see this listed in the [documentation](https://tools.stefankueng.com/grepWin_cmd.html) and in future releases. 👌

**Comment by kirkw** [comment]
I think this should be re-opened.

When using this switch I am getting EVERY Searched file listed, no context, and NO found strings...

I ran the program twice.  Once using an INI File WITHOUT the switch (Left Side), and again with the switch!

Can we put this switch inside the INI? [Once it is working, of course]

![image](https://user-images.githubusercontent.com/10579315/107981448-139d9400-6f90-11eb-803d-16905531009c.png)

**Comment by HelderMagalhaes** [comment]
> When using this switch I am getting EVERY Searched file listed, no context, and NO found strings...
> 
> I ran the program twice. Once using an INI File WITHOUT the switch (Left Side), and again with the switch!

By looking into both screenshots it seems that the regression is related with the _Inverse search_ setting/flag:
![Grepwin-SearchModifiers](https://user-images.githubusercontent.com/557924/107996202-baf1e980-6fd7-11eb-9a51-5053def4ce77.png)
(Note the file list, where none of the files in the left appear in the right.)


> Can we put this switch inside the INI? [Once it is working, of course]

IMHO this makes sense in **both** as well (I'm guessing in the INI _also_). 😉
