### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by bmaim** [stefankueng/grepWin#216]
Hello,
I just download the project and according to the file build.txt I tried to compile in VS but I received a lot of issue regarding missing files like: BaseDialog.h, DlgResizer.h, SimpleIni.h, registry.h.
I look for these files in the project folder (I downloaded the zip from github) and there are not.
I use VS Community 2019.
Can you tell me how can I compile in windows this project? 
Thank you very much,
Mircea

**Comment by stefankueng** [comment]
you have to clone the repository recursively to get the submodule
