### ISSUE TITLE
v2.0.6.1006, PerMashine installation - "The older version grepWin x64 cannot ne removed", but the previous version is removed and all traces of it in the OS are cleaned up.

### ISSUE THREAD

**Issue by VictorVG** [stefankueng/grepWin#220]
v2.0.6.1006 , MSI have propites:
```
[Properties]
UpgradeCode = {C73ED533-953E-47E5-9A42-A48292BB7C6C}
WixUIRMOption = UseRM
WixAppFolder = WixPerUserFolder
WIXUI_INSTALLDIR = APPLICATIONFOLDER
ALLUSERS = 2
ARPPRODUCTICON = grepWinIcon
ApplicationFolderName = grepWin
MSIINSTALLPERUSER = 1
Manufacturer = Stefans Tools
ProductCode = {09D41637-D4F6-455D-916F-AC4654F7348C}
ProductLanguage = 1033
ProductName = grepWin x64
ProductVersion = 2.0.1006
DefaultUIFont = WixUI_Font_Normal
WixUI_Mode = Advanced
ErrorDialog = ErrorDlg
SecureCustomProperties = APPLICATIONFOLDER;PREVIOUSVERSIONSINSTALLED
```
and SecureCustomProperties = PREVIOUSVERSIONSINSTALLED forces .MSI to search for the previous version, but since it does not exist, we get an image:

![1](https://user-images.githubusercontent.com/906886/106752701-cfc79800-663b-11eb-822d-df87262b3e36.png)

Now I see the only option - MSI as a selectively crooked technology in /dev>nul because such "feats" have long been known behind it, and just writing your own installer on NSIS or Inno Setup will take less effort than fixing the next mistakes of Redmond failers.

**Comment by VictorVG** [comment]
Upgrade v2.0.5 to v2.0.6 use PerMashine mode also failure - MSI always try remove old version, but this operation already returned FAILURE result then install can't continue...

**Comment by stefankueng** [comment]
there was a bug in the 2.04 installer.
Problem is due to that bug you have once to uninstall grepWin manually. After that it should work again and future updates as well.

**Comment by VictorVG** [comment]
The most interesting thing is that even after manual removal and complete cleaning of the OS from traces of the previous installation, including searching and deleting .MSI files, the error is reproduced for all registry entries for grepWin. It is also reproduced on a copy of the OS where grepWin has never been installed before.

I remember that in 2.0.4 there was an installer error that manifested itself in 2.0.5 and before updating to 2.0.6 I uninstalled version 2.0.5 via Revo Uninstaller Free, then with its help I cleaned up all the heuristics it found on medium settings (maximum leads to removing unnecessary is a "feature" of the Freeware version, and I don't see the point in installing Pro for a one-time operation), and then in Far Manager b5738 I manually checked and deleted all traces of grepWin in the system, the Registry Editor found and deleted all entries in its configs and only after that tried to put grepWin in PerMashine mode - search and unsuccessful attempt to delete a nonexistent old version, and then a message about the impossibility of deleting it.

Installation succeeds in PerUser mode.

Only PerMashine mode does not work.

**Comment by stefankueng** [comment]
just tried it (again) on a fresh machine - works like it should.
Using "cleaners" is never a good idea, because they more often than not corrupt the system. Why else would you get an error that an older version can not be removed? That means that it was removed, but the key that indicates it's installed is still there.

Maybe search your registry for C73ED533-953E-47E5-9A42-A48292BB7C6C - that's the installer key for grepWin.

**Comment by VictorVG** [comment]
This key is deleted, but error is exists.... :?
