### ISSUE TITLE
Where did the portability of the portable versions go?

### ISSUE THREAD

**Issue by wvxwxvw** [stefankueng/grepWin#221]
Portable versions of the current release write the settings to the registry. Why?  
Portable versions do not see the old INI file. Why?  
  
Or will you tell me again that everything is fine? )))

**Comment by stefankueng** [comment]
which settings?

**Comment by wvxwxvw** [comment]
What are your the answer options? Just wondering.

**Comment by stefankueng** [comment]
Which settings are still stored in the registry instead of the ini file?

**Comment by wvxwxvw** [comment]
Everything. All.  
  
Oh, I'm sorry. I have Windows 7 x64, if that matters.

**Comment by hpwamr** [comment]
> Everything. All.
> 
> Oh, I'm sorry. I have Windows 7 x64, if that matters.

Hello @wvxwxvw ,

With a freshly installed Windows 7 x64, I just tested `grepWin-x64-2.0.6_portable.exe` (Search and Replace of 350 items).

But I couldn't reproduce your issue ? 🤔
- I did not find any trace of grepWin in the registry.
- The `grepWin.ini` file has been successfully created with all needed keys in same folder of `grepWin-x64-2.0.6_portable.exe`.

**Comment by wvxwxvw** [comment]
@hpwamr 
Dear, do not tell me tales, there is no grepWin-x64-2.0.6_portable.exe and grepWin-x64-2.0.6_portable.exe in the releases. There is grepWin-2.0.6_portable.zip and grepWin-x64-2.0.6_portable.zip, inside these archives are grepWin.exe. And they write the settings to the registry.
![2021 02 06_145606](https://user-images.githubusercontent.com/13194155/107117449-8a010e80-688b-11eb-9618-4d6d3304e263.png)
  
Before version 2.0.4, there really were files with the name grepWin-x.x.x_portable.exe and I have no complaints about them.

**Comment by hpwamr** [comment]
> There is grepWin-2.0.6_portable.zip and grepWin-x64-2.0.6_portable.zip, inside these archives are grepWin.exe

Sorry about the misunderstanding.  🤔 
I know that inside the `Win-x64-2.0.6_portable.zip` file it's solely  `grepWin.exe`!
I've renamed it to `grepWin-x64-2.0.6_portable.exe` to emphasize that I test `grepWin.exe`, `x64`, `2.0.6`, `portable`.  😏

**Comment by stefankueng** [comment]
please rename the grepWin.exe to grepWin_portable.exe - I accidentally messed up the build script when zipping the files.
