### ISSUE TITLE
Change the original file encoding

### ISSUE THREAD

**Issue by SigmaStar** [stefankueng/grepWin#222]
If you replace some words from English to other language for example from English to Chinese. It would change the original file encoding due to many encoding types of Chinese (UTF8 UNICODE GBK), what about add a selection of encoding?

**Comment by stefankueng** [comment]
![image](https://user-images.githubusercontent.com/665591/107118076-f32e5500-687e-11eb-978d-5a656bb591e4.png)

**Comment by stefankueng** [comment]
there's a checkbox "treat files as UTF8" which means grepWin will load the file forcing an utf8 encoding.
otherwise, the file is loaded as is, and replacing will not change the encoding.

**Comment by SigmaStar** [comment]
But what about other encoding files? for example gbk, gb2312 or utf16 utf32？I&nbsp;think&nbsp;we can use the original encoding.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stefankueng/grepWin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 凌晨4:46
收件人:&nbsp;"stefankueng/grepWin"<grepWin@noreply.github.com&gt;;
抄送:&nbsp;"Furry"<2079688829@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [stefankueng/grepWin] Change the original file encoding (#222)





 
there's a checkbox "treat files as UTF8" which means grepWin will load the file forcing an utf8 encoding.
 otherwise, the file is loaded as is, and replacing will not change the encoding.

**Comment by stefankueng** [comment]
do you have an example file and search/replace string where the encoding changes?
