### ISSUE TITLE
Parsing: How to make a replacement of a regex from File-1 (Folder-A) to File-2 (Folder-B)

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#223]
hi, I have a regex that works in File-1 (Folder-A)

FIND: `(?s)(START).*(FINNISH)`

(this regex will select any lines from  START to FINNISH )

Now, I want to make a replacement in File-2 (Folder-B) and to put that selected lines over the word: **PUT-HERE-THE-CODE**

Should be something like 

FIND: `(?s)(START).*(FINNISH)` \ Folder-1
Replace on: `PUT-HERE-THE-CODE` \ Folder-2

How can I do this?

**Comment by stefankueng** [comment]
replacing only works on the file itself, so you can't automatically store the file with replacements in a separate folder. But you can copy the files from Folder-1 to Folder-2 and then do the replacement there.

your search string starts with `(?s)` - what's that for?

As for the replacement string: use $n to insert matched groups, something like this:
`$1PUT-HERE-THE-CODE$2`
should do the trick.

**Comment by me-suzy** [comment]
It can be used PowerShell for this kind of task:

    $sourceFiles = Get-ChildItem 'c:\Folder1'  
    $destinationFolder = 'c:\Folder2'

    foreach ($file in $sourceFiles) {

    $sourceContent = Get-Content $file.FullName -Raw
    $contentToInsert = [regex]::match($sourceContent,"(?ms)(START)(.+)(FINNISH)").value
    $destinationContent = Get-Content $destinationFolder\$($file.Name) -Raw
    $destinationContent = $destinationContent -replace 'PUT-HERE-THE-CODE',$contentToInsert

    Set-Content -Path $destinationFolder\$($file.Name) -Value $destinationContent -Encoding UTF8

    } #end foreach file
