### ISSUE TITLE
grepWin randomly crashes while searching on exFAT partitions

### ISSUE THREAD

**Issue by that-ben** [stefankueng/grepWin#228]
It is worth mentioning that grepWin randomly crashes while searching on exFAT partitions and there are numerous read errors too.  That drive and its files are sane and can be opened with text editors and whatnot.  After copying a folder of files from the exFAT partition to a NTFS partition, it makes grepWin search correctly (no read error) and no crash either.

I could not find any information regarding the partition type(s) grepWin supports on the product's official homepage.  This should be mentioned somewhere clear if it does not support exFAT.

**Comment by stefankueng** [comment]
grepWin uses the Windows APIs to search and open the files. There's no difference about which file system is used at all.

That said: when you refer to an "exFAT partition" you most likely mean an USB stick or something like that. Which means that's treated as an external device by virus scanners and that means they interfere as much as they can whenever a process tries to access files there. Since grepWin does this to many, many files at once, there's a big chance that the virus scanner has the file still  open/locked and grepWin then can't access it.

**Comment by that-ben** [comment]
No, I didn't mean an USB stick.  I meant an 8TB internal hard disk.  Windows 7 and above natively support exFAT partitions, tough it won't show the format option.  If you format the hard disk with Linux, then Windows displays it as an exFAT partition and lets you use it natively.

Regarding your other comment, that's exactly what I initially thought, but as a matter of fact it wasn't the case. I let the computer sit for 10 minutes with all programs closed and hit the scan again with grepWin and the exact same files were marked as "Read error".  grepWin would completely crash on the same folders which I could never finish scanning on the exFAT partition.

Simply copying that folder of files from exFAT to a NTFS partition and scanning them again with grepWin showed to have zero "Read error" and grepWin would not crash.  I have scanned over 4TB of files today on the NTFS partition and there was exactly zero result marked as "Read error" and zero crash.

It is 100% reproducible and it is solely tied to an exFAT partition vs a NTFS one, not to the actual DATA inside the files.

**Comment by stefankueng** [comment]
well, as I said grepWin does not differ between file system formats. It doesn't even know what format the files are on.
So there must be something on your end.
And letting the computer sit for 10 minutes won't help with virus scanners: they access a file right before a process tries to open a file - for single files the virus scanner is fast enough to release the file before the other process gets an access-denied error. But if a process like grepWin accesses thousands of files, then the scanner is too slow.

**Comment by that-ben** [comment]
If the AV was the problem, it would do at least return SOME "Read errors" on a NTFS partition too, yet after more than 400,000 files read on a NTFS partition, grepWin has not returned a single "Read error" nor crashed at all, a scenario that is instantly reproducible on an exFAT partition (the exact same computer, the exact same set of files, same AV program, etc...).

What I meant to say in my previous message was that the API that grepWin uses surely sees a difference between accessing an exFAT and NTFS partition, so indirectly grepWin suffers from this when searching on an exFAT partition for sure.   I used it more than 5 hours straight yesterday and not a single "Read error" came out of the same 400,000 files copied over to a NTFS partition.

**Comment by stefankueng** [comment]
while grepWin does not know about file system formats, an AV surely does.
Just try to add grepWin to the list of processes your AV will leave alone.

**Comment by that-ben** [comment]
This seems extremely unlikely, given that scanning the same exFAT folder 3 times in a row yields the exact same results (some specific files return "Read error" and some don't and it's the exact same files every time).  I don't think the AV would scan the same files 3 times in a row.  AV only scans a file once and if the hash (or shadow copy or whatever they use to detect if a file changed) does not change, then the AV does not rescan the file, especially not 3 times in less than 10 seconds.
