### ISSUE TITLE
Inverted Search (NOT Containing) is not working

### ISSUE THREAD

**Issue by kirkw** [stefankueng/grepWin#229]
Stefan,
  2 pictures says it all.  I was looking for PACKAGES where there is no "PACKAGE BODY" being declared.  These are errors.
  
  I knew there was at least one out there...  But I could not find it using that feature.
Here is the FOUND version
![image](https://user-images.githubusercontent.com/10579315/108890695-e2e6db80-75db-11eb-90ec-1a6d68b2b758.png)

And here is the Inverted search results being blank: (I changed the string to add " BODY")
![image](https://user-images.githubusercontent.com/10579315/108890741-f09c6100-75db-11eb-9298-2986b9a9b010.png)

This should be easy to reproduce/test...
I loaded this using an /ini file

**Comment by stefankueng** [comment]
works fine for me.
did you pass the /nosavesettings parameter?

**Comment by kirkw** [comment]
In my ATTEMPT to recreate, I found the problem.

I had CONTENT selected (LMAO).  I think for this search, you might consider switching it back to files!
