### ISSUE TITLE
Export search results to a text or csv file

### ISSUE THREAD

**Issue by joedf** [stefankueng/grepWin#23]
Just a feature idea. The ability to export the search results to a text or csv file would be nice feature and help for processing content-wise searching.

**Comment by jahhubba** [comment]
Absolutely, I agree!

**Comment by stefankueng** [comment]
You can select the entries (or all entries with Ctrl+A), then either hit Ctrl+C to copy the results to the clipboard and do whatever you want with it, or right-click and use one of the "copy..." entries at the top of the context menu.

**Comment by jahhubba** [comment]
All I get with a regular copy is a Windows 10 popup saying that the format is not supported. It does allow me to do a "Copy paths..." or a "Copy filenames..." but not a full copy of the results.

**Comment by stefankueng** [comment]
When and where do you get an error saying "format is not supported" ?

**Comment by joedf** [comment]
I'll have to try this. 👍

**Comment by joedf** [comment]
Works for me...

**Comment by jahhubba** [comment]
You can see what happens here:
http://friendsutrust.com/ScreenCapture.swf.html.

Just don't use Chrome, because it's flash.

Thanks,

John

**Comment by jahhubba** [comment]
I did my screen video on my Window 7 at my office. I believe that in
Windows 10, at home, it came up in the bottom right when I selected the
Copy command.

Thx,

John

**Comment by joedf** [comment]
You should try [LICEcap](https://www.cockos.com/licecap/).

**Comment by jahhubba** [comment]
Nice! I'll check it further.

Thanks

**Comment by PrakharPrashantSingh** [comment]
Hey jahhubba need your help man....... can u modify this program to transfer searched content directly into a text file.

In other words, when i search specific keywords from a file, i want a option there to transfer these keywords to a new file (maybe txt)......
![thing](https://user-images.githubusercontent.com/40795304/42219022-117d025a-7ee8-11e8-88b6-07582b90b98f.PNG)

**Comment by joedf** [comment]
yeah it gets a little heavy for the clipboard...

**Comment by Taneeda** [comment]
Command line option to export to file would be great for automation (with additional command to hide window)

/outfile:"..."
/hidewindow

**Comment by koolraap** [comment]
I'd argue current behaviour is a bug -- if you Select All, right-click and choose Copy it's different behaviour to Select All + Ctrl+C. The former is copying files, the latter is copying the search results.

It'd be nice if there was a Copy To Clipboard button and/or Export to Excel.

**Comment by SirSquish69** [comment]
> You can select the entries (or all entries with Ctrl+A), then either hit Ctrl+C to copy the results to the clipboard and do whatever you want with it, or right-click and use one of the "copy..." entries at the top of the context menu.

This wasn't obvious at all, but it's really cool that it works. Would you please consider adding an export button though? Were it not for stumbling on this thread, I would not have known about the copy/paste trick.

**Comment by BrockleyJohn** [comment]
That's a great big ME TOO. grepwin is my go-to when dealing with a file that's too big to open in an editor. Sometimes the list of matches is also huge and I'd really like just to route the output straight to a file. Ctrl+C & V works on the output list but if you inadvertently right click for a menu it just gobbles all the memory and stops.

**Comment by AnabasisXu** [comment]
An "export" option will make things easier.

**Comment by AnabasisXu** [comment]
An AHK solution to this problem:

!t::
Send,^c
Sleep 200
Data:=Clipboard
FileAppend,%Data%,%A_Desktop%\%A_Now%.txt
return



just ctrl+a, and then alt+t, then there will be a txt file on the desktop with all texts select. Of course, you can change "alt+t" to any key binding you like.

**Comment by YeisonHunt** [comment]
Just if someone needs, on chrome there is an extension called **_GofullPage_** that can export this on pdf or image, but you have to go to every result if there are a lot of pages.

**Comment by mrx23dot** [comment]
The export button ignores when 'content' is selected and still exports only the file names.
![2024-10-09 12_12_28-grepWin _ __192 168 0 1_Q _STM ECU Test Results](https://github.com/user-attachments/assets/127f6ef4-3315-47f7-8eed-749f17998b1f)
Could we add to consider which is selected? And maybe export it as csv or tab separated?

Would make post processing possible.
