### ISSUE TITLE
Subfolder(s) not searched

### ISSUE THREAD

**Issue by bits-bytes** [stefankueng/grepWin#230]
I have a very simple search to do.
Normal text in text files.
In the starting folder I have 54 files - they are searched. (message : searched 54 files....)
I have 2 subfolders as well in this folder with some hundred files - they are not searched. (e.g. named "old").
When I change search location to "...\old" the files are searched.

Regards
Manfred

**Comment by stefankueng** [comment]
"..\old" is NOT a subfolder but a sibling folder.

**Comment by bits-bytes** [comment]
Sorry, my mistake to write it a bit stupid like this ("..\old")

It is like this

<code>
mainfolder            (2 sub folders, 54 files)

      Info                 (folder)
      old                  (folder, not searched)
      file-1.txt
      file-2.txt
      ....
      file-54.txt

</code>

**Comment by stefankueng** [comment]
stupid question, but did you check the box "include subfolders"?

**Comment by bits-bytes** [comment]
yes I did.
I realized I had some version of 2019, so I upgraded to the latest one, but it is the same...

**Comment by stefankueng** [comment]
please attach a screenshot of your grepWin here - maybe you have some other settings done which prevent searching that folder?

**Comment by bits-bytes** [comment]
Hi,
I made another test. I suspected somehow from the beginning it might have a link to the fact that I am searching on a network drive.
So I copied the complete folder + subfolders to my desktop and test it again.

On my desktop it is working. On the network drive not.
But I have no clue why... ?
