### ISSUE TITLE
Suche in .doc funktioniert, .docx nicht

### ISSUE THREAD

**Issue by syberstef** [stefankueng/grepWin#232]
Hallo,

über die Suche werden mit .doc Dateien angezeigt, die den gesuchten Inhalt haben.
Im neueren Format .docx gespeicherte Word-Dateien werden hingegen nicht angezeigt.

Kannst du den Bug fixen?

Bis auf diesen Bug ein wirklich geniales Tool.
DANKE!

**Comment by stefankueng** [comment]
das ist kein Bug.
doc und docx-Dateien sind keine Textdateien, deshalb wird auch nix darin gefunden.
