### ISSUE TITLE
Idea/Feature request: Archiving of file content (databse) for faster searches

### ISSUE THREAD

**Issue by wisemike2** [stefankueng/grepWin#234]
I am not sure if this is the right place for that.  But could it be possible to add an option to archive the text content of files, for faster searches?

When there are tens tens or hundreds of thousands of files, it takes a while to search them.  But if there an archive database (based on directory/path.. etc.), it would show nearly instant results.  And one could update the database or rebuild it when needed.

**Comment by stefankueng** [comment]
Sorry, but that can't work.
grepWin uses regex to do the search. So creating a DB with only text content will have the effect that the content is not 1:1 anymore, and regex searches will not get the correct results.
