### ISSUE TITLE
Feature request: hide replace button in settings

### ISSUE THREAD

**Issue by SoftCyD** [stefankueng/grepWin#235]
To avoid mistakes is it possible  to have a setting to allow hiding replace button ?
I just want to grep. On Unix grep doesn't have a replace switch.
Thank you

**Comment by stefankueng** [comment]
the replace button is only active if there's text in the "replace with" edit box.
And if you try to do a replace without creating backups there's a warning dialog shown first (unless you deactivate that).

Hiding that button is going too far.

**Comment by SoftCyD** [comment]
I'm sure replace button is active even there's no text in "replace with" textbox. It's dangerous for me.
