### ISSUE TITLE
Binary/ForceBinary searches do not show matches in tooltip and report double the number of matches per file, version 2.0.6.1006

### ISSUE THREAD

**Issue by dkline1** [stefankueng/grepWin#237]
Version 2.0.6.1006

I discovered this by accidentally leaving "Treat files as binary" checked. For ANSI files, the preview of the matches in the tooltip works fine files and the number of matches per file is correct. but the tooltip still flashes during the search and it still would help a lot of it remained on the screen for a longer time, or until I mouse out of the filename.

When I do a search either of binary files or with "Treat files as binary" checked, and then hover over the filenames in Search Results, the preview of the matches that show up in the tooltip for non-binary searches does not appear, and the tooltip only contains the full path to the file. This might be the normal behavior for binary searches. However, the number of matches per file in Search Results is double the number of actual matches. This might also be by design and a consequence of leaving "Treat files as binary" checked, and then searching non-binary files. But if it is not, then it's a bug.

It would also help a lot if for all searches (binary or not), the tooltip remained on the screen for a longer time, or until I mouse out of the filename.

Additionally, when I hover over the filenames while the search is running for all searches, the tooltip flashes on the screen repeatedly, making it nearly impossible to read. I suspect that it has to do with the way that the Search Results table is being populated.

Thanks! I love grepWin!

**Comment by stefankueng** [comment]
you just found a six year old bug (showing the double of found items for binary searches)

**Comment by stefankueng** [comment]
about the tooltip: it flashes whenever the list control is updated.
Right now, it updates with a timer unconditionally while searching. I'll change that so it's only updated if a new entry is found.
But if you have a lot of matches so that new entries are added fast, the tooltip will still flash - nothing I can do about that, sorry.

**Comment by dkline1** [comment]
Thanks! I greatly appreciate all of your efforts. I especially like Dark Mode!
