### ISSUE TITLE
Snapping to top of results window during search

### ISSUE THREAD

**Issue by MrGroggle** [stefankueng/grepWin#238]
Repro steps: 

1. When a search is in progress, select an entry from the search results either using the shell menu with RMB or LMB
2. Allow the search to continue such that the scroll bar appears
3. Scroll the mousewheel down on the view, or use the scrollbar to navigate down
4. Observe the view after the scroll completes
5. Attempt to deselect the item using CTRL+Spacebar or CTRL+LMB, or click away from the view
6. Observe repeating step 3.

Expected behaviour: I can deselect an item and continue to scroll the view
Actual behaviour: When scrolling, shortly after the scroll has executed, the view snaps back to whatever item was last selected, with no clear way to disable this functionality. Attempts to deselect the item create a dashed border around the item, but do not prevent the view from snapping back to it. It is possible to select the bottom item in the view, and scroll will then continue to work until that item would disappear from the top of the view. When search concludes, the behaviour is no longer present. If an item is never selected, the behaviour is not present.

**Comment by stefankueng** [comment]
this was fixed with 31c2c4b2c7e8b8d463678552f038c8522bf18855
