### ISSUE TITLE
Please clarify license, AGPL or GPL

### ISSUE THREAD

**Issue by mrjoel** [stefankueng/grepWin#24]
The license previously was understood to be GPL2+ based on header comments in each source file. However, a recent commit added the LICENSE file which is AGPL3+. The AGPL doesn't seem to be super relevant for a desktop application (as opposed to remote network service providing code). Did the incorrect license get added into LICENSE inadvertently, or is it meant to imply a license change?

**Comment by stefankueng** [comment]
Sorry, my bad.
License was "GPLv2 or later", wanted to change it to GPLv3 - must have copied the wrong one.
