### ISSUE TITLE
"Include binary files" setting not saved

### ISSUE THREAD

**Issue by EnthusiastNT** [stefankueng/grepWin#241]
IDC_INCLUDEBINARY for some reason is disabled, and thus not saved as checked (or the checked state is not restored since it is disabled, either way, same result).

SearchDlg.cpp allows enable only if there is something to search for, which is empty when you start, obviously:
1154 DialogEnableWindow(IDC_INCLUDEBINARY, bIsDir && len > 0);
1190 DialogEnableWindow(IDC_INCLUDEBINARY, len > 0);

I'm sure there is a good reason, I just wish it would remember that setting. Maybe enable it before setting the check (lines 384 and 879), then disable it again.

I have to search through (proprietary) database files that contain lots of interesting strings, so binary definitely makes sense. Great program, btw, thanks for maintaining it!

**Comment by stefankueng** [comment]
enabled state has nothing to do with the checked state, so the checked state is always saved and restored.
The "include binary files" is disabled if the path is to a single file, which then doesn't make sense since that file is always searched.

**Comment by EnthusiastNT** [comment]
You are right, it wasn't the enable state. Just a typo that prevents "Include binary files" to be checked: should be m_bIncludeBinary instead of m_bIncludeBinaryC on line 348 of SearchDlg.cpp

**Comment by stefankueng** [comment]
closed by https://github.com/stefankueng/grepWin/pull/242
