### ISSUE TITLE
[Feature] Show the current dir during search progress

### ISSUE THREAD

**Issue by ulrichb** [stefankueng/grepWin#243]
During search it would be nice to show the current dir.

Use case: To see which directories (resp. directory prefixes) take long to search, so that these (in case they aren't relevant) could be added to the "exclude dirs" pattern in a follwing search.

**Comment by ulrichb** [comment]
BTW: Thanks for this great, great tool. Using it almost every day. ❤️

**Comment by stefankueng** [comment]
There's not really a "current dir", because the search is done with multiple threads, which usually don't search the same folders.

**Comment by ulrichb** [comment]
Oh, didn't think of this. So this wouldn't be really trivial (e.g. calculating a common dir prefix over all threads) ... so feel free to close this issue.

In any case, thx for your reply!
