### ISSUE TITLE
[Feature] Exclude matches of type 'read error'

### ISSUE THREAD

**Issue by GraniteRob** [stefankueng/grepWin#244]
I'd like to see a checkbox in the 'Limit search' section,  or a global setting 
instructing Grepwin to not display results matches of type 'read error'

**Comment by stefankueng** [comment]
why don't you want to see files that can not be searched? That's an important information when you're searching.

**Comment by wisemike2** [comment]
@GraniteRob 
I get "read error" when searching using forward slash **/** (E:/folder/subfolder)
But the issue is fixed when using back slash **\\** (E:\folder\subfolder)

**Comment by sicklittlemonkey** [comment]
@stefankueng 
> why don't you want to see files that can not be searched? That's an important information when you're searching.

Agree it can be important, but nicer to be able to make it go away, or put it in another window or something.

Otherwise, nice tool, thanks!
