### ISSUE TITLE
grepWin-x64-2.0.7_portable.zip contains no exe file <eom>

### ISSUE THREAD

**Issue by rarnold99** [stefankueng/grepWin#245]

**Comment by VictorVG** [comment]
_cp -f grepWin-x64-2.0.7_portable.exe grepWin.exe_ :)

**Comment by stefankueng** [comment]
sorry, removed the corrupted file

**Comment by rarnold99** [comment]
> sorry, removed the corrupted file

Make the life of unexperienced users easier; I am an IT professional so I knew the trick 
renaming the file using any file manager or the CLI :-)  - Thanks for your various helpful tools!
Greetings from Göttingen, Ronald - rarnold@uni-goettingen.de
