### ISSUE TITLE
Multi-undo

### ISSUE THREAD

**Issue by sergeevabc** [stefankueng/grepWin#246]
Dear Stefan,
Consider making multiple undo possible while editing the fields.
Right now it seems that I am able go back one step only.

**Comment by stefankueng** [comment]
cursor-down has a full list of previously entered patterns

**Comment by sergeevabc** [comment]
> cursor-down has a full list of previously entered patterns

I cannot accept this as a solution, Stefan, because previously entered patterns are not required, but undoing of current session edits are. Imagine I copy/cut/paste parts of regex from one place of the string to another and back, then want to undo. If that editing was happening in the Run dialog of Windows, undo would work fine, that’s why it is expected to work here as well.
