### ISSUE TITLE
Upgrade from 2.0.4 to 2.0.7

### ISSUE THREAD

**Issue by DaleyKD** [stefankueng/grepWin#248]
Tried to upgrade using `grepWin-2.0.7-x64.msi` from 2.0.4, and I guess the product code in the MSI didn't change?  It wasn't seeing it as an upgrade; it assumed it was the same version.

This forced me to uninstall and reinstall (that seemed to cause a few MSI caching issues, but I was able to get around those).

I'm good to go for now, but thought that for v2.0.8+, you may consider this?

**Comment by stefankueng** [comment]
the product code must never change for the same app - that's what marks an upgrade and not an installation of another app.
But the upgrade version code must change, and it did:
2.0.4  has version code 2.0.961
and
2.0.7 has version code 2.0.1040
So it should upgrade properly - did for me on three different machines, and all coworkers in the office didn't have any problems either.
