### ISSUE TITLE
How to disable Found  statistics

### ISSUE THREAD

**Issue by vvyoko** [stefankueng/grepWin#249]
I would like to add a space between lines
But because of the large number of files, I get stuck when I get to a part of it

I have tried other search terms before
Modify more files are no problem

I suspect that this Found data is too large and the process is stuck
Is there a way to disable this statistic?

search and replace word
```
\r\n
\r\n\r\n
```

![1](https://user-images.githubusercontent.com/2145741/116227901-37970600-a787-11eb-8ab4-2690d9b23b84.jpg)

**Comment by stefankueng** [comment]
with this search/replace pattern you end up in an endless loop!
You're replacing \r\n with \r\n and another \r\n. Then the search proceeds and find the just inserted \r\n (the second one), and replaces that with another \r\n and so on...

you need to search for
`\r\n(?!\r\n)`
meaning you're searching for a newline that's **NOT** followed already by another newline.
