### ISSUE TITLE
grepWin cannot find this kind of ï¿½ unicode characters ?

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#251]
hello, why grepWin cannot find this kind of ï¿½ unicode characters ?

**Comment by stefankueng** [comment]
grepWin tries to detect the encoding of files and search with that encoding.
So, if you want to search for the unicode replacement chars, you have to check the box "treat file as binary" so grepWin won't try to detect the encoding.

**Comment by me-suzy** [comment]
works, thanks
