### ISSUE TITLE
Remove fixed window size

### ISSUE THREAD

**Issue by shanedevane** [stefankueng/grepWin#254]
Hi
Minor issue 
Using grepwin 2.0.7.1040 
Using Windows 10
grepwin  It has a fixed minimum width set - this width is large and is over 50% of my  1920x1080 display - this prevents the window from being 'snapped' vertically with other windows in an easy way.
Told you it was a minor issue :)
Thanks
Shane

**Comment by stefankueng** [comment]
I don't think I can reduce the minimum width - controls and labels need the space without being cropped.

**Comment by shanedevane** [comment]
Yeah no worries. 
Great job with grepwin. It's an awesome tool
