### ISSUE TITLE
Can't open filenames with spaces in them

### ISSUE THREAD

**Issue by gondwanasoft** [stefankueng/grepWin#255]
Attempting to open `abc def.txt` results in opening two files: `abc` and `def.txt` (both of which presumably don't exist). When passing filenames (and probably directories), you may need to stick " around them.

Testing via Visual Studio Code.

**Comment by stefankueng** [comment]
it does put " around a path.
how did you start vscode from grepWin?

**Comment by stefankueng** [comment]
or, if you've configured vscode as the default editor in grepWin, then you have to put the quotes around the %path% yourself - there it's really up to you to do that.

**Comment by gondwanasoft** [comment]
I'm sorry; it was the latter. I'd forgotten that I'd done that configuration.
Don't you hate it when people raise issues for their own mistakes? ;) If it's any consolation, I've donated.
