### ISSUE TITLE
Feature Request: Database/File content indexing for instant search results

### ISSUE THREAD

**Issue by wisemike2** [stefankueng/grepWin#256]
I have a list of hundreds of thousands of files that I search regularly, could it be possible to add an option to archive/index file content to a database, for faster search results (instant search results)?  And when needed, one could run the indexer option now and then to update the database.

**Comment by stefankueng** [comment]
searching with a regular expression requires that content is left exactly as it is. Creating a db with e.g. words of a document therefore won't work at all.
