### ISSUE TITLE
How to find UTF-8 Unicode characters in several txt files?

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#258]
hello, I need to find in my text files all Unicode code. I know how to do this in notepad++ for each page. **Create new tab -> Menu -> Encoding -> Change encoding to ANSI -> Copy the entire text in that tab -> Change encoding to UTF-8.** This way you will see with BOLD writing style every Unicode Character.

But how to do this with several files? How to search all Unicode code in all txt files?

**Comment by stefankueng** [comment]
a little bit of research would have helped:
search for any char that's outside the ANSI range.

`[\x{00FF}-\x{FFFF}]`
