### ISSUE TITLE
File names matching bug in grepWin

### ISSUE THREAD

**Issue by michelverhagen** [stefankueng/grepWin#26]
Hi Stefan,

In your latets grepWin 1.8.1.778 file name matches don't work as they should (or at least how I think they should).

When I enter "sources.*" in the file names match box, I expect grepWin to find "sources." and "sources.inc" and "sources.cmn", etc, but it doesn't. It finds all sources files with an extension, but not "sources."

Even if I enter "sources." in the file match box, it won't find "sources.". I have to enter "sources" (so without the ending dot) for grepWin to actually find the search string inside my "sources." file.

File match option set to "Text Match" (no regex match selected).

I hope it is clear what I mean.

**Comment by stefankueng** [comment]
That's expected: the "Text match" uses a simple file-match glob. Meaning it works similar to the DOS wildcards.
If you really want to only find "sources.", you have to use the regex match with "sources\.".

**Comment by michelverhagen** [comment]
No, I don't JUST want to find sources., I expect "sources.*" to find all of the following:

sources.
sources.inc
sources.cmn
etc.

But it doesn't find the first one. Is that expected? If so, it is really counter intuitive... DOS finds sources. when I type "dir sources.*"

**Comment by stefankueng** [comment]
While you have to jump through a few hoops to even create a file with a trailing dot on Windows, I managed to get a test folder set up.
And grepWin finds the file just fine, even without using the regex match:

> Bookmarks
> Bookmarks..h
> Bookmarks.cpp

searching for 

> Bookmarks.*

returns all three files.

when using the regex match, enter

> Bookmarks\.(.*)?

And while we're at it: a file with a trailing dot causes a lot of problems on Windows. You can't even open it in most apps.

**Comment by michelverhagen** [comment]
Hi Stefan,

With "sources." I just meant "sources", so without extension (and also without a trailing dot). Apologies for not being clear. I've sent you an email with a testfolder and some screenshots. I hope that will clarify the issue.

**Comment by stefankueng** [comment]
If you want to find all files, even without any extension you can either search for
sources*
or
sources.*|sources

**Comment by michelverhagen** [comment]
Thanks Stefan!

Not exactly the same as DOS wildcards (because there sources.* finds "sources"), but I can live with sources*

**Comment by stefankueng** [comment]
I found a way to make this work as you expect it to.
But in my opinion, matching "sources" when the match string is "sources.*" is not strictly correct :)

**Comment by michelverhagen** [comment]
Super, thanks for all tools you provide, they are all MUCH appreciated!
