### ISSUE TITLE
Feature: Selected count at program taskbar

### ISSUE THREAD

**Issue by wisemike2** [stefankueng/grepWin#260]
It would be nice to show the number of selected files in the program taskbar when selecting..

![image](https://user-images.githubusercontent.com/16458615/120109829-6419b580-c16b-11eb-8eca-457bf1d09d3a.png)

**Comment by wisemike2** [comment]
Was that issue added?
I don't understand it being closed this in [3873b3d](https://github.com/stefankueng/grepWin/commit/3873b3dee81e30ecb8d1aca5c1bedd5b8d1ebf35)
Or do I need to tweak something to fix it locally?

**Comment by stefankueng** [comment]
it's scheduled for 2.0.9 - the current release is 2.0.8
