### ISSUE TITLE
[REQUEST] Unicode text search option

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#266]
Can you add Unicode text search?
Sometimes I need to find some long text strings for ANSI/UTF8/UNICODE mixed files... Would be handy an option to enable quick search of a string like: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." in all formats at once...

**Comment by stefankueng** [comment]
grepWin automatically detects the encoding of text files. So searching for a string does not depend on the file encoding, unicode (utf8, utf16 and even utf32) filea are searched as well.
Why do you think you need an option for that? I'm guessing you know the string is in a file and grepWin does not return a result?
So what's your search string exactly, and if possible what's the file you think grepWin should return a result for?

**Comment by Hexaae** [comment]
Oh! Sorry I missed it was able to find text in all these codeset already.
No prob then, and thank you for this precious tool!
