### ISSUE TITLE
"read error" if "search in" path doesn't start with drive letter

### ISSUE THREAD

**Issue by abhlabs** [stefankueng/grepWin#268]
Running 2.0.8.1054.   Doing a text search of *.cpp and *.cs files.   When I specify the "Search in" as

`\Projects\Product Name 16.0
`

I get "read error" on every file in the specified folder hierarchy.  If I change the "Search in" to

`C:\Projects\Product Name 16.0
`

It works perfectly.  I don't know if the spaces or the period in the folder name are relevant, and if it matters, there are dozens of subfolders and thousands of files.  Running on Win10 Professional

Obviously a minor issue, thanks for the fantastic program!

**Comment by stefankueng** [comment]
that's expected: the "current" directory is usually the one where the grepwin.exe is. So entering a relative path like `\Projects\Product Name 16.0` will then get resolved as `c:\program files\grepWin\Projects\Product Name 16.0` which doesn't exist.

**Comment by abhlabs** [comment]
"So entering a relative path like \Projects\Product Name 16.0 ...". 

A path that begins with a backslash isn't a relative path according to the way Microsoft defines relative versus absolute paths.  When the path begins with a backslash, it's assumed to start at the root of the current drive.  To make it a relative path, it would need to be ".\Projects\Product Name 16.0" (note the "." prior to the backslash.

[microsoft documentation](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)

**Comment by stefankueng** [comment]
ok, so the root of the `current `drive - but the problem is the same: which drive?

**Comment by abhlabs** [comment]
The GetCurrentDirectory windows api returns both the current drive and directory.    What I'd like to see is for GrepWin to search the same folders that a "DIR /s" would search given the same starting path. Open a command window, change directory to any arbitrary folder, then type the following two commands:

```
DIR/S \Projects\Product Name 16.0
DIR/S C:\Projects\Product Name 16.0
```
They produce the same results, regardless of what the current directory is.
