### ISSUE TITLE
Feature Request: Check for new version/update

### ISSUE THREAD

**Issue by rafi-d** [stefankueng/grepWin#272]
I just think it can be very convenient to have... :) 

Thanks!

**Comment by stefankueng** [comment]
there's already an update check done. If there's a new version available, a link is shown right of the "Presets" button.

**Comment by rafi-d** [comment]
I haven't noticed.  Do you mean this link will auto-download&update (which is what I meant) , or just refer to the site? I'll check it up again when 2.0.9 is out (with my columns adjustment fix) .. Any time soon?... :)

**Comment by rafi-d** [comment]
Running 1.0.6 -  I can see the link , which only get you to the site... Just that I never noticed it, so maybe , so maybe move it to the top - at the left for the about link (top right)?
