### ISSUE TITLE
can it be that wingrep does not work/start when you are having no internet?

### ISSUE THREAD

**Issue by f1-outsourcing** [stefankueng/grepWin#273]
Are you doing something in wingrep that is connecting to the internet?

**Comment by stefankueng** [comment]
yes: every seven days the file https://raw.githubusercontent.com/stefankueng/grepWin/main/version.txt is downloaded to check if an update is available. But you can disable this in the settings.
and it's grepWin, not wingrep - wingrep is another tool.
