### ISSUE TITLE
Feature Request: Add "whole word" search criteria

### ISSUE THREAD

**Issue by Netphilou31** [stefankueng/grepWin#28]
I,
I really love this tool that I use almost daily. However I found recently that there was no option to restrict the Search/Replace to "Match whole word" case. I think it would be an even better tool with this feature.
Best regards,

**Comment by stefankueng** [comment]
it's a regex search tool. So just use the word boundary anchors **\b**
for example, so search for "word" and only match the whole word, do a regex search for
**\bword\b**

**Comment by Netphilou31** [comment]
Hi,
Great! Thank you for the advice. I did not catch that I could use a regexp to find a whole word.
Best regards.

**Comment by Heromyth** [comment]
Maybe we really need a checkbox to indicate whether it will handle a whole word.
