### ISSUE TITLE
direxcluderegex command line parameter ignored

### ISSUE THREAD

**Issue by birbilis** [stefankueng/grepWin#283]
Doc page https://tools.stefankueng.com/grepWin_cmd.html writes:

> /direxcluderegex:"string"	sets the exclude dirs regex mask

but seems it is ignored keeping whatever the GUI was showing in that field at last search

**Comment by stefankueng** [comment]
works fine for me.
please make sure you have the latest version (2.0.8)

**Comment by birbilis** [comment]
it's been some time since then, but checking my batch file I see I have a /excludedirs:"" (not sure where that param name came from, probably some string I had found while peeking the strings in the .exe file), so probably I was using wrong param name, strange since I mention the correct one above

**Comment by stefankueng** [comment]
aha, that's the hint I needed: you're setting it to an empty string!
And currently the check if it's set via command line is to check if it's empty :(

**Comment by birbilis** [comment]
that explains it, indeed was trying to clear whatever it remembered from everyday UI use
