### ISSUE TITLE
Internet Explorer forced upon boost link in Help file

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/grepWin#284]
Why is the default web browser in my case Chrome not opened upon clicking on the boost regex link in the Help file Instead IE is opened which is an old and perhaps insecure browser Further I am forced to use IE as the link for some reason refuses to be copied for pasting into a modern browser Also Why must the Ctrl key be held down when it seems a mouse click would be sufficient Thank You - Cheerio

**Comment by artie-finkelstein** [comment]
I agree with all points raised by PaltryProgrammer
