### ISSUE TITLE
Features request: SearchMyFiles features

### ISSUE THREAD

**Issue by Pharaoh2k** [stefankueng/grepWin#29]
Really love your utility, especially for it's amazing regex search capability, one of the best implementations I have ever seen. Thank you.
I think it would be great and very useful if you add more features to it, which are available in NirSoft's SearchMyFiles (which doesn't have regex capabilities unfortunately), for example.
Features like: 
- Limit searches by File Times
- Limit searches by File Attributes
- Limit subfolders depth
- Limit searches by Text excluded dirs (not only regex option)
etc.
And the ability to see "date modified" and "encoding" also in the content window, and not only on the Files window.

Truly appreciate your work. Thank you again. :)

**Comment by stefankueng** [comment]
- Limit searches by File Times: that's already implemented. Or are you missing something else?
- Limit searches by File Attributes: not sure how that would help. You can already ignore system and hidden files. Limiting by other attributes doesn't make much sense to me. Can you provide a use case for that?
- Limit subfolders depth: is this really something you would use often? Would it be enough to just have a "no recurse" option?

**Comment by Pharaoh2k** [comment]
Hi,
I might be blind, but couldn't find any file times filtering options:
https://lh3.googleusercontent.com/-dZixHPNAoiQ/W19qW8oGDNI/AAAAAAAAKiw/TmspeuS5K8wvHuWM09NAyxbWGc5m7z5FACHMYCw/s0/grepWin_2018-07-31_02-43-14.png

Attributes can be useful when you are interested in searching for only system files, or read-only files, I have used it quite a lot, although I can't really give a specific example right now.

Limiting subfolder depth can be very useful too when you are searching inside a folder that has many subfolders and you just want to search the first 2-3 levels. No recurse is good, but not as good as being able to limit search depth.

Also, how the ability to see "date modified" and "encoding" also in the content window, and not only on the Files window?

Thanks again

**Comment by stefankueng** [comment]
Your screenshots indicate that you don't have the latest version.
https://github.com/stefankueng/grepWin/releases

**Comment by Pharaoh2k** [comment]
You are absolutely right. Don't know why I downloaded 1.7.1 from sourceforge yesterday instead of the latest one. Thanks for that too.

**Comment by stefankueng** [comment]
working on "searching only in already found files" now...
