### ISSUE TITLE
How to "Text Match" option - Multiple extensions on search and replace?

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#291]
hello. I try a search and replace, by multiple extensions. In the option "Text Match", if I put `.html` is working good.

But, if I put `*.html;*.htm;*.txt;*.php;` , trying to search and replace on multiple extensions, is not working.

**Comment by stefankueng** [comment]
you have to use `|` as the separator, not `;`
`*.html|*.htm|*.txt|*.php`

just see the tooltip :)
