### ISSUE TITLE
Better indications of invalid regex

### ISSUE THREAD

**Issue by gemal** [stefankueng/grepWin#293]
![image](https://user-images.githubusercontent.com/69105/144424052-25605250-994a-4ad6-889a-f4b7f2a279a0.png)

I entered a invalid regex but it took me forever to find out why "Search" and "Replace" buttons where disabled until I suddenly saw this very small indication. I even uninstalled and reinstalled the app...

Please make it more visual

**Comment by stefankueng** [comment]
do you have any suggestions on **how** to make it more visual?

**Comment by caironite** [comment]
Thanks for this great application!
