### ISSUE TITLE
regex issue with the filename search

### ISSUE THREAD

**Issue by alexeyrv** [stefankueng/grepWin#297]
Hello, thank you for the great tool. 
I used Regex very often and with portable grepWin have a problem.
grepWIn 2.0.9. 1098 portable
Environment: Windows 10
Goal: to find files with "pdf" extension of pdf at the end of a filename
Issue: there are unmatched files in the result
Settings: searching files, enabled regex search, all sizes, include system items
Search for string: math.*pdf
Result issues are below:
content_1000_to_1200.csv
content_1200_to_1500.csv
content_1500_to_1723 (1).csv
content_300_to_600.csv
content_940_to_1000.csv
content_600_to_900.csv
content_900_to_1200 (1).csv

No "math" or "pdf" strings are presented in the filenames.
Files with "pdf" or/and "math" strings are there.

![image](https://user-images.githubusercontent.com/3062541/146396541-8882c000-a886-4c29-9a0f-c35042bd5108.png)

With best regards, Alex

**Comment by stefankueng** [comment]
to limit the search to certain filenames, enter the search mask into the edit box at the bottom right, just above the "Search" button: See the "File Names match: use '|' to separate multiple text match patterns, prepend '-' to exclude" label?
