### ISSUE TITLE
Add shell integration

### ISSUE THREAD

**Issue by rafi-d** [stefankueng/grepWin#299]
HI,
Is it possible for you to add Windows shell integration? I mean  - be able to left-click explorer folder, and "open" grepWin from there, with this folder in the "search in" line? An option to do that will be great, or at least be able to use a run-parameter so we can make such integration manually?

Thanks

**Comment by stefankueng** [comment]
the portable version does not have shell integration because that requires adding registry entries.
but the setup version has shell integration.
