### ISSUE TITLE
Bug: Results for text files larger than 70MB don't show text strings

### ISSUE THREAD

**Issue by vertigo220** [stefankueng/grepWin#3]
When the results view is set to 'Content,' the text field is empty for all findings from text files larger than 70MB (and possibly other file types, but I only tried with text files). This applies whether searching a single file or a group of files, in which case there will be entries in the text column for any files <70MB but nothing for files >70MB.

**Comment by stefankueng** [comment]
That's done for performance reasons.
For such big files, grepWin does not parse the lines of the files but only marks the found count.
Parsing the lines is very expensive, and for such big files that's just not feasible.

**Comment by vertigo220** [comment]
Couldn't there at least be an option to show them? As great as this program is, and as fast as it is, at least compare to AstroGrep, it's just not very useful with this info omitted. And it's not like I don't have the resources for it.

**Comment by stefankueng** [comment]
increased the size for this in
https://github.com/stefankueng/sktoolslib/commit/477acb708380948d3235c46594bb99ff225be3b1

It's now one fourth of the available memory. So if you have e.g. 8GB of RAM and 4GB of RAM is still available, up to 1GB of text file sizes are considered and handled with line numbers.
