### ISSUE TITLE
first match checkbox

### ISSUE THREAD

**Issue by yalov** [stefankueng/grepWin#301]
checkbox for finding only the first match in the every file.

example:
```
Main
{
    name = main1
    value = 2
    Sub
    {
        name = sub1
    }
    // ....
}
```
search string `name = ` give `name = main1` and `name = sub1`, but I want to get only the first one.

**Comment by stefankueng** [comment]
if you only want the files that contain a search match, just switch to "files" view at the bottom right.

**Comment by yalov** [comment]
I want the first match in every file, not just files.

Example:

file1:
```
name = 11
name = 12
```

file2:
```
name = 21
name = 22
```

In the result table, I want to have one column like that
```
name = 11
name = 21
```
