### ISSUE TITLE
No taskbar icon when opening via Windows 11's context menu

### ISSUE THREAD

**Issue by XenoPanther** [stefankueng/grepWin#303]
As seen in the image, whenever I use Windows 11's new context menu to search with grepWin, no icon is shown in the taskbar. But when I use the legacy context menu, the icon does appear. 

<img width="781" alt="image" src="https://user-images.githubusercontent.com/81916167/152698539-130308bf-f2a6-4eec-beea-693effe0e3e2.png">

**Comment by stefankueng** [comment]
I've noticed this too, but only on my machine that's on the beta channel of the Windows-insider program.
On official releases I get the icon.
Are you on an insider channel as well?

**Comment by XenoPanther** [comment]
I am, currently using the latest Dev build (22543)
