### ISSUE TITLE
Clear values in "Limit search" block when starting grepWin

### ISSUE THREAD

**Issue by MeekMark** [stefankueng/grepWin#305]
There should be an option to always clear the file size and file dates criteria when starting grepWin.  I occasionally need to set the file size or file date criteria, and usually forget to clear them when I start grepWin a few days later.  I then wonder "Where's the files?  I know the files are there! "  Then, .... I notice... I had a date or size set!

**Comment by stefankueng** [comment]
but how to decide which settings to re-use and which ones not?
Can't really make a 'remember setting' option for every possible setting - that would get a very overloaded UI

**Comment by MeekMark** [comment]
Good point; I seldom/ever use other options in that pane/region.... so I don't even know the behavior of the other settings in regards to them retaining values from prior sessions.
