### ISSUE TITLE
Execute not working via command line

### ISSUE THREAD

**Issue by SubJunk** [stefankueng/grepWin#31]
The following command prepopulates the fields in the GUI when it opens, but isn't performing the actual search:

```
grepWin /searchpath:"Code/pom.xml" /searchfor:"<version>(\d\.\d\.\d-SNAPSHOT)</version>" /replacewith:"<version>1.0</version>" \execute \executereplace \closedialog
```

Is this a known bug in 1.8.1 or am I doing it wrong? I have been using this page as a reference: https://tools.stefankueng.com/grepWin_cmd.html

**Comment by stefankueng** [comment]
you have to use '/' for _executereplace_ and _closedialog_:
`/execute /executereplace /closedialog`

but instead, you've used a backslash.
