### ISSUE TITLE
Replace not working latest build 2.0.10 windows 11

### ISSUE THREAD

**Issue by matteius** [stefankueng/grepWin#311]
I've used this tool for years, really rely on it.  For some reason the replace functionality is just performing a search now when I go to use it on my new computer.  Windows 11 latest build 2.0.10 have tried both x64 and non.

**Comment by stefankueng** [comment]
work fine for me. Are you sure the text is not replaced in the files?

**Comment by matteius** [comment]
I am sure it didn't work the other day when I opened the issue, but I had some other weird behavior too because I added a registry key to make the taskbar behave like windows 10, but it caused some issues including I think this bug report.  I tired it again since deleting that registry key and things have been working since.  Thanks!
