### ISSUE TITLE
A new feature GrepWin: perform multiple search and replace REGEX operations at once 

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#313]
I find this LINK on notepad++ forum. It represents a great idea (and have also a solution in python) that can help GrepWin to improve itself with  a new feature: to perform multiple search and replace REGEX operations at once. This is extremely important for those who work with regex.

https://community.notepad-plus-plus.org/topic/22601/are-there-any-plugins-or-ways-to-perform-multiple-search-and-replace-regex-operations-at-once/2

```
# -*- coding: utf-8 -*-
from __future__ import print_function

from Npp import *

#-------------------------------------------------------------------------------

class T22601(object):

    def __init__(self):
        regex_find_repl_dict_list = [
            { 'find' : r'foo', 'replace' : r'bar' },
            { 'find' : r'fu', 'replace' : r'bark' },
        ]
        editor.beginUndoAction()
        for d in regex_find_repl_dict_list: editor.rereplace(d['find'], d['replace'])
        editor.endUndoAction()

#-------------------------------------------------------------------------------

if __name__ == '__main__': T22601()
```

**Comment by stefankueng** [comment]
sorry, but I won't include python into grepWin.

**Comment by me-suzy** [comment]
yes, you don't have to include Python. You just need to be inspired by it. 

For example. You can make a new form, just like it looks now GrepWin.  Except, you have to add a BUTTON named "new replacement" ( or something like that ).

For each button press, two new imput lines will appear: A FIND line and a REPLACE line. The user will add the formula in the both FIND/REPLACE lines . 

After several new FIND/REPLACE, then GrepWin will store data into a text files (Just like it is now "Presents' button ).

**That's very easy for you to do.** And it is the most important feauture. I always have to make 6-7 replacements each time in regex. It will be easier if I will run all , just once. 

GrepWin is very good, but must be improved with many other features.
