### ISSUE TITLE
Can you add the feature of limiting the search in certain lines only of the files?

### ISSUE THREAD

**Issue by khaldi-yass** [stefankueng/grepWin#314]
Sometimes when we search for a word in we want to look for that word in certain lines only, this is mostly encountered in structured files such as XMLs.

For example here is a use case: We have an XML file that contains multiple documents with `<id></id>` tags, we would like to find a document with id 1234 but only if it's for document A (ie: In line 15), so we would be searching for `<id>1234</id>`, but now when we don't specify the line the results will also show files where document B (ie: line 55) has an id of 1234.

Hope I managed to clear the use case, thank you.

**Comment by stefankueng** [comment]
just use a proper regex to include the document name. Something like
<document id=\"A\".*?<id>1234</id>.*?</document>
