### ISSUE TITLE
Replacement Text Case Conversion limited to [a-zA-Z] ??

### ISSUE THREAD

**Issue by KaDeeKe** [stefankueng/grepWin#318]
Replacement Text Case Conversion placeholders (\L, \l, \U, \u, etc), as listed in GrepWin's F1, suggest they can convert ANY lowercase character to uppercase and vice versa.   
This works fine on my GrepWin 2.0.10.1125 on W10 for the characters in the range [a-zA-Z], 
but it does not seem to apply in my environment to some characters used Scandinavian, French, Italian, Spanish ... languages.
Examples:    ö  versus Ö;   ç versus Ç;  ù versus Ù; ñ versus Ñ; etc., ...
I'm testing on a .srt-file with UTF8-encoding according to GrepWin.   "Treat files as UTF8" makes no difference.
From the paragraph "Boost’s Replacement String Case Conversion" in https://www.regular-expressions.info/replacecase.html the example «So when (?i)(helló) (wórld) matches HeLlÓ WóRlD you can use \L\u\1 \u\2 to replace the match with Helló Wórld.» suggests that it is not a limitation of the Boost Engine.
Is my assessment correct that GrepWin cannot case-convert such characters and should its F1 be more modest :)?
Or can I do something to circumvent this limitation?

**Comment by stefankueng** [comment]
can you provide a sample file and your exact search and replacement string?

**Comment by KaDeeKe** [comment]
Hi Stefan,

 

 

Small sample test-file:  Bron.0.srt

1

00:16:41,080 --> 00:16:45,920

Politie MALMö, Saga Norén.

 

2

00:19:07,320 --> 00:19:12,240

Het is van Ölanders Livs in MALMö.

 

For sake of testing, Id like to turn «Malmö» into All Capital Case.

 

Search for «\b(Malmö)\b»

Replace with «\U$1\E»

 

My result in Bron.1.srt

1

00:16:41,080 --> 00:16:45,920

Politie MALMö, Saga Norén.

 

2

00:19:07,320 --> 00:19:12,240

Het is van Ölanders Livs in MALMö.

 

I had hoped for MALMÖ iso MALMö ...

 

Treat files as UTF8 makes no difference.

 

My W10 Language settings:



 

 

Kind regards,

Kurt
