### ISSUE TITLE
Search for multiple lines fails

### ISSUE THREAD

**Issue by colinsutton** [stefankueng/grepWin#321]
When I search for either of two consecutive lines of text in my file, the search is successful.
If I copy and paste the two lines into the 'click to enter the text as a multiline text' box, the 'Search for' box shows the texts separated by \r\n but grepwin does not find those lines in my file.
Using notepad++ I can see that the file has the line separator only \n 
Notepad++ can find the two lines if I search for line1\nline2
When I change the search text in the grepwin 'search for' box to use only \n it still does not find those lines.

**Comment by stefankueng** [comment]
please try to replace the '\r\n' that's automatically inserted with '(?:\\n|\\r\\n|\\n\\r)'

**Comment by colinsutton** [comment]
That worked. Looking forward to the next release!
