### ISSUE TITLE
r-clicking a file in the search results causes the entire window to redraw.

### ISSUE THREAD

**Issue by KutanaDev** [stefankueng/grepWin#322]
grepWin is great - I use it a lot.

But when I use the context menu to open a file in a text editor, the r-click makes the entire window - all the controls and everything - redraw. The app main window briefly goes blank before all the controls reappear.

**Comment by stefankueng** [comment]
tried on two machines - I can not reproduce that.
Maybe you have some helper tool installed that causes this?

**Comment by KutanaDev** [comment]
Many thanks for the steer - I think it's the Windows Explorer shell extension item that our product adds to the r-click context menu that causes the behaviour I saw. When I uninstalled the addin the problem went away. Now I have to work out how to fix our code…
