### ISSUE TITLE
Make Find/Replace only in some files from some folders

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#323]
hello. I have 3 folders with to type of files (that have different content)

```
Folder_A
    Files_TYPE_X
    Files_TYPE_Y
Folder_B
    Files_TYPE_X
    Files_TYPE_Y
Folder_C
    Files_TYPE_X
    Files_TYPE_Y
```

I want to change only  **Files_TYPE_X** from all folders. 

How can I do this with GrepWIn ?

**Is there no "Exclude Files" option?** or **"Include only the files" option?**

**Comment by stefankueng** [comment]
there's a "File names match" box at the bottom right. Enter `*.filetype` there.

**Comment by me-suzy** [comment]
doesn't work. I put `*.webinar` as to FIND/REPLACE in all files that contain the word webinar, and doesn't work. Nothing if find...

See this print screen

![image](https://user-images.githubusercontent.com/2770489/167278833-0f099f98-7950-4b7b-970e-e7d166f07ff0.png)
