### ISSUE TITLE
"Limit search" -> "Include ..." check boxes get unchecked when using presets

### ISSUE THREAD

**Issue by dinkumoil** [stefankueng/grepWin#324]
## Description

When selecting a preset which is a regular expression in _Presets_ dialog and closing it with _OK_ button or after double-clicking a preset in this dialog, in group box _Limit search_ all check boxes _Include ..._ get unchecked.

## Steps to Reproduce

1. Create a preset which is a regular expression and save it using button _Add to Presets_.
2. Set input focus to _Search for_ edit control and input some character, for example an _a_.
3. In group box _Limit search_ check all options _Include ..._.

![grafik](https://user-images.githubusercontent.com/24699812/175274433-c5701a74-d7fd-4f86-b75a-120a9d035c5c.png)

4. Click _Presets_ button to open related dialog.
5. a) Select a preset and click _OK_ button or
    b) Double-click a preset.
6. Observe check boxes _Include ..._, their states have been changed to _unchecked_.

![grafik](https://user-images.githubusercontent.com/24699812/175274625-31860ff7-85aa-4bfb-8f52-3fee8fbce04f.png)

## Applies to

_grepWin_ version 2.0.10.1125

**Comment by stefankueng** [comment]
the presets include the checkbox states. So if you create a preset with those unchecked, then when you select that preset the state of the checkboxes changes back.
That's so intended.
