### ISSUE TITLE
Search results not sorted

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#325]
If you sort by Ascending name (A-Z) the results is ok, but when you do a **search again** the resulting files won't be sorted (A-Z).
Basically you have to resort the column order manually after every search.

**Comment by stefankueng** [comment]
that's by design: that way every new search is sorted in the order the filesystem stores it's data

**Comment by Hexaae** [comment]
But the filebar still says it's sorted by -your last choice-. Should be reset to look coherent at least.
