### ISSUE TITLE
Replacing char with hexadecimal value representing another char

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#328]
For example "Finché", wanted to change "é" -> hexadecimal char 0080 (€).
Doesn't seem to work from reg. exp. helper:
![image](https://user-images.githubusercontent.com/8591462/179101361-44422f6d-546c-49d0-8373-44673ce8c12d.png)
Expected results: Finch€
What am I doing wrong?

**Comment by stefankueng** [comment]
`\x80` is a utf8 control char, you have to use `\xE8`

**Comment by Hexaae** [comment]
Uhm, and there is no way to replace that char/byte with the exact byte 0x80 even if "not printable" in this case? Of course I can use an hex-editor but your excellent grepWin was so handy and faaast in mass editing.

**Comment by stefankueng** [comment]
well, if you use `\x80` then the found string is replaced with that. But of course as you said it's not printable/visible

**Comment by Hexaae** [comment]
The problem is it won't be replaced with $80 but I find some $00 if I open the converted docs with an hex-editor, that's why I opened the thread. $80 with the hex-editor = char "€", but from grepWin I get $00...

EDIT: SOLVED!
Enabling "Treat files as binary" it does exactly what I wanted replacing the given char with $80 👍🏻
![image](https://user-images.githubusercontent.com/8591462/179285834-4b8bbec1-6122-4b21-bc7b-eee2121ce45f.png)
