### ISSUE TITLE
Problems installing latest (2.0.10)

### ISSUE THREAD

**Issue by gregerlhd** [stefankueng/grepWin#329]
I'm on Win11 Home Insider 25158. 
When trying to install 2.0.10 (or  2.0.9, for that matter) I get an error message that Installer service could not be accessed.
So I tried another msi, for PowerShell, and it worked. 
Slightly unhappy (sort of like trying using Explorer find...) screenshot attached!

![2022-07-16](https://user-images.githubusercontent.com/8778214/179355985-bcff38b1-a948-4026-ac59-9nam,elyde3707cf8b8.png)

**Comment by stefankueng** [comment]
move the msi to a folder where the user SYSTEM has access and install from there.

**Comment by gregerlhd** [comment]
I moved it to C:Windows

Same result.

 

Från: Stefan Küng ***@***.***> 
Skickat: den 16 juli 2022 15:33
Till: stefankueng/grepWin ***@***.***>
Kopia: gregerlhd ***@***.***>; Author ***@***.***>
Ämne: Re: [stefankueng/grepWin] Problems installing latest (2.0.10) (Issue #329)

 

move the msi to a folder where the user SYSTEM has access and install from there.

**Comment by stefankueng** [comment]
not sure how you set up your OS, but C:\Windows is maybe the worst place to move an msi.
Try your download folder or your documents folder.

**Comment by gregerlhd** [comment]
The failed install I reported was from Download. However, Download is included in OneDrive, as is parts of Documents. But why does other msi work fine out of Download?

 

Från: Stefan Küng ***@***.***> 
Skickat: den 17 juli 2022 11:39
Till: stefankueng/grepWin ***@***.***>
Kopia: gregerlhd ***@***.***>; Author ***@***.***>
Ämne: Re: [stefankueng/grepWin] Problems installing latest (2.0.10) (Issue #329)

 

not sure how you set up your OS, but C:\Windows is maybe the worst place to move an msi.
Try your download folder or your documents folder.

**Comment by gregerlhd** [comment]
I did! Skickat från min Huawei-surfplatta-------- Ursprungligt meddelande --------Ämne: Re: [stefankueng/grepWin] Problems installing latest (2.0.10) (Issue #329)Från: Stefan Küng Till: stefankueng/grepWin Kopia: gregerlhd ,Author 
not sure how you set up your OS, but C:\Windows is maybe the worst place to move an msi.
Try your download folder or your documents folder.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/stefankueng/grepWin/issues/329#issuecomment-1186460455",
"url": "https://github.com/stefankueng/grepWin/issues/329#issuecomment-1186460455",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
