### ISSUE TITLE
notepad2 error when opening a file with line number

### ISSUE THREAD

**Issue by dcoder42** [stefankueng/grepWin#33]
When double clicking on one of the files in the search result to open it up in the editor and Notepad2-mod is installed i am getting an error that file "/g 123" can not be opened. That's because the line parameter /g must be set before the file name.

Simply replacing linenumberparam with linenumberparam_before fixes this for me.
https://github.com/stefankueng/grepWin/blob/bbb9ff770ad26a3875b08190cfe6049adf1e38dc/src/SearchDlg.cpp#L1903

**Comment by dcoder42** [comment]
With notepad2 you can not only jump to the correct line, you can also specifiy the text to be highlighted

`linenumberparam_before = CStringUtils::Format(L"/g %s /m \"%s\"", textlinebuf, m_searchString.c_str());`

**Comment by stefankueng** [comment]
done in acb430462e84e5dbec4401b42ea288658cb87403

**Comment by dcoder42** [comment]
The "/mr" switch that you checked in is causing issues if you do a simple text search. For example searching for ['LD_FLAGS'] will not highlight the text. Changing the code to the following fixes this

	auto escapedsearch = m_searchString;
	SearchReplace(escapedsearch, L"\"", L"\\\"");
	std::wstring searchParam = L"/m";
	if (IsDlgButtonChecked(*this, IDC_REGEXRADIO) == BST_CHECKED)
		searchParam = L"/mr";
	linenumberparam_before = CStringUtils::Format(L"/g %s %s \"%s\"", textlinebuf, searchParam.c_str(), escapedsearch.c_str());
