### ISSUE TITLE
Double-clicking filename in search results opens new application instance

### ISSUE THREAD

**Issue by garkbit42** [stefankueng/grepWin#330]
I've just installed grepWin (v 2.0.10.1125) on a new laptop (Windows 10) and its behaviour differs from how it used to work for me on my old laptop. I appreciate this is probably a _windows_ setting rather than grepWin but hoping someone can help?

If I double-click on a .sql filename in the search results - it opens a new instance of SQL Server Management Studio however
if I double-click on a .sql filename from windows explorer then the query file opens in my existing SSMS instance.

The workaround would be to "Open File Location" first and then double-click the file from there to open it in the already running version of SSMS, but am wondering if there is a simple setting somewhere to force it to reuse the existing app rather than try to open a new one every time.

**Comment by stefankueng** [comment]
there are actually different apps defined for different actions. Usually a double click in explorer executes the "open" action, so the app associated with that action is executed.
Opening a file from grepWin however means the application that's associated with the "default" action is used, which is not necessarily the same as the app for the "open" action.
You could use the registry editor (`regedit.exe`) and check the commands under `HKEY_CLASSES_ROOT\SystemFileAssociations\ `and change the app there, or simply use "open with" from the explorer command and select your preferred application there, check the box "always open files with this application" and be done.

**Comment by garkbit42** [comment]
Thanks - the "open with" option works.

HKEY_CLASSES_ROOT\SystemFileAssociations\.sql is not defined (neither on my new laptop - nor on my old one).
HKEY_CLASSES_ROOT\.sql has the same setting on both laptops - ssms.sql.15.0

It's not that double-clicking fails to open the file in the correct application - just that on my new laptop it opens a new instance of SSMS every time whereas on my old one it opened a new query window within the existing (already open) application.

As I said in my original post - I don't think this is an issue with grepWin - so I will close this issue, as at least I have a better workaround now - by using "open with"

**Comment by mni-lifa** [comment]
I don't think it is a windows setting issue.
if i click open containing folder and then double-click the file or right-click + Open it opens in existing instance, so the windows setting does the right thing.
