### ISSUE TITLE
Feature request: add a setting to hide or disable the "Replace" button

### ISSUE THREAD

**Issue by agiudiceandrea** [stefankueng/grepWin#332]
Previously already requested with https://github.com/stefankueng/grepWin/issues/235, which was closed by @stefankueng with the reason that:

> the replace button is only active if there's text in the "replace with" edit box

Anyway, on Windows 7 Home SP1 64 bit, with grepWin 2.0.10.1125 (and previous versions), the Replace button is active and clickable also when there is no text in the "Replace with".

![image](https://user-images.githubusercontent.com/16253859/181231884-bb1feaff-e838-4767-ace5-4e5281896b0d.png)

It would be great if the "Replace" button could be hided or disabled or if a warning dialog would pop up every time (not only when the backups are disabled) the  "Replace" button is pressed.

**Comment by stefankueng** [comment]
I'll just make it so a warning is always shown if the replace string is empty.

**Comment by mdnava** [comment]
Hello..

I just tried 2.0.11 and I was able to replace text from a file with no warning, and the "replace with" input box was empty.
Is there an option or setting I should enable ??

I'm up for this feature if there's no text in in the "Replace with" input box..
I once before made the mistake of clicking "Replace" instead of "Search" and made a mess.

Best regards!

**Comment by stefankueng** [comment]
the warning only shows if you don't have backups enabled

**Comment by mdnava** [comment]
Ok, I had enabled: Don't warn when replacing without creating backups.

**Comment by GongKiro** [comment]
hello，I download the source and compile it ，but vs2019 tell me can not found SimpleIni.h， how can I get the file？

**Comment by stefankueng** [comment]
@GongKiro first, use vs2022. Second: you have to clone the repo recursively to get the submodule where simpleini.h is in. Or since you've already cloned it, run
`git submodule update --init`
