### ISSUE TITLE
The problem of replacing a single-line string with a multi-line one

### ISSUE THREAD

**Issue by dasu88** [stefankueng/grepWin#335]
When I search for a single line string and replace it with a multi-line string, but I can only get the single line string with '\r\n', how do I get the correct multi-line replacement?
For example, the result in the picture is "123\r\n456"
![2022-09-14_104450](https://user-images.githubusercontent.com/23251263/190047226-557f0e0c-806f-4d75-82c7-84ce1ca57b5e.jpg)

**Comment by stefankueng** [comment]
works fine for me with this file content:
```
abc
123abc
def
456
```

gets replaced with
```
abc
123
456abc
def
456
```

**Comment by dasu88** [comment]
> works fine for me with this file content:
> 
> ```
> abc
> 123abc
> def
> 456
> ```
> 
> gets replaced with
> 
> ```
> abc
> 123
> 456abc
> def
> 456
> ```

It seems to work only under Regex Search, but will be replaced by a single line string in Text search.
