### ISSUE TITLE
Backslash is dropped from the replacing text

### ISSUE THREAD

**Issue by 001Guy001** [stefankueng/grepWin#338]
For example, when replacing `word` with `(?<!\ba )word` the `\` is dropped and the updated text becomes `(?<!ba )word`

Notes:

- This is when using "Text search"
- It's been working correctly in version 2.0.10.1125

**Comment by stefankueng** [comment]
that's by design: for the replace text you `must `escape the backslash. Otherwise you couldn't add a replace text that contains newlines.

**Comment by CADbloke** [comment]
just a comment, I found this when I had the same problem. For me, I expected a text search to behave like text, not a regex. But yeah, I get the adding newlines thing. It's not unrecoverable so not a trainwreck.
