### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by ghost** [stefankueng/grepWin#339]
I don't know what I'm doing wrong. When I searched on time, it found lots of files, but it didn't find "time" in this excel spreadsheet. What do I need to fix?

![image](https://user-images.githubusercontent.com/115202981/194462412-26fef9c4-34b4-4038-a5ab-52edd2f67f2b.png)

**Comment by stefankueng** [comment]
excel files are zip compressed, they're not plain text files.
