### ISSUE TITLE
Search Results - display line containing search string

### ISSUE THREAD

**Issue by clawhammer99999** [stefankueng/grepWin#34]
Hi Support,
I am a new user of GrepWin.
The first search I ran, for each file, the Search Results **displayed the line containing the text string** for which I was searching – Perfect!!
However, all searches thereafter failed to display the line - don’t know why the change. Don’t see anything in the options that would control display of the text line.
Being able to view that text line is critical to my needs. How can I get GrepWin to again display the text lines?
Help me, Obi Wan. You’re my only hope!

**Comment by stefankueng** [comment]
At the bottom right of the dialog, there are two radio buttons "Files" and "Content". You want "Content".

**Comment by clawhammer99999** [comment]
Wonderful!  Thanks a Big Bunch!  (I will get my glasses upgraded 😊)
