### ISSUE TITLE
path changed for images on Wiki

### ISSUE THREAD

**Issue by tfox58** [stefankueng/grepWin#341]
No an issue with the program but rather the wiki page "Integrating grepWin into Visual Studio."

Looks like the two screenshots have been moved.  Path was
/stefankueng/grepWin/**raw/master**/src/Resources/vs9-tools-grepwin-prj.png
/stefankueng/grepWin/**raw/master**/src/Resources/vs9-tools-grepwin-sln.png

Now, they are
/stefankueng/grepWin/**blob/main**/src/Resources/vs9-tools-grepwin-prj.png
/stefankueng/grepWin/**blob/main**/src/Resources/vs9-tools-grepwin-sln.png

**Comment by stefankueng** [comment]
fixed
