### ISSUE TITLE
grepWin-2.0.11-x64.msi installer depends on grepWin-2.0.10-x64.msi

### ISSUE THREAD

**Issue by cowwoc** [stefankueng/grepWin#342]
The new installer is broken. If you try upgrading from the previous version, you will get the following error:

![image](https://user-images.githubusercontent.com/633348/197405810-ded9cafa-60b6-4f74-8345-6503810a4e02.png)

**Comment by stefankueng** [comment]
I assume you have the msi on a network share and you try to install from there? That won't work.
Copy the msi e.g. to your desktop and install from there.

**Comment by cowwoc** [comment]
@stefankueng I'm not running on a network share. This is the error I get when running from my desktop folder. Did you notice the incorrect dependency in the error message?

The `2.0.11-x64` binary depends on version `2.0.10-x64` (the previous version). That by itself sounds like a bug...

**Comment by stefankueng** [comment]
no, that's not a bug. That's how all msi's work when upgrading to a newer version: the old msi is used to uninstall the previous version.
Windows keeps the 'old' msi file exactly for that. I assume you've used one of those "optimizing" tools that promise to free "unused" files. Don't do that!

**Comment by cowwoc** [comment]
@stefankueng I didn't use any optimizing tools. I can see now that I cannot uninstall the old version unless I re-download its installer. Meaning, I get the above error message if I do.

Shouldn't users be able to uninstall the software without needing to keep the original installer around? I don't remember running into this problem in past versions of this software, or other software for that matter.

**Comment by stefankueng** [comment]
Yes, users should be able to uninstall the SW without keeping the old installer. As I said: Windows does this automatically.
Even if you don't use such tools, *something* deleted that msi file Windows keeps around.
