### ISSUE TITLE
All files matching pattern show as Encoding "BINARY" in version 2.0.11.1154

### ISSUE THREAD

**Issue by MeekMark** [stefankueng/grepWin#349]
It seems like since I upgraded to grepWin version 2.0.11.1154, when I search all the files that match show up as BINARY encoding, which doesn't bother me too much, unless I want to see the text of the matched lines, and of course if I select the "Content" radio button at the bottom, it doesn't show the "binary" content.

It worked fine a while ago; I checked the settings, and I tried increasing the "number of NULL bytes to 100 to no avail.  These are text files.
![greWin-BINARY](https://user-images.githubusercontent.com/1624754/207987484-33356e3e-a651-4e27-9883-54a1a9570204.png)

**Comment by stefankueng** [comment]
uncheck the box "treat files as binary" (top right, below the "replace with" edit box.

**Comment by MeekMark** [comment]
Ugh!  I figured it was something stupid!  Sorry for the trouble.
