### ISSUE TITLE
skipping folders shortcuts

### ISSUE THREAD

**Issue by emadmahdi** [stefankueng/grepWin#350]
Hi,

I have problem using your tool "grepWin" .. I need to know how to instruct "grepWin" to  "NOT  FOLLOW " folders shortcuts (folders symbolic links)

Please check the attached photo .. the folder "test" exists only once in my harddrive .. while "grepWin" keeps finding the same folder again and again and again .. which cause the search to never finish.

To reproduce the problem .. you can execute the below commands .. then use "grepWin" to search for the folder "test" (same in attached photo)

====================
cd /d c:\\
mkdir emad
cd emad
mkdir test
cd test
mklink /d mahdi c:\emad
====================

![image](https://user-images.githubusercontent.com/7454511/208032829-f58ecb68-c7f8-460b-83dd-ae148fa61167.png)

**Comment by stefankueng** [comment]
You've created a recursive link. So of course grepWin recurses too when searching.

**Comment by emadmahdi** [comment]
Microsoft Windows does not agree with you .. their "windows explorer search" does not open or follow any symbolic links .. check the attached photo !!

Plus i did not create these symbolic links in my Windows installation folders .. I sent you the commands so you can reproduce this bug not to tell me that i created these symbolic links !!

![image](https://user-images.githubusercontent.com/7454511/208179996-fd4f36ad-056c-4452-b62e-39e019d1bf51.png)

.

**Comment by emadmahdi** [comment]
Plus it does not make any sense to search inside a symbolic link

Example:
The Folder "C:\Program Files\My App" have inside it a link to "C:\Windows" .. then when i use your "grepWin" to find files inside "C:\Program Files" .. "grepWin" will extend the search to include results from "C:\Windows" which does not make any sense because i need results only from "C:\Program Files" not from the whole harddrive

**Comment by stefankueng** [comment]
Well,  whether it makes sense to search symbolic links will come up again, I'm absolutely sure of that. Because if I would simply change grepWin to ignore those, it will not take long before users complain about that.

**Comment by emadmahdi** [comment]
Then simply add a check box in settings to ignore or not ignore symbolic links .. Plus "Windows Explorer" does ignore all symbolic links .. so ignoring symbolic links is the "Standard" not the opposite !!

**Comment by stefankueng** [comment]
I just did: https://github.com/stefankueng/grepWin/commit/de30ae3da8cbd8de50c1a0c3120a7f1224e17ece

**Comment by emadmahdi** [comment]
one more point .. your "grepWin" will be faster if the symbolic links are ignored .. because most people does not know they are searching extra folders untill they trapped in a recursive symbolic links .. then they will stop using "grepWin"

Thank you for this great tool .. it is so good .. simple .. fast .. full featured .. I add it to my "Windows Explorer" context menu and i always use it.

**Comment by emadmahdi** [comment]
It will be also nice and very useful if you can add search for symbolic links .. whether it is a shortcut to a file or a link to a folder.

**Comment by emadmahdi** [comment]
it is also very useful is you can add a search for "files" or "folders" .. right now "grepWin" search for both at the same time ., but i use a trick to force "grepWin" to search for only folders by specifying the size of the files to be "equal to Zero" !!

**Comment by emadmahdi** [comment]
If you are going to add search object type .. then i suggest you add it as check box in settings .. that will allow "grepWin" to search for more than one object type at the same time .. such as "folder" and "file" .. or "folder" and "symbolic link" .. or "file" and "shortcut" .. or "all" at the same time

**Comment by Coldblackice** [comment]
> I just did: [de30ae3](https://github.com/stefankueng/grepWin/commit/de30ae3da8cbd8de50c1a0c3120a7f1224e17ece)

Props for that. Props also for maturity in not reacting to an aggressive request (unlike how I would have responded 😃)!
