### ISSUE TITLE
copy column content

### ISSUE THREAD

**Issue by mrx23dot** [stefankueng/grepWin#359]
Right click on column could copy finding column text, 
![2023-01-09_213652_Wu](https://user-images.githubusercontent.com/4163396/211413203-6e9b8ebb-f662-45a0-9eb7-484a616d3007.jpg)

saving time by not copying everything by hand with ctrl+A and trying to extract columns manually.

**Comment by mrx23dot** [comment]
thank you, works great!

**Comment by kaifuzi** [comment]
@stefankueng Thanks for this enhancemnet! There is smale issue, when there is seach item is selected, and after I click "Copy whole column", the context menu will also be popup of selected item, I think this is not necessary, could you please inprove this?
