### ISSUE TITLE
Feature Question: Display RegEx Capturing Group Results

### ISSUE THREAD

**Issue by fhaag** [stefankueng/grepWin#36]
grepWin is great for finding files by regexing their content, and I like the results display very much.

Sometimes, I do, however, wish for getting an enhanced results table, where I cannot only see the line that matched my search expression, but where I get one additional column for each capturing group in the regular expression.

I *think* this feature is not yet included (?)

(I looked at the sources, but unfortunately, my current development ecosystem is not quite set up for C++. Maybe I'll return to this later.)

**Comment by yowl** [comment]
+1 for this.  I notice that groups seems a bit buggy.  e.g. `(?:<TargetFrameworks>.*)(uap10.0)(?:[;<])` is valid but ignores the non capturing groups when using the replace.  In the Test Regex window it works but you have to escapte the round brackets

**Comment by stefankueng** [comment]
Since #171 is now done, I'm closing this one. #171 I think should cover this as well, maybe not exactly but close enough.
if you think it does not, feel free to reopen this issue (but then add more info about what exactly is still missing)
