### ISSUE TITLE
Window resize

### ISSUE THREAD

**Issue by crag2012** [stefankueng/grepWin#360]
Problem accessing top and bottom bars.
When grepWin is loaded it always puts top and bottom out of visible range such as close max and min is not visible it is above the window and the bottom bar. Size selection does not work

**Comment by stefankueng** [comment]
if both top and bottom are out of the monitor range, then the whole window is too big for your monitor?
What resolution and dpi do you use?

**Comment by stefankueng** [comment]
also, the size and position of the window is stored between sessions. So if you position the window once correctly, it will remember that and use the same size/position the next time.

**Comment by crag2012** [comment]
resolution  1920x1080
Since HP graphic update alls fine. Intel drivers not so good, so stick to HP updates and not Intel.
Solved
