### ISSUE TITLE
Grepwin doesn't find search text if files are read only

### ISSUE THREAD

**Issue by kjsmithtx** [stefankueng/grepWin#362]
Grepwin 2.0.12 fails to find text in a file if that file is read only.  I don't recall this being prior behavior nor do I think it should be current behavior.

**Comment by stefankueng** [comment]
did it show an error when reading the file?

**Comment by kjsmithtx** [comment]
no error, interesting thing is that the number of files changes if the read only property is toggled.  So in the simplex case of only selecting a single file, when that file is read only the number of files searched is 0, but read only off it is 1 and correspondingly if a folder is selected (which is my usual use case) then the number of files searched changes based the number of read only files in the folder structure.

**Comment by kjsmithtx** [comment]
Just uninstalled 2.0.12 and installed 2.0.11 and 2.0.11 finds values in read only files

**Comment by stefankueng** [comment]
check the option "include symbolic links". If that option is unchecked, readonly files are also excluded :(
