### ISSUE TITLE
Install of new version fails

### ISSUE THREAD

**Issue by plao** [stefankueng/grepWin#365]
The install of the new version 2.0.13 seems to failing. A repair operation was also tried, but no glue

<img width="384" alt="explorer_xA0b52s5bX" src="https://user-images.githubusercontent.com/880930/213735393-1a53708c-6268-4253-a8bd-cfb4aca97588.png">

Thanks for this wonderful sw!

BR,
Giando

**Comment by stefankueng** [comment]
try an uninstall, then reboot, them try installing again

**Comment by plao** [comment]
Hi Stefan,

ok, alles klar, ich geb Bescheid!

Vielen Dank und VG,
Giando

**Comment by plao** [comment]
Hat geklappt, danke!

VG,
Giando
