### ISSUE TITLE
Unwanted network connection

### ISSUE THREAD

**Issue by mrx23dot** [stefankueng/grepWin#366]
After starting 2.0.13 my firewall complains that grepwin wants to talk on the internet,

even though 'check for updates' is disabled.

**Comment by stefankueng** [comment]
Does this happen during installation or after when you start grepWin?

**Comment by stefankueng** [comment]
and does your firewall show to which address it want's to talk to?

**Comment by mrx23dot** [comment]
after already installed:

![2023-01-20_223132_gR](https://user-images.githubusercontent.com/4163396/213817041-f5595356-80e9-434b-9c1c-32e620147ce5.jpg)

185.199.109.133: ISP: GitHub Inc. US

and it's halts and exits (but not always) if I don't let it talk, wasn't the case in earlier versions.

**Comment by stefankueng** [comment]
that's strange. The update check thread isn't even started if the option is disabled. And that's the only place in the grepWin code that establishes a network connection.

https://github.com/stefankueng/grepWin/blob/3d3acc612756adc8a48ee8523ddf4d94de6756b6/src/SearchDlg.cpp#L639-L648

**Comment by stefankueng** [comment]
can you check again if the option to check for updates is really disabled? Maybe the setting got lost during the update?

**Comment by mrx23dot** [comment]
Interesting, it still tries to connect first time I start grepwin.exe after reboot.
![2023-01-23_205812_3U](https://user-images.githubusercontent.com/4163396/214148666-0e47487d-6926-4e08-8e8d-49a685c178f7.jpg)

update was never enabled:
![2023-01-23_205845_ri](https://user-images.githubusercontent.com/4163396/214148731-8b52b023-8e33-43f1-b6ca-322819e8316f.jpg)

I don't see any 'github' relevant code in the repo, so maybe one of the libs/DLL? 
Also I can't find 'github' in exe if I open it in a hex editor.

**Comment by stefankueng** [comment]
I think I found the problem.
You have to first check the option in the settings dialog, close grepWin, then open the settings dialog again and uncheck it.
The problem is that the default is shown as "do not check" even though the default is "do check" everywhere else.

**Comment by mrx23dot** [comment]
Nice one, it works, as long it auto fixes it for everyone else in the next release it should be fine.
Thanks!
