### ISSUE TITLE
A complex search & replace pattern...

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#368]
This is the case: https://stackoverflow.com/questions/75212474/keep-only-a-few-specific-lines-inside-some-text-files-using-regex-for-mass-text 

Wanted to modify all my MAME\ini\ files (simple text *.ini files) keeping inside only the lines:

```
#  
# OSD PER-WINDOW VIDEO OPTIONS  
#  
aspect0          xx:xx
```
where xx:xx can be 4:3, 17:10 or anything else (any specified screen ratio)... The spaces between aspect0 and xx may vary.
Everything else (= all other lines) should be removed and only those lines (if present) should remain. If those lines were not present, an empty file left will be fine (i.e. remove all non matching lines).

BTW: isn't there a special replacement placeholder to say grepWin to "remove this char/line"? Maybe my current partial solution (leaving replacement string empty) is wrong... because it will leave many < C R > instead of removing the whole lines...

**Comment by stefankueng** [comment]
I'm sorry, but I can't provide help with specific regex replace patterns.
That would open a can of worms...

**Comment by Hexaae** [comment]
What about the request for replacement placeholder for "remove char/line"?

**Comment by stefankueng** [comment]
That's not a regex feature.

**Comment by Hexaae** [comment]
Can't be added an additional custom grepWin replacement placeholder for "nothing"? Would be handy in some situations letting you replace matching strings with "nothing" (i.e. actually just remove the matching char/line...).
(Should I open a new feature Request?)
