### ISSUE TITLE
Mismatching results not as shown in RegEx test result

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#372]
![no_match_Immagine 2023-01-30 200639](https://user-images.githubusercontent.com/8591462/215571941-4c48422e-630b-4743-a647-df4a74c73a49.jpg)

This is the text I used for testing in the test panel: https://hastebin.com/uracacaxik.apache
Search string:` (\r\n)^(?!.*(\# OSD PER-WINDOW))(?!aspect0).*$`

The resulting file (upper-left open in CudaText) shows something different from what was shown in the preview (test panel).

**Comment by stefankueng** [comment]
don't use `\r\n` but only `\n` in the test dialog since grepWin normalizes the line endings.
also check the box "dot matches newline" if you search over multiple lines

**Comment by Hexaae** [comment]
but I need to remove exactly all \x0d\x0a... except those lines after ^...

**Comment by stefankueng** [comment]
also check the box "dot matches newline" if you search over multiple lines

**Comment by Hexaae** [comment]
uhm... this way though it won't do what I wanted... expected results:
```
#
# OSD PER-WINDOW VIDEO OPTIONS
aspect0                   17:10
```
I'm a newbie with RegEx though :(

**Comment by stefankueng** [comment]
do you actually want to remove everything except the "OSD PER-WINDOW VIDEO OPTIONS" and the value,
or do you want to filter that information out and create a new file with that?

The first option will get very complicated, that regex would grow to a huge monster.
The second option however is easer: just search for that and use the "Capture search" feature instead.
![image](https://user-images.githubusercontent.com/665591/215583680-8152709d-9406-4f78-b5bf-c9b4e270f21a.png)

search string: `#(?:\n|\r\n|\n\r)(# OSD PER-WINDOW VIDEO OPTIONS)((?:\n|\r\n|\n\r)#)(\n|\r\n|\n\r)(aspect0\s+[0-9.:]+)`
replace string: `$1$2$3$4`

and then use the "Capture search":
![image](https://user-images.githubusercontent.com/665591/215583904-1aa1d8b6-0255-48ca-8620-b9f0b489e397.png)

**Comment by Hexaae** [comment]
Thanks for your help. Yes, wanted to preserve just the following in the final ini, removing everything else and it seems a quite complicated challenge indeed... ;)
```
#
# OSD PER-WINDOW VIDEO OPTIONS
#
aspect0                   17:10
```
Tried your search above but I got no match at all using https://paste.sh/3vzEJkJH#_IZHMlAsw7RUu8esOdmURU5g , even when selecting "Capture search":
![image](https://user-images.githubusercontent.com/8591462/215830200-ab3bab56-ec8c-4dd7-ad82-c63b9b873409.png)
ATM, the best solution I've found is on https://stackoverflow.com/questions/75212474/keep-only-a-few-specific-lines-inside-some-text-files-using-regex-for-mass-text , which is _almost perfect_ but probably a bit incorrect.

**Comment by stefankueng** [comment]
closing this issue, because I can't start helping with regex search strings. I'm coding the tool, not supporting users with their searches, sorry.

**Comment by Hexaae** [comment]
I understand, and thanks for helping anyway.

**Comment by Hexaae** [comment]
Thinking about this bug... going back to the 1st message (and ignoring the attempt to find a better pattern-matching...) the problem was that test dialogue shows inaccurate results: processed file doesn't look like test dialogue even if I use just "\x0a" removing the \r\n thing... 🤔
Can the line ending problem you mentioned be fixed to make dialogue show the exact result? This means the test window can be misleading and inaccurate...

To show in the test dialogue the correct preview (= matches actual file after Replace) I have to use \r in front of the string:
`\r(\n)^(?!.*(\# OSD PER-WINDOW))(?!aspect0).*$`
This will remove the CR lines too from preview, as the replacement regex string without \r does on the real file:
`(\n)^(?!.*(\# OSD PER-WINDOW))(?!aspect0).*$`
