### ISSUE TITLE
grepWin x64 2.0.13 crash with RMB over results in Content preview mode

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#374]
Search in a dir full of files for something, selecting "Treat files as binary" mode,
Select at the bottom right: "Content" preview mode, and from the Search results list RMB over a matching file: grepWin will freeze and crash. Won't happen if you use "Files" preview mode instead of "Content".
Tested also on a clean VBox install of Win 10 so it should be always reproducibile...

**Comment by Hexaae** [comment]
Rolled back to 2.0.12 and this version was not affected.

**Comment by stefankueng** [comment]
took me quite a while to figure out what "RMB" meant. Next time, please write it out!

**Comment by stefankueng** [comment]
oh, in case someone's wondering: RMB = **R**ight **M**ouse **B**utton
