### ISSUE TITLE
Quantifiers in regex lookarounds

### ISSUE THREAD

**Issue by mdpenguin** [stefankueng/grepWin#381]
grepWin doesn't recognize regex patters as valid if a quantifier is included in a lookaround like the following
```
(?<=a\s+)b
(?<=a\s?)b
(?<=a\s*)b
(?<=a\s{1,})b
(?<=a\s{1,3})b

a(?=\s+b)
a(?=\s?b)
a(?=\s*b)
a(?=\s{1,}b)
a(?=\s{1,3}b)
```

grepWin version 2.0.13.1197

**Comment by stefankueng** [comment]
variable length quantifiers are not allowed in lookbehind expressions. At least not in most regex engines.
