### ISSUE TITLE
Text column does not bring information about the search

### ISSUE THREAD

**Issue by FABIOGIMENEZ** [stefankueng/grepWin#383]
When carrying out the field search process, the system does not bring the information found in the routines in the content column.

![image](https://user-images.githubusercontent.com/38988092/228038145-1539df0e-446d-4503-9454-1ae41161afbf.png)

**Comment by stefankueng** [comment]
That's expected since you've checked the box "treat files as binary" (or in your screenshot it reads "Tratar arquivos como binario".
Uncheck that box, and the text is shown.

**Comment by FABIOGIMENEZ** [comment]
Thanks!!

Em seg., 27 de mar. de 2023 às 16:05, Stefan Küng ***@***.***>
escreveu:
