### ISSUE TITLE
why my pc get hard lags when search?

### ISSUE THREAD

**Issue by ruoydnim** [stefankueng/grepWin#384]
why my pc get hard lags when search? i believe it doesn't matter if there are many or fewer files, or larger or smaller files ..
my pc get lags,some freeze on 2secs, 5secs,10secs 20secs and is totaly laged but why? i used grepwin before on my old shit pc and i never get lags when searching...sorry for my english

**Comment by stefankueng** [comment]
Sorry, but that's really a problem on your side. grepWin uses multiple threads, but what you're describing looks like trouble with hardware or drivers.
