### ISSUE TITLE
Updates are checked for, when "Settings" has the option unchecked to "Check for updates"

### ISSUE THREAD

**Issue by sean-bloch** [stefankueng/grepWin#385]
### version affected 
This is in `2.0.10.1125` , and I did not see an active issue or anything in release notes on future releases. 

### behavior
In `Settings` (button above "Search Results") , the option `Check for updates` is not selected, yet there is a notification with a clickable hyperlink that is labelled *"grepWin 2.0.13.1197 is available"*.  (annotated screenshot below: )

![image , a screenshot showing the highlighted option in settings("check for updates, and the unexpected behavior in the search dialog](https://user-images.githubusercontent.com/74521409/228290867-ad5a3d0b-d624-4435-8051-8355ecbdd4f8.png)

### expected behavior
If there is a checkbox option to "Check for updates", an unselected state is expected to "Not Check for Updates"; and would expect the app to not query the internet for updates and produce clickable hyperlinks in the app from them.

**Comment by stefankueng** [comment]
#366
