### ISSUE TITLE
Empty "Exclude dirs" and "File Names match" don't get saved correctly for presets

### ISSUE THREAD

**Issue by Destroy666x** [stefankueng/grepWin#386]
Whenever you create new presets, extra `""` are added inside `excludedirs` and `filematch` dirs in `bookmarks` file. Examples:
```
excludedirs=""""
filematch=""""
```
```
excludedirs=""""""""
filematch=""""""""
```
which is annoying because files get skipped if you don't notice this.

I'm using latest grepWIn `2.0.13.1197` version on Windows 10.

**Comment by stefankueng** [comment]
Not quite sure how you get multiple quotes listed.
Are you starting grepWin with the /preset command line switch?

**Comment by Destroy666x** [comment]
I don't modify anything, except some settings, here's a screenshot:
![image](https://user-images.githubusercontent.com/3606072/229641777-90eff845-d0fa-4a73-bdd8-01f9a2cc2951.png)
Don't think they affect presets though.

Reproduction steps are basically this, from what I see:
1. Fill text/regex search and replacement
2. Test search
3. Add to presets
4. Fill some other search replace
5. Choose the saved preset
6. Fill something else again
7. Test search and add as another preset
8. `bookmarks` file has 4 quotes for mentioned fields for the new preset.

This is an example of a preset that was affected:
![image](https://user-images.githubusercontent.com/3606072/229642860-44da35c6-f7a1-48d3-ab70-1fec823ba6f0.png)

**Comment by stefankueng** [comment]
the only way I can get to this is if I rename an existing bookmark.
Just by adding/selecting them I can't reproduce this.

**Comment by Destroy666x** [comment]
Weird then, I got it on my first try yesterday. The name was "test for bug" if it matters. Today it didn't happen with the same steps and name. Could be because I had renamed preset selected in the app earlier? But yea, I see renaming causes it for me as well. Some of presets I had with a lot of `"` could have been caused by mostly renames as there were a few that I renamed multiple times.
