### ISSUE TITLE
Request: Use Windows 11 context menu in explorer

### ISSUE THREAD

**Issue by Couchy** [stefankueng/grepWin#388]
I just noticed this since Notepad++ switched to using an entry in the new Windows 11 context menu, and thus no longer appears in the "old" right click menu, which grepWin uses. Would it be possible to use the new context menu in grepWin's explorer on Windows 11?

**Comment by stefankueng** [comment]
it already does. But of course it won't work with the portable version.

**Comment by Couchy** [comment]
Is there some option that needs to be set to enable it? I used the msi installer. I'm referring to this menu, in case it wasn't clear:
![Screenshot 2023-04-07 120627](https://user-images.githubusercontent.com/597166/230641310-de269c8d-e915-4614-b820-c0dcb920f289.png)

grepWin goes straight to the legacy menu:
![Screenshot 2023-04-07 120902](https://user-images.githubusercontent.com/597166/230641766-8afe0601-d9a1-4ab1-a8e8-84a40120a3d2.png)

Moving grepWin itself to the new menu would be nice too, but that's apretty convoluted process as the Notepad++ guys recently found out.

**Comment by stefankueng** [comment]
Oh, I see. You want the Win11 menu inside grepWin, not a grepWin entry in the Win11 menu.
I don't think that's possible, since MS rarely documents anything they do in explorer anymore.

As for NPP not showing the menu entry in the normal context menu anymore: that should be changed in NPP.

**Comment by ikender** [comment]
as an FYI, if you click "Show more options" (Shift + F10) you will see it in the context menu

You can use the old context menu (all context items) with a registry edit or with 3rd party software you can edit the context menu if you don't want to / aren't comfortable with registry edits
https://helpdeskgeek.com/windows-11/how-to-customize-the-right-click-context-menu-in-windows-11/

This link may also help @stefankueng with adding it to the page 1 context menu by default (If you look at the image in OP comment there is NanaZip and Notepad++ who have done it)

**Comment by Couchy** [comment]
This was about how to get the "new" context menu to show up within grepWin itself, which is apparently not possible. Though it might be possible to query "new" context menu entries and add them programmatically.

**Comment by ikender** [comment]
Right, and I was pointing out (for those who searched for a solution to this, and didn't know) that it is in the old (hence FYI)
and then pointed to a resource on how to always use the old context menu (which may give the developer a clue on how to find where he can add it to the new as well)
