### ISSUE TITLE
file content not matching docx files

### ISSUE THREAD

**Issue by akivalib** [stefankueng/grepWin#389]
I have been using grepwin happily for about a year.  Thanks!   Today, however, it seems not to be generating matches from docx files -- if I understand my problem, but it will match content from pdfs or stata do files (which are just text files). It does not seem to matter whether I do a text or regex search (I have also tried treating the files as UTF9 and binary, neither of which helped.)   What might I be doing wrong?
(I was using version 2.0.11 but just dowloaded the latest version, 2.0.13.1197; problem is unchanged.)

**Comment by stefankueng** [comment]
docx files are **not** text files but zipped xml files. So grepWin won't find what you're looking for.

**Comment by akivalib** [comment]
Thanks very much for clarifying.  I thought i had previously included docx files, but I guess I misremembered.

Akiva (via phone)
________________________________
