### ISSUE TITLE
Multiple lines - Normal Replace doesn't work at all 

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#390]
**See the example below. It doesn't work at all.**

```
<!-- Blog starts -->
<section id="blog" class="bg-light-gray text-left">
  <div class="container">
    <div class="row">
```
**I want to replace with:**

```
<!-- Blog starts -->
<section id="blog" class="bg-light-gray text-left">
  <div class="container">
  
  asfaf              asfsafa
  
    <div class="row">

      <!-- Blog Left Listing -->
```

![image](https://user-images.githubusercontent.com/2770489/233419653-9aa9932b-8847-4b98-9f87-9ede444d2fe2.png)

**Comment by stefankueng** [comment]
- you have "Text Search" instead of "Regex Search" selected. 
- you have "whole word" option checked
-

**Comment by me-suzy** [comment]
got it. WORKS SUPER. 

I had to check "Regex Search" instead of "Text Search"

thanks a lot
