### ISSUE TITLE
Exclude dirs with wildcard

### ISSUE THREAD

**Issue by wisemike2** [stefankueng/grepWin#392]
The "Exclude dirs" works well for exact matches using (for example dir name is **not**): 
**^(not)$**

But how to do the same to exclude any dir that has the word "**not**", like **not**tingham, or dehyp**not**ization.

I tried using * around the word, but it didn't work.

**Comment by stefankueng** [comment]
you need to learn some regex, but that's not an issue of grepWin:
https://regex101.com/

`^.*(not).*$`
should work.
