### ISSUE TITLE
First letter missing in every path in the search results

### ISSUE THREAD

**Issue by johnmcd** [stefankueng/grepWin#393]
Searching a network drive, I got results and In the path column, every path value is missing the first letter. 

![2023-04-25 10_55_50-Window](https://user-images.githubusercontent.com/1476393/234334557-3d3dfd87-859e-4b92-946f-159c21e1a17f.png)

**Comment by stefankueng** [comment]
I can not reproduce this. Works fine for me with local drive roots and network shares and mounted network shares.
How is your network drive set up?

**Comment by johnmcd** [comment]
It's a shared drive for all users with a drive letter that is established at login for each user through their profile login script. However, I noticed it does the same thing while searching local C:\  I also noticed that if you right click the path of a search result and copy the path to the clipboard, you get the  complete path, the first letter is not missing. The problem seems to be just with the display of the path string in the search results.

**Comment by johnmcd** [comment]
OS Name	Microsoft Windows 10 Pro for Workstations
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	STW-DSK-67
System Manufacturer	Dell Inc.
System Model	Precision 5820 Tower
System Type	x64-based PC
System SKU	0738
Processor	Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz, 4008 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 2.4.0, 7/6/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	06JWJY
BaseBoard Version	A00
Platform Role	Enterprise Server
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\windows
System Directory	C:\windows\system32
Boot Device	\Device\HarddiskVolume3
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.2728"
User Name	RRY\jmcdonald
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.7 GB
Available Physical Memory	20.3 GB
Total Virtual Memory	36.4 GB
Available Virtual Memory	20.4 GB
Page File Space	4.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by stefankueng** [comment]
not sure why, but check your path!
In your screenshot, the search path is `P: \` (note the space after the colon!). If you remove the space, the paths will show properly.

**Comment by johnmcd** [comment]
Yep, that was it. thank you!
