### ISSUE TITLE
Multi-line search doesn't convert regex special chars

### ISSUE THREAD

**Issue by Coldblackice** [stefankueng/grepWin#397]
When pasting a multi-line search, grepWin automatically applies the necessary newline/spacing chars. However, it doesn't escape special regex chars first, such as "(" and ")".

Apologies if this is intended.

**Comment by stefankueng** [comment]
Sorry, but there's no way to determine whether ( and ) need escaping or whether you intended them as proper regex chars, e.g. for capture groups. So what you ask for is not possible to implement without the ability of mind reading.

**Comment by Nutzzz** [comment]
While mind-reading sounds like a great feature... short of that, couldn't there be a right-click "Paste As Plain Text (Escaped)" action for the Search box (at least when in Regex mode), as well as the Exclude dirs box?  I've wanted this feature as well.
