### ISSUE TITLE
Using VS2017, cannot build grepWin

### ISSUE THREAD

**Issue by hephaestuskar** [stefankueng/grepWin#398]
Error on: `#include "language.h"`
Error on: `#include "SimpleIni.h"`
Error on: `CSimpleIni`

Is it possible build it on Visual Studio 2017?
If it is possible, how do I solve this issue?

**Comment by stefankueng** [comment]
you're missing the submodule:
`$ git submodule update --init`

**Comment by hephaestuskar** [comment]
Can I download it from external link like third party? I'd like to use it as a standalone project.
