### ISSUE TITLE
Bug: Program becomes unresponsive when dealing with large number of results

### ISSUE THREAD

**Issue by vertigo220** [stefankueng/grepWin#4]
The program takes a _significantly_ longer amount of time to perform a search when there are more results found, which seems to be an issue itself (in fact, I'm pretty sure searching one 200MB file with ~100,000 results took far longer than searching all ~2,000/40GB of files when there was only one results). But to make matters worse, during this time the program stops responding, which not only makes it look like it's frozen, but makes it impossible to cancel the search. Also, once complete, switching from 'Content' to 'Files' view for the results takes a while, and switching back to 'Content' takes even longer (much longer, in fact), and in both cases the program again stops responding during this time. Even starting a new search takes a while and causes it to stop responding, as it seems it struggles to clear the long results list as part of the execution of the new search. Assuming the new search has only a few results, performing it a second time goes much, much faster since it doesn't have to clear so many beforehand the second time.

As for the issue of it taking so much longer when there's more results, this doesn't seem to be a bug, as AstroGrep has the same problem, but it doesn't make much sense either. Regardless of whether there's 1 or 100,000 results, it still has to search all the lines in the file(s), so the only extra task is to keep track of the results. I find it very surprising that takes so much longer.

**Comment by stefankueng** [comment]
Found the part of the code that's very slow. Will have an improvement soon.

**Comment by stefankueng** [comment]
fixed in 288430c5a5b49ca977149a1ad1bcd4b554078c2a
