### ISSUE TITLE
2.0.14 x64 will not install

### ISSUE THREAD

**Issue by daxliniere** [stefankueng/grepWin#401]
Tried extracting portable x64 and it wouldn't run, even as Admininstrator. So I downloaded the regular x64 installer and that gives another message (see below), even after taking ownership of the file.

![image](https://github.com/stefankueng/grepWin/assets/8109020/fab6855b-cae5-4ca1-bb38-b48a94bc7810)

oh.. ohkay... I just re-ran the portable so I could take a screenshot of the error message and it loaded properly. 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by stefankueng** [comment]
move the installer to another location, e.g. your documents folder.
