### ISSUE TITLE
Portable x64 version of v2.0.14 does not load/apply existing INI file settings

### ISSUE THREAD

**Issue by craigtp** [stefankueng/grepWin#402]
When using the portable x64 version of v2.0.14 grepWin and replacing the .exe file in a folder that contained the v2.0.13 .exe file and an associated `grepwin.ini` file, the ini file is not read at startup by the v2.0.14 .exe (or at least, it's settings are not applied).

**Comment by jdknight** [comment]
This broke with #394 (my bad); and can be resolved with changes in #403.
