### ISSUE TITLE
Crash when using the start-of-file anchor (^) on "Treat files as binary"

### ISSUE THREAD

**Issue by regapictures** [stefankueng/grepWin#405]
With these settings:
![2023-06-05 10_29_08-grepWin _ C__EMGROUP_D _EMGroup Galantis UI ASP](https://github.com/stefankueng/grepWin/assets/4117576/5cc6b0a7-1f26-4979-b35f-9a689ebde138)
grepWin freezes and crashes.

**grepWin version:** 2.0.14.1224

Good to know:
- No issues when turning off "Treat files as binary"
- No issues when removing the start-of-file anchor (^)

I'm happy to provide more info if necessary.

**Comment by stefankueng** [comment]
https://github.com/boostorg/regex/issues/192
