### ISSUE TITLE
Bug: 2.0.14 doesn't remember last directory on launch?

### ISSUE THREAD

**Issue by wisemike2** [stefankueng/grepWin#406]
I just installed the latest version, and when I open grepWin it opens each time to "**C:\Windows\System32**".

Was this meant to be? Or a new bug? Can there be an option in the settings to "Remember last used directory(s)"?

Thanks.

**Comment by martinRocks** [comment]
I'm experiencing the same thing.  I hope it is a bug, because I liked it better the way it was before.

**Comment by stefankueng** [comment]
this was fixed with https://github.com/stefankueng/grepWin/pull/404
