### ISSUE TITLE
Request better icon

### ISSUE THREAD

**Issue by DRSDavidSoft** [stefankueng/grepWin#41]
Hi @stefankueng and thanks for your awesome app!

Do you by any chance plan on updating the program's main icon?

![grepwin](https://user-images.githubusercontent.com/4673812/45524170-4bfa8000-b7e2-11e8-960a-74c28999276a.png)

Currently this icon resembles the Windows XP set, and since you're no longer supporting either XP or Vista, I'd like to ask if you could update the icon to match Windows 7 and newer.

Maybe go for a flat looking one?

**Comment by stefankueng** [comment]
maybe @mediazombie can help out with a better icon?

**Comment by mediazombie** [comment]
I have created a new icon for grepwin in the win 10 flat design. Let me know if it is okay.
![grepwin_16](https://user-images.githubusercontent.com/4390082/45786072-197fd580-bc6f-11e8-84df-fac21b4ca03a.png)
![grepwin_32](https://user-images.githubusercontent.com/4390082/45786076-1dabf300-bc6f-11e8-8c92-4670e16a1764.png)
![grepwin_64](https://user-images.githubusercontent.com/4390082/45786078-2270a700-bc6f-11e8-8cb8-e59ec1ca87ed.png)
[grepwin.zip](https://github.com/stefankueng/grepWin/files/2398979/grepwin.zip)

**Comment by DRSDavidSoft** [comment]
@mediazombie Looks awesome! ❤️  Maybe add a flat shadow on the handle?
BTW Thanks for putting `svg` in the zip!

@stefankueng This looks much better than the old icon! 👍 
This could go really well with the `v2.0` release (or `v1.9` if you are on semantic versioning).

### Preview

<img width="177" alt="grepwin-contextmenu" src="https://user-images.githubusercontent.com/4673812/45788107-d7b25780-bc8d-11e8-847f-93a8b9afe0eb.png">

<img width="512" alt="grepwin-newiconabout" src="https://user-images.githubusercontent.com/4673812/45788113-ded96580-bc8d-11e8-87fa-40ea40d1bc1b.png">

**Comment by stefankueng** [comment]
I like it!
As for a shadow on the handle, I don't think that's necessary. It wouldn't look 'flat' anymore.

**Comment by stefankueng** [comment]
I'll prepare an 1.9.0 release for this weekend with the new icon.
Thanks @mediazombie  for the icon!

**Comment by stefankueng** [comment]
new version might take a little while longer: my card reader stopped working so I can't digitally sign the binary files anymore. And without that signature, Windows will show big warning when you try to install or run it.

**Comment by DRSDavidSoft** [comment]
@stefankueng I hope you don't lose the signing keys, that'll be a big headache.
