### ISSUE TITLE
special characters á é etc

### ISSUE THREAD

**Issue by perboe01** [stefankueng/grepWin#412]
Yesterday I manage too find and replace these characters. Today I found that the spacial characters are replaced with another character.
I cannot find the way to go back.
I try to replace (search) ó and I found ├│ in the search for
Any help will be appreciated.

![Captura de pantalla 2023-07-13 200535](https://github.com/stefankueng/grepWin/assets/38083652/e48ecf6a-4a11-44f1-8aa9-4c1658726d97)

**Comment by perboe01** [comment]
if I start grepWin and in the search box I input \ó and mark regex, works fin. 
If I try the same in a bat file using /regex:yes /searchfor:"\ó" does not work
In the search box appears  \├│

**Comment by stefankueng** [comment]
That's a problem with the console and the consoles encoding.
