### ISSUE TITLE
Identations break in "Seach for" field

### ISSUE THREAD

**Issue by pwnoobz** [stefankueng/grepWin#414]
Sometimes I want to copy a block of code and paste it in the "Search for" , but when the block of code has identations and starts a bit further from the start of the line it breaks in both "Search for" field and in "Replace with" fields.

Example:

```
					<div class="some-class">
						<div class="some-other-class">
							<div class="another-class-here"></div>
							<div class="another-class-here"></div>
							<div class="another-class-here"></div>
							<div class="another-class-here"></div>
						</div>
					</div>
```

Can you by any change improve on this?

Using the latest version on Windows 10 OS.

**Comment by stefankueng** [comment]
Sorry, but that's definitely not the job of grepWin.
Think about it: how could grepWin even know that it can/should remove leading whitespaces? How could it know that you don't want the leading whitespaces (even though you "_entered_" them)?

**Comment by daxliniere** [comment]
I have a similar issue. I want to change this:

![image](https://github.com/stefankueng/grepWin/assets/8109020/3fa94d58-c3e9-4734-a879-e46211932367)

to this:

![image](https://github.com/stefankueng/grepWin/assets/8109020/c743df14-9279-44e7-b35a-862e9c79bd86)
 
I've used the multiline editor for both (great feature, by the way!), but there are no search results.
When I use only the first line, the search function is able to find all of the lines as expected. Is there a way to solve this?

(EDIT: I wasn't even able to paste the actual text here, Github changes the formatting even when using the code tags)

**Comment by daxliniere** [comment]
This is with all characters displayed. You can see that space characters are included not only between the words, but also several of them indicating indents.

![image](https://github.com/stefankueng/grepWin/assets/8109020/9b0e8cca-3b5f-4dfa-ba9f-a58616273713)

**Comment by stefankueng** [comment]
@daxliniere when searching, use `\s+` to search for whitespace with x indentation.

**Comment by daxliniere** [comment]
Hey @stefankueng, thanks for the super-quick reply!
Sorry to be a dunce, but where in the GUI would I add `\s+`, please? And would it be possible to simply add a checkbox for this option?

All the best,
Dax.

**Comment by daxliniere** [comment]
Hey @stefankueng, where in grepWin would I add `\s+`, please?

**Comment by stefankueng** [comment]
replace space/tabs in the search window/box with `\s`
