### ISSUE TITLE
Feature request: case sensitive file name regex search

### ISSUE THREAD

**Issue by ManuelSMA** [stefankueng/grepWin#415]
Using the regex option for the file name field, the matches aren't case sensitive. I tried to prepend the "\l", but without success.

**Comment by stefankueng** [comment]
just use something like `[Ff][Ii][Ll][Ee]`
Adding yet another option just for file name search, sorry, won't do.

**Comment by ManuelSMA** [comment]
Maybe I didn't understand it yet. If I try `.*\.[L][O][G]`, I get results of both `.log` and `.LOG`. And if I try `.*\.[l][o][g]`, I get the same results.

**Comment by stefankueng** [comment]
ah, you want case _sensitive_. Sorry, misread the title.

Anyway: Windows filesystems are case-insensitive, so it does not make sense to search case sensitive.

**Comment by ManuelSMA** [comment]
Thank you for your quick reply. For me, it would have been useful, but my case may really be too rare. I just found the file search tool "Everything", and I can use it side by side with grepwin. Thank you anyway for all the effort, I really appreciate.
