### ISSUE TITLE
Search multiple folders at the same time

### ISSUE THREAD

**Issue by erickksun** [stefankueng/grepWin#42]

**Comment by stefankueng** [comment]
A little bit more effort would be nice if you're creating a new issue.

Anyway: you can already do that. Pass all the paths to your folders in the "search in" box, separated by the | char. As it explains in the tooltip.
![2018-09-19 18_36_25-grepwin _ d__downloads](https://user-images.githubusercontent.com/665591/45767710-37cbde00-bc3b-11e8-92c6-d4177624c495.png)
