### ISSUE TITLE
Set default application to open files by double click 

### ISSUE THREAD

**Issue by helperman** [stefankueng/grepWin#421]
I really like how you open associated files in Notepad++ at a certain line where match was found.
I would like to open all text files (source code files) in Notepad++ despite the application it was associated with.
For example, html-files are usually opened using web browser but when it comes to searching through a folder with these files I would like to open it at a certain line in Notepad++ or any other text editor.

**Comment by stefankueng** [comment]
configure notepad++ as the editor (click the settings button).
Then on right-click the top entry in the context menu will open the file with notepad++.
