### ISSUE TITLE
Open files associated with Visual Studio in the same window instead opening a new one 

### ISSUE THREAD

**Issue by helperman** [stefankueng/grepWin#423]
If you double click to an occurence in a *.cs file the associated application will be opened (usually Visual Studio = devenv.exe) in a new window, even if it has already been opened before.
Please open it in the same window.
By the way, opening to a certain line of code doesn't also work (the file is opened from first line).

**Comment by stefankueng** [comment]
a double click does what a double click in explorer does. That won't change.

**Comment by helperman** [comment]
No, it isn't. Have you tested this behaviour?

**Comment by stefankueng** [comment]
https://github.com/stefankueng/grepWin/blob/308b1145c278c7ada7b4877f5939cd79aa832b98/src/SearchDlg.cpp#L2606

And seriously: even asking if I tested something in my own app is an insult.

**Comment by helperman** [comment]
You closed the issue without even try to figure it out. This insulted me.
