### ISSUE TITLE
Indicate invalid regex in 'File names match' and 'Exclude dirs'

### ISSUE THREAD

**Issue by MartinRJ** [stefankueng/grepWin#424]
The "File Names match" options (Regex match/Text match) are not working as expected.

How to reproduce:

- Create a folder like T:\folder
- Create three .txt files "doc.txt", "doc2.txt", "doc3.txt" with the respective contents "stuff", "other stuff", "more stuff"
- Open Grepwin and in "T:\folder" search for "more" with the File Names match filter "*.txt" and enable the "Regex match" option. (Note: The 'include subfolders' option, which was enabled in my attached screenshot, does _not_ have to be enabled, in order to reproduce this.)
**Expected:**
Search results shows "doc3.txt"

**Actual result:**
Search results are empty.

- Switch back to "Text match" and repeat the search:
**Expected:**
Search results are empty

**Actual result:**
Search finds "doc3.txt"
![image](https://github.com/stefankueng/grepWin/assets/3988789/cc8625c7-0bc9-4c6a-8231-90e82a6c4356)

If you switch to "Text match", the regex will be applied properly, but it also works if I set the "File Names match" to Text match and search for "doc.txt". So it appears, there were some underlying changes made, that make the "Text match" accept both: regex and non-regex searches, but the UI doesn't reflect that, and the Regex match setting appears broken, and the Text match is not working as expected. When I search for Text match (non-regex, that is) with *.txt, I don't necessarily expect it to find file names that are different to literally "*.txt", when there's an explicit distinction between _regex match_ and _text match_.

There's another bug, that may be related:

- Using that same setup, in "T:\folder" search for empty string (leave "Search for" empty), with the File Names match filter "*.txt" and the "Text match" option enabled. [Observe: The results should list the three files "doc.txt", "doc2.txt", "doc3.txt"]
- Then switch the File names match option to "Regex match" and search for "123"
**Expected:**
Search results are empty, because none of the files contains the string "123".

**Actual result:**
The search results list doesn't repopulate.

Version: 2.0.15.1232 (I also tested version 2.0.10, which has the same bug)

**Comment by stefankueng** [comment]
`*.txt` is NOT a valid regex! The equivalent of `*.txt` in regex would be something like `.*\.txt`
The 'text match' option for file names matching is not just 'text' match but uses the common globs like * and ? to match the filenames. 'Regex match' however uses the regex engine to match the filenames.

**Comment by MartinRJ** [comment]
You're right, I'm sorry for the oversight. I'll do some more testing and close the issue, if it works as expected.

**Comment by MartinRJ** [comment]
I can confirm that part `#1` of the report actually works as intended, furthermore as for part `#2` of my report, it appears the missing repopulation of the list stems from the wrong regular expression.
It would help if there was some kind of warning in the UI, instead of the app just doing 'nothing'.

My confusion came from the tooltip text ("Example: `*.cpp|*.h`"), which doesn't change when you switch to "Regex match". So I assumed that these "common globs" work in the regex mode.

**Comment by stefankueng** [comment]
changing issue to somehow indicate when a regex is invalid
