### ISSUE TITLE
batch implementation of multiple operations in a single call

### ISSUE THREAD

**Issue by robrow1** [stefankueng/grepWin#43]
hello Stefan, I using GrepWin for a long timp. I am a web designer, I use your tool as regex tool to repair many things on my 10.000 html pages. I am also a guru in regex.

I have one single problem. Many times, I need to implement multiple operations and I don't have time for manage all those operations, each one.

Can you make some kind of Batch Process, so to use many saves regex in order I want, so as to resolve my problems when I am gone for laptop?

I send you a print screen of another text procesor, named TextCrawler (not so faster as GrepWin), just to see how should works.

https://snag.gy/nDoJ5r.jpg

So, I write regex in order I want, press ok, and it runs every command till finnish. Wonderfull Idea !

**Comment by stefankueng** [comment]
Dupe of #92
