### ISSUE TITLE
Get rid of timeout after click menu item in a list

### ISSUE THREAD

**Issue by ask9** [stefankueng/grepWin#430]
Menues in all buttons with |-symbol are affected.
![0000001045](https://github.com/stefankueng/grepWin/assets/33929221/3ced86ff-2b21-4d9e-9b7b-ef59ec2c7664)

**Comment by stefankueng** [comment]
what timeout? what do you mean?

**Comment by ask9** [comment]
One-second pause between click to "*.cs|*.sql" and its response.

**Comment by stefankueng** [comment]
this is handled by windows alone:
https://learn.microsoft.com/en-us/windows/win32/api/shldisp/nn-shldisp-iautocomplete2
https://learn.microsoft.com/en-us/windows/win32/api/shobjidl/nn-shobjidl-iautocompletedropdown
