### ISSUE TITLE
Search 'n Replace with Text: issue with "\" backslash in replace text

### ISSUE THREAD

**Issue by ToniMa1** [stefankueng/grepWin#431]
Searching in text mode works well, but when it comes to replace it doesnt escape the "\\" char. seems they are used as regex in replace mode. (version 2.0.15.1232)

Example:

**Search**: C:\\temp\\search
**Replace**: C:\\temp\\errors

**File content before**: C:\\Temp\\search\\text1.txt
**Result in file**: C:\\temprrors\\text1.txt

**Comment by ToniMa1** [comment]
Workaround:

Double the "\\" backslash in replace will help, but unhandy.

**Comment by stefankueng** [comment]
That's by design. Otherwise you couldn't replace something with e.g. a newline.

**Comment by ToniMa1** [comment]
Hi stefan,Eine frage: auch by design bei text suche?? Bei regexmodus wärs mir klar, aber text sollte doch nicht interpretiert werden, oder? Lg martin Von meinem iPhone gesendetAm 27.10.2023 um 22:17 schrieb Stefan Küng ***@***.***>:﻿
Closed #431 as completed.

**Comment by stefankueng** [comment]
Not when searching, no.
