### ISSUE TITLE
regex in commandline mode not work

### ISSUE THREAD

**Issue by hoangdiemtinh** [stefankueng/grepWin#432]
sorry for my bad english.

I run cmd:

"G:\grepWin-v2.0.15-2023-6-10\grepWin-2.0.15_portable.exe" /regex:yes /searchpath:"G:\set.txt" /searchfor:display_name="(.*?)" /replacewith:display_name="ok fine" /executereplace /nosavesettings /k:no /closedialog

Content in set.txt file:
abc.display_name="a1 b1 c1" 
def.display_name="a2 b2 c2"

**regex in commandline mode not work.
regex in form mode is work.**

![image](https://github.com/stefankueng/grepWin/assets/67616643/89a5e6a5-91c4-4fec-abc9-ee5306fa6ee3)

**please help for my case.**

**Comment by hoangdiemtinh** [comment]
I corrected myself.
display_name="\\"ok fine\\""

**Comment by stefankueng** [comment]
if you want to pass complex regex search strings via command line, you'll have to use the ini file approach because the command line get's parsed as commands.
So: use the /searchini command.

https://tools.stefankueng.com/grepWin_cmd.html
