### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by dl1mx** [stefankueng/grepWin#433]
Hi Stefan,
I'm updating my Windows 10 programs regulary with the winget tool. After I installed grepWin version 2.0.15, I always get an update recommendation from winget, although version 2.0.15 is the only installed version. Installation with grepWin-2.0.15-x64.msi for all users.

If I look into "Programs & Feature" I get the following version:
![installed](https://github.com/stefankueng/grepWin/assets/3036287/3d8bda00-bbd0-4945-8541-c92aa8c41059)

And winget show the following dialog:
![winget](https://github.com/stefankueng/grepWin/assets/3036287/a7125aad-2dd9-419b-b721-42bf22e0f45a)

But grepWin has version 
![version](https://github.com/stefankueng/grepWin/assets/3036287/f17691d6-30a1-4596-8ac3-e54614574b95)

What can be the root cause of this version mismatch? Why is the old version of 2.0.1232 listed in Windows programs? Maybe it has to do with version.txt from git, which shows 2.0.15.1232.

Best regards, Marco

**Comment by stefankueng** [comment]
I don't maintain the winget package. Don't even know who does.
You'll have to get answers from winget somehow.

**Comment by dl1mx** [comment]
Okay, but your installer seems to write the wrong version to the windows regsitry:
![installed](https://github.com/stefankueng/grepWin/assets/3036287/3d8bda00-bbd0-4945-8541-c92aa8c41059)

So it has no direct connection to winget package.
