### ISSUE TITLE
searching binary files doesn't always find text

### ISSUE THREAD

**Issue by bsabiston** [stefankueng/grepWin#435]
I'm using GrepWin to find text within Unreal .usasset files.  I noticed that it sometimes misses files that have the text in them.  All these files have the same binary format, as far as I know.  Not sure why it would miss some and not others...

**Comment by stefankueng** [comment]
Sorry, but 'sometimes' and 'as far as I know' doesn't help at all. I can't really do anything with such an issue. I would need the file(s) in question and the search regex and all the options set for the search.
If you can reproduce the problem, feel free to reopen the issue.

**Comment by bsabiston** [comment]
Sorry I know that isn’t helpful but unfortunately I am not allowed to share the file.  Just didn’t know if you cared to know the problem exists.  If I run across a repo I can share, I will.  It was no regex just a straight search for a text string in a binary file.

**Comment by Coldblackice** [comment]
> Sorry I know that isn’t helpful but unfortunately I am not allowed to share the file. Just didn’t know if you cared to know the problem exists. If I run across a repo I can share, I will. It was no regex just a straight search for a text string in a binary file.

Why not hex-chop the executable down to the specific slice of what's not being found? And stripping out any personal/proprietary info in the process.

An example is pretty necessary for any sort of fixing/troubleshooting.

**Comment by bsabiston** [comment]
I said I knew it wasn't helpful.  I don't remember what the file was, six months later.
