### ISSUE TITLE
Dark mode setting does nothing

### ISSUE THREAD

**Issue by Protuhj** [stefankueng/grepWin#436]
Win64 .msi install
Windows 11 Professional
![image](https://github.com/stefankueng/grepWin/assets/1165219/28b40a5c-88b0-459d-942e-b5e468332e40)

I go to settings, check "Dark Mode", hit 'Ok' and nothing happens.

When I open settings again. "Dark Mode" is no longer checked.

**Comment by Richard-L** [comment]
Working fine here 
![image](https://github.com/stefankueng/grepWin/assets/4934209/988bba0f-5c82-4959-be01-7c0a54da0994)
Is the app in a location on your PC where you don't have write rights, so it cannot save the theme setting?

**Comment by Protuhj** [comment]
I can run as Administrator and it still fails. I can try to record a video if you don't believe I'm doing it right.

**Comment by Protuhj** [comment]
~~From the little I looked at (and understand) the code, it checks if dark mode is supported. Maybe that doesn't work correctly in Win 11 pro?~~

Edit: yes. You **have** to enable the Dark Mode theme in Win 11. I wouldn't expect them to be related, but that fixes the problem.

**Comment by Protuhj** [comment]
Maybe it would be helpful to warn the user they need to do that? Otherwise it just looks like it does nothing.
