### ISSUE TITLE
How to provide Traditional Chinese translation?

### ISSUE THREAD

**Issue by doggy8088** [stefankueng/grepWin#437]
I saw there is a `Chinese.lang` file been provided. In Chinese, there are two variant. 

1. Simplified Chinese ( zh-CN ) ( current one )
2. Traditional Chinese ( zh-TW )

I'd like to provide translation for Traditional Chinese. Can you guide me how can I contribute this?

**Comment by stefankueng** [comment]
the *.lang files are simple po-files which can be translated with any po-editor you like (e.g. [poEdit](https://poedit.net/download/)), or a simple text editor will do as well.
