### ISSUE TITLE
Stop button (stop search) can take some minutes on very large files

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#461]
grepWin 2.0.15.1232, NVMe 3GB/3GB, Win11 23H2, i7-8750H, 32GB RAM
Is it possible to make **Stop** button more responsive?
I noticed grepWin can take even 60+ secs to stop searching if the dir contains huge single files like emulator roms of 8GB+
Probably a side-effect of its blazing fast search multi-threading routine, but can be a pain having to wait 90+ secs before you actually see search being canceled.

BTW, when search is running Stop button will show help-bubble of Start button (which can be confusing).

**Comment by lifenjoiner** [comment]
> dir contains huge single files like emulator roms of 8GB+

Use the size limit "less than", first.
Terminating threads forcibly is not a good choice.

**Comment by Hexaae** [comment]
I don't want to limit file size as I need to search in big files too. Let's see what the author says, if there's some room for improvement or it can't be changed.

**Comment by stefankueng** [comment]
unfortunately, while a search is in progress of a very big file, stopping a search is only possible when a match is found or when that file is completely searched.

**Comment by Hexaae** [comment]
No way to insert some parallel "timed checkings" and in case stop the process, I guess...
I can live with that anyway, a bit annoying but the pros of grepWin of course highly surpass this rare case.

P.S. don't forget the incorrect help bubble on the Start/Stop button while is still searching...

**Comment by lifenjoiner** [comment]
Had optimized already by commits [d587ce1, c8b911f].
