### ISSUE TITLE
Replace does nothing with binary files

### ISSUE THREAD

**Issue by 7kt4** [stefankueng/grepWin#465]
Replace text in binary files does nothing, it just flashes for a second and does not touch the files

**Comment by lifenjoiner** [comment]
Try the latest Artifacts from https://github.com/stefankueng/grepWin/actions. I had improved it.

**Comment by 7kt4** [comment]
> Try the latest Artifacts from https://github.com/stefankueng/grepWin/actions. I had improved it.

This version corrupts the binary files

**Comment by lifenjoiner** [comment]
Prove it.

To be honest, binary files vary. It is highly likely that they are not correctly decoded, BTW.
You should know that, and don't expect it works in the same way like text files.
Only do it when you know exactly what you are doing, and always make backups.

**Comment by 7kt4** [comment]
> Prove it.
> 
> To be honest, binary files vary. It is highly likely that they are not correctly decoded, BTW. You should know that, and don't expect it works in the same way like text files. Only do it when you know exactly what you are doing, and always make backups.

It removes two bytes from the file for some reason, hence corrupting it

https://github.com/stefankueng/grepWin/assets/84914212/f04a2a5c-e227-4a99-9247-2b1ae4870ec2

**Comment by lifenjoiner** [comment]
Thanks for your feedback!
Should be fixed by https://github.com/stefankueng/grepWin/commit/dc586b1fcea22af8ed72999ff3ebc0ec5534dfb3. Try the latest.
