### ISSUE TITLE
Issue with a search replacement that contains a backslash

### ISSUE THREAD

**Issue by u01jmg3** [stefankueng/grepWin#467]
## Expected

Search for:
`namespace App\Models\Assessments;`

Replace with/Capture format:
`namespace App\Models\Assessment;`

## Actual

`namespace AppModelsAssessment;`

---

ℹ️ The same issue does not exist with forward slashes.

**Comment by stefankueng** [comment]
`\` is the escape character (so you can use e.g. `\n` for a newline). You have to use
`namespace App\\Models\\Assessment;`

**Comment by u01jmg3** [comment]
I realise `\` is the escape character but is there no way GrepWin can handle this for me? It's also not obvious to the user that manual escaping is required.

e.g. in Notepad++, they have a "search mode" that allows you to toggle on/off whether `\` is treated as an escape character.

<img src="https://github.com/stefankueng/grepWin/assets/1266205/978dcac5-5077-4197-b6cd-b03024ca526c" width="70%"/>

**Comment by stefankueng** [comment]
grepWin is a regex tool. So the regex rules apply, which includes escaping.

**Comment by lifenjoiner** [comment]
Try "Text search" mode using the CI build of the latest commit.

**Comment by u01jmg3** [comment]
> _grepWin is a regex tool. So the regex rules apply, which includes escaping._

Even on a "text search"?

---

Same outcome using the "text search".

![image](https://github.com/stefankueng/grepWin/assets/1266205/c7ed04ca-b69f-4aaa-b3ef-dfd702808638)

**Comment by lifenjoiner** [comment]
https://github.com/stefankueng/grepWin/actions/runs/8424535527

I had fixed it.

**Comment by u01jmg3** [comment]
Thanks @lifenjoiner

I managed to download the artifact build from GitHub Actions and sure enough it works. I guess this was fixed a while ago?

Looking forward to seeing this in an official release
