### ISSUE TITLE
Not all regex replacement placeholders work

### ISSUE THREAD

**Issue by Coldblackice** [stefankueng/grepWin#470]
I love my grepWin, utilizing it every day. On grepWin v2.0.15.1232 (likely other versions), however, not all regex replacement placeholders work explained via F1 help work. Namely:

- "$`" / "${^PREMATCH}" 
- "$'" / "${^POSTMATCH}"
- "$+{NAME}"
- "${now}"

...most useful being those first two placeholders. Is it possible to fix?

**Comment by stefankueng** [comment]
they all work for me just fine.
However in the test dialog, `${now}` doesn't work (the other work in the test dialog as well)

please test again, and if it doesn't work for you I need an example, meaning the original text, the regex to search for and the replacement text, and then what you would expect as the result.
