### ISSUE TITLE
zero matches

### ISSUE THREAD

**Issue by choochum99** [stefankueng/grepWin#471]
in grepwin 'inverse search NOT searchstring' is the default setting for the Search button.  Nothing else works so I get zero matches every time I try any search for any text. Most of the time when I hit the Search button nothing happens at all. I have no filters and a search for text & a search including subfolders checked.  Nothing seems to make a difference

**Comment by stefankueng** [comment]
No, the search button has always the default for a normal search.
an 'inverse search NOT searchstring' is only done when you have the shift-key pressed while clicking on the button (or shift pressed while pressing enter).
