### ISSUE TITLE
Command line parameters are not being "honored"

### ISSUE THREAD

**Issue by old-guy-surviving** [stefankueng/grepWin#472]
Using the UI, I can search/replace just fine.  I'm using regex for both.  
I'm also using a "filemask" - VERY important aspect for what I'm trying to do as it needs to work across a large number of files.

When setting this up as "command line parameters" - it fails.  Exact same thing with the UI works.

Instead of using /filemask:"*.whatever", I have tried eliminating that parameter and just specifying the full path with filename as the "/searchpath" parameter (no wildcard characters).  I think this works but totally makes the /filemask parm useless.

I'm using v2.05.15.1232

**Comment by stefankueng** [comment]
What is the exact command line you're using? And then what do you expect and what actually happens?
When I add `/filemask:"*.txt"` it works as expected for me.

**Comment by old-guy-surviving** [comment]
This is some of the script from my "cmd" file that currently is working.
set data_path=C:\Data\Excel
"C:\Program Files\grepWin\grepWin.exe"
/searchpath:"%data_path%\Yahoo-NG.tmp" /searchfor:"</td><td class=.*
data-symbol" /replacewith:"data-symbol" /executereplace /k:no /i:yes /n:no
/nosavesettings /closedialog
"C:\Program Files\grepWin\grepWin.exe"
/searchpath:"%data_path%\Yahoo-CL.tmp" /searchfor:"</td><td class=.*
data-symbol" /replacewith:"data-symbol" /executereplace /k:no /i:yes /n:no
/nosavesettings /closedialog
"C:\Program Files\grepWin\grepWin.exe"
/searchpath:"%data_path%\Yahoo-HO.tmp" /searchfor:"</td><td class=.*
data-symbol" /replacewith:"data-symbol" /executereplace /k:no /i:yes /n:no
/nosavesettings /closedialog
"C:\Program Files\grepWin\grepWin.exe"
/searchpath:"%data_path%\Yahoo-RB.tmp" /searchfor:"</td><td class=.*
data-symbol" /replacewith:"data-symbol" /executereplace /k:no /i:yes /n:no
/nosavesettings /closedialog


Originally, instead of the last 4 lines specifying the "search files"
individually, I had used the "filemask" parameter (as shown below) but it
failed from the command line.
"C:\Program Files\grepWin\grepWin.exe" /searchpath:"%data_path%"
/filemask:"*.tmp" /searchfor:"</td><td class=.* data-symbol"
/replacewith:"data-symbol" /executereplace /k:no /i:yes /n:no
/nosavesettings /closedialog

If I go in and use the GUI, it would work.

**Comment by stefankueng** [comment]
still, works fine for me here.
