### ISSUE TITLE
BUG replacing text as "Text Search"

### ISSUE THREAD

**Issue by Softproman** [stefankueng/grepWin#476]
I have the file "FileWithTextToBeReplaced.txt" with content: `<DCC_BplOutput>..\Lib\RAD11\$(Platform)\</DCC_BplOutput>`
![image](https://github.com/stefankueng/grepWin/assets/104144857/01099a6a-21e7-4837-9270-5e477b2c9e3c)

I wish replace the word "RAD11" by "RAD12" with GrepWin. I configure as...:
![image](https://github.com/stefankueng/grepWin/assets/104144857/a109bf46-9f0b-472e-9d6e-2628e42301a4)

I press "Replace" and the content of "FileWithTextToBeReplaced.txt" is: `<DCC_BplOutput>..ibrad12\$(platform)</dcc_bploutput>`
![image](https://github.com/stefankueng/grepWin/assets/104144857/80246ffa-de76-456f-b4fa-1bca28cef87f)

The replacement is wrong.

**Comment by TheCartpenter** [comment]
Looks like a malformed regex search pattern. I used the ```regex search``` option instead of the ```text search``` option and I searched for:

```<DCC_BplOutput>..\\Lib\\(RAD11\\)\$\(Platform\)</DCC_BplOutput>```

I replaced it with:

```<DCC_BplOutput>..\\Lib\\RAD12\$\(Platform\)</DCC_BplOutput>```

Works just fine.

**Comment by stefankueng** [comment]
works fine with the latest dev version:
https://github.com/stefankueng/grepWin/actions/runs/9155897409

**Comment by Softproman** [comment]
GitHub ate a character at the beginning of the post (ScreenShot and image not match. I have solved it). My intention was to search for plain text, not regular expressions. In any case, I have tested it with the latest development version that you have attached and the search works correctly. With the latest official version (2.0.15) the problem is reproduced.

**Comment by Softproman** [comment]
GitHub ate a character at the beginning of the post (ScreenShot and image not match. I have solved it). My intention was to search for plain text, not regular expressions. In any case, I have tested it with the latest development version that you have attached and the search works correctly. With the latest official version (2.0.15) the problem is reproduced.
