### ISSUE TITLE
Searching in C:\ and subfolders doesn't work

### ISSUE THREAD

**Issue by agiudiceandrea** [stefankueng/grepWin#478]
Searching in `C:\` always returns "Found 0 files, skipped 25 files". In my Windows 10 64 bit system `C:\` contains 32 folders (6 of which are hidden) and only 1 file.

![image](https://github.com/stefankueng/grepWin/assets/16253859/a0d33f8a-decc-4e8e-9a9f-e2e6f91e9c9b)

grepWin 2.1.0

**Comment by stefankueng** [comment]
works fine for me. Do you have read access to the folders in `c:\` ?

**Comment by agiudiceandrea** [comment]
> works fine for me. Do you have read access to the folders in `c:\` ?

Yes, the user has read access to almost all the folders (except e.g. the folders under `C:\Users\different_user`), and obviously also to `C:\Program Files\grepWin` which contains `grepWin.exe`. In fact, if I search for `grepwin.exe` in `C:\Program Files\` using grepWin, then the searching succeeds and `grepWin.exe` is correctly found in `C:\Program Files\grepWin`

![image](https://github.com/stefankueng/grepWin/assets/16253859/fa30bbc9-c418-465f-ab6c-dced4c5fddbd)

**Comment by reggie-vanwyk** [comment]
Same thing happens to me with 2.1.0.1328.  Note it only does it from the root of C:\ for me.  From a subfolder (i.e. C:\Dev) it works fine.

Note I am running Windows 11 22H2 (64bit).

**Comment by Epitax** [comment]
I have the same problem with grepWin v2.1.0.1328 in Windows7.
I did not have this problem with previous versions of grepWin with exactly the same search and the same path.

**Comment by agiudiceandrea** [comment]
I can confirm the issue doesn't occur using grepWin 2.0.15.1232 while it does occur using grepWin 2.1.0.1328.
