### ISSUE TITLE
Context menu issue since upgrading to v2.1.0 on Win 11

### ISSUE THREAD

**Issue by u01jmg3** [stefankueng/grepWin#480]
Since upgrading to [v2.1.0](https://github.com/stefankueng/grepWin/releases/tag/2.1.0), there appears to be an issue with how grepWin integrates with my context menu.

I've now got duplicate entries when right-clicking on the background of a folder:

<img src="https://github.com/stefankueng/grepWin/assets/1266205/d9a4e448-8bbe-41ca-a478-b4ed714aa641" width="65%"/>

---

I tried downgrading back to [v2.0.15](https://github.com/stefankueng/grepWin/releases/tag/2.0.15) (uninstall then fresh install) where I had no such issue but my context menu is still broken.

- Is there anything I can do to fix this?

**Comment by stefankueng** [comment]
MS designed the Win11 context menu specifically to prevent apps from adding more than one entry. If an app tries to add more than one, Win11 will combine those into one with a submenu automatically.
So what you're seeing here should not be possible.

That also means I have no idea on how this can happen :(

**Comment by u01jmg3** [comment]
Strangely, I (correctly) get one option when right-clicking directly on a folder or the background of my desktop:

<img src="https://github.com/stefankueng/grepWin/assets/1266205/c7ec64dc-bb55-415f-9f54-10b02523690e" width="45%"/>

**Comment by u01jmg3** [comment]
It is likely caused by having grepWin installed for my user (the default installer setting) and then also for everyone. Unfortunately, the installer does not currently remember what setting has been used by previous installations and that's likely how I ended up with my issue.

Resolving issue #292 will prevent this
