### ISSUE TITLE
Sorting by path is not quite correct.

### ISSUE THREAD

**Issue by asdfchlwnsgy1236** [stefankueng/grepWin#485]
Please look at the screenshot below.
![image](https://github.com/stefankueng/grepWin/assets/8199342/6a5217d9-4830-425e-bd8c-489b702ed01e)

**Comment by stefankueng** [comment]
and what exactly is not correct?

**Comment by asdfchlwnsgy1236** [comment]
It is supposed to be sorted by path in ascending order, but you see the rows of ...\Config, and then some ...\Config\XUi, some more \Config, and then some ...\Config\XUi_Menu.
I believe the correct sorting would not have those in mixed order like that.

**Comment by asdfchlwnsgy1236** [comment]
Unrelated, but I also just noticed that the highlighting for the matching string is off by one character to the right.
Should I make a new issue for that?
