### ISSUE TITLE
Regex hex search incorrect?

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#486]
![image](https://github.com/stefankueng/grepWin/assets/8591462/868b426a-e260-4a56-b31e-71b4bbbcadfb)

As you can see GrepWin finds a pair of matches of hexadecimal string: $0000536900... but there is no trace of that exact string in [the file](https://1drv.ms/u/s!ApMUGr0cuN39g9ok1IX3ym54bpl1Hg?e=w3bqHm).
Mmmh...

**Comment by stefankueng** [comment]
what it actually finds is also \x00\x00\x53\x49, because you also have 'search case-sensitive' unchecked. The case-insensitive search also affects the hex search.

**Comment by Hexaae** [comment]
Ah! I had that doubt in fact... Thank you.
