### ISSUE TITLE
Jumping to filename in list

### ISSUE THREAD

**Issue by mrx23dot** [stefankueng/grepWin#487]
given I have a long list of files

![2024-06-23_000845_WC](https://github.com/stefankueng/grepWin/assets/4163396/91610472-f647-4452-b31d-fd9700ed0083)

when  I press 's' button, it jumps to first item in list not to next one starting with S,
 compared to cursor position (even when not sorted)

v2.13

**Comment by mrx23dot** [comment]
Thank you!

but I'm testing 2.1.3.1355 and standing here, when I press 'b' it doesn't jump to Belarusian.lang  
![2024-06-29_105251_SX](https://github.com/stefankueng/grepWin/assets/4163396/4382f153-fd99-414b-9e3a-35bffa5017dd)

even though it's sorted by name.

**Comment by stefankueng** [comment]
ups, forgot the content view...
