### ISSUE TITLE
Crash on crash on crash

### ISSUE THREAD

**Issue by gemal** [stefankueng/grepWin#492]
I love your product but with the latest releases the app keep crashing and crashing doing different operations.
I never had a crash until I think version 2.10 or so.
Now it's VERY VERY unstable

If I do a search and then do a replace I often get a crash. Not 100% sure I can reproduce.
Do you have a crash reporter installed?

**Comment by gemal** [comment]
and the "Stop" button also stopped to work :(
Using version 2.13

**Comment by stefankueng** [comment]
you can set up windows to get crash dumps:
https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

and check memory use of grepWin, maybe its out of memory?

**Comment by stefankueng** [comment]
will be fixed with 2.1.4
