### ISSUE TITLE
Keyboard shortcut to copy files/file path ?

### ISSUE THREAD

**Issue by mdnava** [stefankueng/grepWin#494]
Hello Stefan, is there a keyb shortcut available to copy files/file paths from the result list (SysListView321) ?
I've tried CTRL+C, ALT+C, ALT+SHIFT+C .. among others..

If not, please consider it. I do believe copying the file should be the default behavior of CTRL+C, as in Windows Explorer.
But setting a different keyb shortcut for it like ALT+C would make things easier.

There are several reasons for the need of this keyb shortcut, but the most important is to avoid having to open
a context menu to select "COPY", which at times is not immediate. I also use it to set AutoHotkey keys to convert
all "COPY" results as plain text and use ithem as arguments to open files with different editors (not default in Windows)
like CTRL+F12 for VSCode and ALT+F12 for BowPad.

Best regards!.

**Comment by stefankueng** [comment]
so let's change it so:

- Ctrl+C: copies all selected paths
- Ctrl+Shift+C: copies all colum texts (as Ctrl+C does now)
- Ctrl+Alt+C: copies all selected filenames (not full paths)
