### ISSUE TITLE
New Version 2.1.3.1355 - Crash after first find/replace

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#498]
I test many times. So, if I have more then 2.000 files, for example html files, and I want to find and replace in these folders. A very simple example:

**Search in:** `e:\Carte\|d:\Ocazki\|c:\Folder-Oana\`

a simple find and replace:

**FIND:**` ./creative-studio/`
**Replace by:** _stereos.com/creative-studio/_

After done this task, and I try every other search and replace, GrepWin crashes and closes. It happens every time. I assume it's because of the countless files it has to change. But it is not allowed to crash.

**Comment by stefankueng** [comment]
#492

**Comment by me-suzy** [comment]
Still crash after multiple find/replace in more then 4000 html files. It doesn't crash as quickly as the previous version, but after several reloads it crashes again

I report to Windbg, as you want. Hope to see it. And, maybe if will find and replace a little bit faster for the next version.

**Search in:**   `e:\Carte\BB\17 - Site Leadership\Principal\ro\|e:\Carte\BB\17 - Site Leadership\Principal\en\`

**Find:**

```
<!-- Ultimele articole -->
        
     <p class="text_obisnuit2">Ultimele articole accesate de cititori:
<ol>
       <li><a href="https://neculaifantanaru.com/alchimistul-II.html">Alchimistul (II)</a></li>
       <li><a href="https://neculaifantanaru.com/alchimistul.html">Alchimistul (I)</a></li>
       <li><a href="https://neculaifantanaru.com/tango-to-evora.html">Tango to Evora</a></li>
        <li><a href="https://neculaifantanaru.com/sa-vezi-ceea-ce-nu-se-poate-vedea-decat-foarte-rar.html">Lily was here</a></li>
     </ol>
     </br>

<!-- Ultimele articole final -->
```

**Replace with:**

```
<!-- Ultimele articole -->
        
     <p class="text_obisnuit2">Ultimele articole accesate de cititori:
<ol>
       <li><a href="https://neculaifantanaru.com/ochii-mei-vad-lucruri-pe-care-tu-nu-le-vezi.html">Ochii mei vad lucruri pe care tu nu le vezi</a></li>
       <li><a href="https://neculaifantanaru.com/te-admir-cu-ochii-ce-nu-i-vezi.html">Te admir cu ochii, ce nu-i vezi</a></li>
       <li><a href="https://neculaifantanaru.com/autenticitatea-omului-care-se-gandeste-pe-sine.html">Autenticitatea omului care se gandeste pe sine</a></li>
        <li><a href="https://neculaifantanaru.com/ochiul-sfant-al-lui-paracelsus.html">Ochiul sf&acirc;nt al lui Paracelsus</a></li>
     </ol>
     </br>

<!-- Ultimele articole final -->
```
