### ISSUE TITLE
open with notepad4 but the colmun is not offset enough

### ISSUE THREAD

**Issue by Tback1** [stefankueng/grepWin#500]
![image](https://github.com/user-attachments/assets/ae657464-f93b-4fc4-b62d-2a35c7e13aa4)

https://github.com/zufuliu/notepad4/issues/827

I tried to search through grwpwin, and grepped the correct offset at the colmun position of the result.
But when notepad4 was opened, the offset parameter was passed correctly.
But the result was not in line with my intuition.
The startup parameters were as follows: .\Notepad4.exe /g %line%,%column% - %path%
The text was simply a string of numbers 0-9
0123456789
Search for the number 5 and find line 1 column 5
Intuitively, column: 5
should correspond to the position after 5 and before 6, which means that the cursor is now after 5, which is in line with my intuition.
Or the position after 4 and before 5 is also understandable. That is, the cursor is at least before or after 5.
But now, after passing the line 1 column 5 parameter to notepad4, the cursor position is actually after 3, which is quite outrageous.
Of course, from the parameters passed, we can see from the status bar that the position of line 1 column 5 is indeed after 3.

**Then we need to consider how both sides define the line number, whether it is 0 or 1, and whether the column offset is the front offset or the back offset. This needs to be unified on both sides, or can grepWin consider adding a user-set offset before the column parameter is passed out?**

**Comment by lifenjoiner** [comment]
Test the latest dev built artifacts from https://github.com/stefankueng/grepWin/actions?query=branch%3Amain.

**Comment by Tback1** [comment]
> Test the latest dev built artifacts from https://github.com/stefankueng/grepWin/actions?query=branch%3Amain.

OK this is is the front offset. work well with notepad4
![image](https://github.com/user-attachments/assets/86fe104a-251a-4387-b365-4bc5da1bd79d)

but I still think maybe need add a setting to set the offset addiction,to fit for other setting editor.

**Comment by lifenjoiner** [comment]
I guess all editors adopt this way as de-facto standard. Imagine selecting characters `[1, 2]`.
