### ISSUE TITLE
Issue with matching files within a subfolder

### ISSUE THREAD

**Issue by u01jmg3** [stefankueng/grepWin#502]
ℹ️ **Note 'Include subfolders' is checked**

![demo](https://github.com/user-attachments/assets/fdbe8cba-de12-4f8c-b368-0377495f3504)

**Comment by ronh991** [comment]
I have same issue - filename with wildcards does not work

**Comment by bitzer-sbc** [comment]
In version 2.1.4.1372, the 'Filenames match' doesn't work at all. In my case I search for content in all files. One of the files found is Build.cs, but when I put Build.cs in the 'Filenames match', nothing is found. Same happens with *.cs BTW
![GrepWinIssue2](https://github.com/user-attachments/assets/4a73108b-7951-447d-8ee0-3afb9f1028a9)

**Comment by charles-dexter-ward** [comment]
It seems that setting a search path wgich contains only folders in the first level does not run inside the sub-folders even if "Include subfolders" is checked.

**Comment by lifenjoiner** [comment]
Test the latest dev built artifacts from https://github.com/stefankueng/grepWin/actions?query=branch%3Amain.

**Comment by u01jmg3** [comment]
Appreciate the fix but shall leave someone else to test it as the artifact is being detected as containing malware: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.H!ml&threatid=2147814524.

Will wait for @stefankueng to make a new release

**Comment by lifenjoiner** [comment]
@bitzer-sbc
> https://github.com/stefankueng/grepWin/issues/502#issuecomment-2257638427

Does the new built work for you?
I didn't reproduce it even with version 2.1.4.1372.
If it doesn't work, we need reproduce it and then diagnose.

Malware? I don't think so. `Opened sources compiled with github actions` Vs `silly machine`.

**Comment by u01jmg3** [comment]
_\* Silly Microsoft_

**Comment by lifenjoiner** [comment]
@bitzer-sbc
> https://github.com/stefankueng/grepWin/issues/502#issuecomment-2258438688

Reproduced:
the file for `File Names Match` must be in a sub folder to trigger it.

It has been fixed by my test.

**Comment by ronh991** [comment]
just an FYI - 2.1.4 does not seem to uninstall 2.1.3 - I see two grepWins in my App uninstall.  Have no idea if this is of concern.

**Comment by lifenjoiner** [comment]
@ronh991 
> just an FYI - 2.1.4 does not seem to uninstall 2.1.3 - I see two grepWins in my App uninstall. Have no idea if this is of concern.

Didn't reproduce it on Win10 sandbox.
I always prefer portable version, for all apps. 😁
Seriously, there is no setup behavior change from v2.1.3 to v2.1.4.

**Comment by bitzer-sbc** [comment]
@lifenjoiner The latest build solves my issue, thank you very much 🍻

**Comment by lifenjoiner** [comment]
> just an FYI - 2.1.4 does not seem to uninstall 2.1.3 - I see two grepWins in my App uninstall. Have no idea if this is of concern.

Caused by having 2 different installed types ("for current user" and "for this machine") from advanced option.
Go to #292.
