### ISSUE TITLE
Rigth menu Can't working in Directory Opus 13

### ISSUE THREAD

**Issue by sinfee** [stefankueng/grepWin#505]
The rigth menu item " Search in grepWin " within Directory Opus 13 (my version is  13.8/13.9 ) , Can't popup grepWin windows .

**Comment by lifenjoiner** [comment]
That is an alternative to Explorer. I guess it does not follow the system's rules.
And it is a proprietary software, maybe you should ask them.

**Comment by lifenjoiner** [comment]
Reopen if there is really an issue of grepWin.

**Comment by sinfee** [comment]
![image](https://github.com/user-attachments/assets/49614126-fac2-4a42-955b-34561aa8b352)
The menu item in picture at 1 can be clicked, but the menu item at 2 cannot be clicked. 
I found after comparing that grepWin would appear as two menu items in the right-click menu of Directory Opus 13. I analyzed and concluded that the two occurrences were from the new quick right-click menu in Windows 11 and the standard Windows Explorer right-click menu. DO essentially copied two sets of the right-click menu, and the grepWin from the new quick right-click menu did not respond when clicked. However, programs like PowerRename (within Powertoys), Beyond Compare 5, and Code Insiders could be clicked and opened, but grepWin could not. I recommend downloading a trial version of Directory Opus 13 to try it out.

**Comment by lifenjoiner** [comment]
Check:
1. if it works in explorer;
2. if there are 2 entries in your Apps Uninstall Panel;
3. if reinstalling works.

**Comment by sinfee** [comment]
1 . works well 
2. only one entry
3. not work well
It is recommended to download the software and test it out. You can also test it using a virtual machine system. The download link for DO is as follows: https://www.gpsoft.com.au/ , and it comes with a default 30-day trial period.

**Comment by stefankueng** [comment]
Directory Opus is an explorer-like tool that uses the context menus that other apps add to explorer.
So it DO does not show and work those properly, the bug is in DO.
So please report the problem to the DO developers.

You don't really expect me to work for free to make another app work properly, and they then get to make money?

**Comment by sinfee** [comment]
I'm sorry, thank you for your support. I didn't think about it that much.
