### ISSUE TITLE
Wild card in file name search doesn't work

### ISSUE THREAD

**Issue by martinRocks** [stefankueng/grepWin#506]
I'm using the latest version (2.1.4.1372).  I put a wild card in the file name search field for example, *.txt and nothing is searched.  If I use 2.1.3, then it works.

**Comment by stefankueng** [comment]
latest version is not 2.1.4 but 2.1.5 with exactly this issue fixed.

**Comment by martinRocks** [comment]
Thank you so very much...I love your tool and make other use it.
