### ISSUE TITLE
No search results if you fill in the "File Names match" field

### ISSUE THREAD

**Issue by terabyte-gc** [stefankueng/grepWin#507]
**GrepWin 2.1.4**

I'm trying to search for a string inside some PHP files in a project, but when I enter "***.php**" (without quotes) in the **File Names match** field, with the **Text match** radio option selected, the search returns 0 results instantly.

It was working correctly until version 2.1.3 before I upgraded. As soon as I empty the **File Names match** field, the program runs a search on ALL types of files, but it does return the expected results. It just takes a long time because there are 70k+ files in the folder I'm searching.

Searching only inside PHP files obviously returned results much quicker in 2.1.3 since it skipped the others.

**Comment by lifenjoiner** [comment]
Fixed by https://github.com/stefankueng/grepWin/releases/tag/2.1.5
