### ISSUE TITLE
Incorrect image link in Visual Studio guide

### ISSUE THREAD

**Issue by Torgo13** [stefankueng/grepWin#509]
https://github.com/stefankueng/grepWin/wiki/Integrate-grepWin-into-Visual-Studio

The guide explains how to use grepWin in Visual Studio to search either a project or a solution, but both screenshots link to the same image showing how to configure it for projects. The correct screenshot for solutions does exist in the Resources folder.

The first image needs to be changed from https://github.com/stefankueng/grepWin/blob/main/src/Resources/vs9-tools-grepwin-prj.png to https://github.com/stefankueng/grepWin/blob/main/src/Resources/vs9-tools-grepwin-sln.png

**Comment by lifenjoiner** [comment]
Thanks! Updated.
