### ISSUE TITLE
The copy behaviour of search results of files is changed?

### ISSUE THREAD

**Issue by imbear** [stefankueng/grepWin#510]
In version 2.1.3, when I press ctrl-a & ctrl-c in search results of files, the whole contents of search results will be put into clipboard.

But in version 2.1.5, same operation, only the file names will be in clipboard.

Maybe create two context menu items for these two actions above?

**Comment by lifenjoiner** [comment]
You need `Ctrl+Shift+C`.

I have created [Hot Keys](https://github.com/stefankueng/grepWin/wiki/Hot-Keys) page according to the source code.

**Comment by imbear** [comment]
> You need `Ctrl+Shift+C`.
> 
> I have created [Hot Keys](https://github.com/stefankueng/grepWin/wiki/Hot-Keys) page according to the source code.
>

It works, thanks for your reply!
