### ISSUE TITLE
The asking for: Are you sure want to replace must be with a scrollable

### ISSUE THREAD

**Issue by ediazrod** [stefankueng/grepWin#511]
Hi I am using the last version 2.1.5 to replace some images on a HTML files and my text to replace is VERY long, like a image base64 long.

the sofware work great but when I replace some long text I said VERY LONG text grepWin make a huge screen and I can see the button to press yes or no...

is a bug, regards!
<img width="958" alt="Screenshot 2024-09-11 180246" src="https://github.com/user-attachments/assets/115b814a-4f84-402d-95ae-26e8f7b86b11">

**Comment by lifenjoiner** [comment]
Quick solution: use the keyboard, Y=Yes, N=No.

Considering long line wrapping, line breaks, space and tab chars, to get a good result:
1. Truncating for current `MessageBox` should calculate the first 2.
2. Scrollable customized dialog box still needs pretty display layouts.

IMHO: Users should make sure these strings are correct from the input boxes. This confirmation message box is just a hard pause to prevent negligence. We don't even need to show the input strings.
