### ISSUE TITLE
2.1.4 breaks "Replace"

### ISSUE THREAD

**Issue by csware** [stefankueng/grepWin#512]
GrepWin 2.1.3 is the last version that works for replacing some text in many files (e.g., TortoiseGit working tree). Search seems to work fine.

With GrepWin 2.1.4+ the replace seems to go into an endless loop without changing a single file. Stop does nothing.

GrepWin 2.1.3 replaces a sigificant amount of files and also does not seem to stop.

Text match, case sensitive
Exclude dirs: `bin|obj|dbg|\.git|\.svn|output|_site|node_modules|\.vs`
Exclude files: `-.obj|.png|.ico|.jpg|.bmp|.jpeg|.svgz|.dll|.exe`
Include: system items and subfolders

**Comment by lifenjoiner** [comment]
Should be fixed by https://github.com/stefankueng/grepWin/commit/4f6674afd2022d878fe3dcd2f4a7ab7bc5c28f4d.
Test https://github.com/stefankueng/grepWin/actions/runs/10970288757.
