### ISSUE TITLE
/searchini:  and /name: (For the section name)  are not work (Neither of them) in 2.1.5.1378

### ISSUE THREAD

**Issue by kirkw** [stefankueng/grepWin#513]
I have a few shortcuts.  Preset that launch to search specific folders.

I have ONE core INI File with 12 sections.  Each for a different preset shortcut (to search various pools of source code).

Unfortunately I installed the new version, and these are no longer working.
I tried using just /searchini and it ignores it.  IT uses whatever was last set.

Reverting back to the prior good version.

**Comment by stefankueng** [comment]
works fine for me here.
my test ini file:

```
[search1]
searchpath=D:\Development\Bowpad
searchfor=search1

[search2]
searchpath=D:\Development\grepWin
searchfor=search2
```

`grepWin.exe /searchini:"D:\Development\search.ini" /name:"search1"`

then brings up the main dialog with `search1` as the search text.

So, what exactly does not work for you?

**Comment by kirkw** [comment]
Interesting.  I have a START IN folder set on my shortcut.
And I am using a relative path:

...\grepWin.exe /searchini:".\DDL.ini" /name:"ALLSOURCE"

And it works fine in the older version, so I feel something changed.

**Comment by stefankueng** [comment]
And I'm asking again: what exactly does not work? Is the search text wrong, is the path wrong, is something else wrong? Does it not find the search text?
And the content of your ini file would also help.

**Comment by stefankueng** [comment]
note: when you set a "START IN" folder in a shortcut, then you have to specify the paths on the command line relative to that "START IN" folder. So ".\DDL.ini" must be in that "START IN" folder.
But even that might not work, since the "START IN" folder is used to set the CWD (current working directory) of a process. And that can change due to other circumstances as well.
So best to use absolute paths when specifying the ini file.

**Comment by kirkw** [comment]
yes, that is exactly the case.  I have the files in my start in folder.  hence I used ".\..." for the ini file name.

And, it behaves like it does not exist.  Let me reduce it to the simplest example for you.
I have to save the current version info, and then uninstall/re-install (potentially restart, and stop all my VMs).

But let me do this...

**Comment by stefankueng** [comment]
grepWin sets the current directory to the path where its exe is.
https://github.com/stefankueng/grepWin/blob/f9222b7c5d2431c65157be8f9ad2d30fd1fb67dc/src/grepWin.cpp#L326

```
attempt to change the working directory to the installation directory

This is a helper when launching grepWin using context menus. When
launching from a context menu, the working directory will be set to the
folder grepWin has been invoked from. With the process now having an
association with this directory, actively attempting to manipulate
(e.g. move/delete) will fail due to an "in use" error. To allow users
to freely manipulate their file systems (without having to close
grepWin), change the working directory to the install path of grepWin.

```

so using relative paths for any command line parameter won't work, sorry.

**Comment by kirkw** [comment]
Perfect.  At least I know.  I quickly changed the paths to NOT be relative paths, and it all works fine, now.
Version 2.0.11.1154, FWIW did not have this "feature"...
