### ISSUE TITLE
Truncated line in tooltips shown on `Results pane`

### ISSUE THREAD

**Issue by Petewg** [stefankueng/grepWin#515]
The tool-tip, displayed when mouse's hovering a line,  in `Search results` pane, 
looks a little bit confusing, because the line content is shown truncated in an arbitrary way (part of preceding word(s) are missing while others are truncated, which decreases readability and makes difficult to get a clue,by a first glance), about the line text you read.
I'm not sure, but seems this is a new behaviour not present in earlier versions.
(since English is not my mother-lang, I do attach a screen snapshot to be better understood the issue).
![grepWin](https://github.com/user-attachments/assets/f7277e60-a0af-4038-8597-d1c291549aad)

the line 44 shown above should read: `#if defined(_UNICODE) || defined(UNICODE)`
while line 49 should be: `#else /* not unicode */`

grepWin version : 2.1.5.1378
O/S: Windows 11

**Comment by lifenjoiner** [comment]
Tooltip can only show limited amount of chars. Main reason.
Long line will be automatically wrapped.
Fixed length leading indicates whether the matching is part of a word, and makes your eyes easy to find them.
Truncating lines makes it be able to show more lines of results.

Each has its own advantages and disadvantages.

To see meaningful results with context, switch to the "Content" view, instead of "File list" view.

**Comment by Petewg** [comment]
@lifenjoiner Thanks for taking time to comment.
However the issue I described it is there indeed.
The last grepWin version that does not "suffer" by this odd tooltip behaviour
is `2.0.15.1232` to which I have already reverted. 
If you're interest, please give it a try.

P.S.: grepWin is a great tool! thank you and kudos to the developer 
      and any collaborator(s) who help to make it better.

regards,
Pete

**Comment by lifenjoiner** [comment]
The new behavior is intentional, as I explained above.
Do you have a better solution?

**Comment by Petewg** [comment]
The better solution was/is already implemented!
Frankly, I don't understand (and cannot see) how the new behaviour is better 
than that of version`2.0.15.1232`, as it's shown in the snapshot below. 
![grepWin2](https://github.com/user-attachments/assets/92317226-d192-4240-9e01-a7c5c87a6fb2)

Note1: The target string searched is : `UNICODE`
Note2: besides the visual discrepancy in newer version, if you look carefully at the image I attached in my first post,  there is an inconsistency between the (correct) number of hits (5) and the number of strings shown in the tooltip (4).

**Comment by lifenjoiner** [comment]
![LL2](https://github.com/user-attachments/assets/827a6d47-b1f5-487f-b39e-18de58e9db89)
Isn't this a mess?
And if there are 5+ results, you can't see the later part anyway.

**Comment by Petewg** [comment]
> Isn't this a mess? 

Possibly. Bu but i wouldn't blame grepWin in first place, it's rather the source code "asking" for it. (for it is too lengthy).

> And if there are 5+ results, you can't see the later part anyway.

That's correct. When the findings do not fit in the tooltip, you get notified about the number of those not displayed. 
However, when it finds 5 matches, shows the 4 (in crippled sentences) and does say nothing about the 5th, it seems a little bit like a bug. No?

**Comment by lifenjoiner** [comment]
> when it finds 5 matches, shows 4

Already had been marked as a bug, which had been self assigned @stefankueng. I'm sure he will diagnose and fix it.

Append another scenario that needs truncating lines:
When the matching part is at the very end of a long line, which is over the max length that a list cell in content view and a tooltip can display.
