### ISSUE TITLE
Content view shows absolute path instead of relative path

### ISSUE THREAD

**Issue by Wdestroier** [stefankueng/grepWin#517]
The "Files" view shows the relative path and it's very useful. However, the "Content" view shows the absolute path. The absolute path takes too much space and contains too much unnecessary information.

Expected:
![image](https://github.com/user-attachments/assets/061c4b9a-08d1-4ede-98bb-e837fb2c9dfc)

Actual:
![image](https://github.com/user-attachments/assets/9334558c-43b4-4aa3-8b9e-fb1d62377c09)

Decreasing the column width doesn't help, because the "C:/blah/" URL part  is kept and the "/important/end.txt" URL part is removed.
![image](https://github.com/user-attachments/assets/5facc657-6c5e-4560-8037-2a1b5708bd36)

Can both views have the same behavior?

**Comment by stefankueng** [comment]
that's by design. Once it was as you request it, i.e., showing relative paths in both views.
But users complained, they needed a full path. Since the content view shows the path at the rightmost column, I now show the full path there.

**Comment by actforjason** [comment]
@stefankueng Hi. Absolute paths take up too much space in **content mode,** and adjusting column widths after each switch is inconvenient, especially since it‘s already shown in `Search in`. Perhaps there could be an option to toggle it.
