### ISSUE TITLE
Feature request: Copy files from found files list directly with Ctrl+C

### ISSUE THREAD

**Issue by fliegenblues** [stefankueng/grepWin#519]
It would be nice if you could copy one or more files from the found files list directly with Ctrl+C, instead of having to do a right-click and selecting "Copy".

**Comment by stefankueng** [comment]
Just select the files, then hit

Ctrl+C : copies file paths
Ctrl+Alt+C: copies file names
Ctrl+Shift+C: copies all columns

**Comment by fliegenblues** [comment]
What I'm missing is the possibility to copy the files with a key shortcut so that I can subsequently copy them into a directory opened in the Windows Explorer.
