### ISSUE TITLE
Context menu not working with 2.1.6

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/grepWin#520]
Nothing happens selecting "Search with grepWin" from pop-up menu, in a directory (File Explorer, Win11 23H2 22631.4391)... 🤔
I double-checked registry keys and they seem ok, e.g.:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\Folder]

[HKEY_CURRENT_USER\Software\Classes\Folder\shell]

[HKEY_CURRENT_USER\Software\Classes\Folder\shell\grepWin]
@="Search with grepWin"
"Icon"="C:\\Users\\Luca\\AppData\\Local\\Programs\\grepWin\\grepWin.exe,-107"

[HKEY_CURRENT_USER\Software\Classes\Folder\shell\grepWin\command]
@="\"C:\\Users\\Luca\\AppData\\Local\\Programs\\grepWin\\grepWin.exe\" /searchpath:\"%1\""
```

I used to right-click on a empty area of an open folder in File Explorer to launch grepWin from that dir...

**Comment by lifenjoiner** [comment]
Thanks for reporting!

Use the CI artifacts, or manually change `%1` to `%V` for `HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\grepWin\command`.

**Comment by Hexaae** [comment]
Installed artifact but I get this at the end of installation:
![image](https://github.com/user-attachments/assets/e7fe2111-dd22-40e6-9895-bedb425e997c)
complaining about missing digital signature...

Never mind... reinstalled/removed it a pair of times and it finally worked without errors on completion. Have no idea why...

**Comment by Sedeniono** [comment]
To add to @lifenjoiner's answer: If you installed grepWin for all users, you need to change `%1` to `%V` in
`HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shell\grepWin\command`
rather than 
`HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\grepWin\command`

**Comment by stefankueng** [comment]
done with cd69063613a43342185633d15eb7a67c020ce241
