### ISSUE TITLE
2.1.6 - Installer asking for admin permissions when local user app folder install is chosen

### ISSUE THREAD

**Issue by koan00** [stefankueng/grepWin#521]
2.1.6 - Windows Installer asking for admin permissions when local user app folder install is chosen. After install, grepWin context menu fails.

![image](https://github.com/user-attachments/assets/85847b93-3ae0-46dd-92c3-c7471c24f7a8)

Tried a repair install, and it did not fix it.

Reinstalled 2.1.5 - No admin prompt. Context menu works.

**Comment by lifenjoiner** [comment]
> 2.1.6 - Windows Installer asking for admin permissions when local user app folder install is chosen

It is trying to detect if a per-machine installation exists. For #292.

> grepWin context menu fails

It should be the same as #520. Fixed.

**Comment by lifenjoiner** [comment]
https://github.com/stefankueng/grepWin/blob/cd69063613a43342185633d15eb7a67c020ce241/src/Setup/Setup.wxs#L206
~This triggers asking for admin permissions, even though "Skipping action: SetALLUSERS (condition is false)".~
~Bug of msiexec?~

**Comment by lifenjoiner** [comment]
> 2.1.6 - Windows Installer asking for admin permissions when local user app folder install is chosen

Fixed by https://github.com/stefankueng/grepWin/commit/540236a3c18ef6e866483c0ddd589c6fca8e5626.

**Comment by stefankueng** [comment]
done with cd69063613a43342185633d15eb7a67c020ce241

**Comment by koan00** [comment]
Hello, unfortunately the installer is still prompting for admin in 2.1.7

**Comment by stefankueng** [comment]
the installer always asks for higher privileges, unless you chose to do a custom install

**Comment by koan00** [comment]
> the installer always asks for higher privileges, unless you chose to do a custom install

Do you mean as a result of recent intended changes? Or did you mean it has always done this for a long time? As I mentioned in the original report, 2.1.5 does not prompt me during install. This seems to match my memory of this function in the past.

With 2.1.7, I can go into advance setup options, and it defaults to non-admin. The help text even says "You do not need local Administrator privileges". With this option selected, it then prompts for admin and fails to install if not granted. Is that the intended behavior?

**Comment by lifenjoiner** [comment]
Upgrading from v2.1.6 needs privileges, as it launches v2.1.6 uninstaller which is the same msi file. Uninstall v2.1.6 first.
![DualMode](https://github.com/user-attachments/assets/1ce3cd29-485a-4a7b-82a2-d6b84af9bd26)

**Comment by koan00** [comment]
I was upgrading from 2.1.5, but a complete uninstall and then a fresh 2.1.7 install worked there too. Thank you!
