### ISSUE TITLE
Creation of search result file empty

### ISSUE THREAD

**Issue by sanpaff** [stefankueng/grepWin#527]
I would like to use the batch command and create a results file with the names of the files that contain a string of characters. 
The command would be this:

**c:\grepWin\grepWin-x64-2.1.7_portable.exe /searchpath:"%1" /searchfor:"%2" /regex:no  /executesearch  /closedialog > "c:\searchF\Result.txt"**

but an empty file is created. Am I doing something wrong? Thank you very much

**Comment by stefankueng** [comment]
grepWin is an UI client, it does not write to the console.

**Comment by sanpaff** [comment]
i would like to write in a file,
