### ISSUE TITLE
how to match multiple lines....

### ISSUE THREAD

**Issue by 4evermaat** [stefankueng/grepWin#54]
how do I match `phrase1` and `phrase2` with any characters in between?

I can't find any examples in your help files.

**Comment by stefankueng** [comment]
the help file is only there for helping with the used regex "flavor". A detailed tutorial for regex is out of the scope of the help.
Try this one:
[https://www.regular-expressions.info/tutorial.html](https://www.regular-expressions.info/tutorial.html)

Search for
`phrase1.*phrase2`
