### ISSUE TITLE
SuggestionBox: regexp renaming templates

### ISSUE THREAD

**Issue by VulcanTourist** [stefankueng/grepWin#55]
I frequently find it useful to be able to rename groups of files with regular expressions, but I am not an expert with regexp syntax and often must experiment a bit to figure out what syntax will accomplish what I want.  Having done that once, it would be highly desirable to save that expression as a template with a descriptive name that I could reuse later and avoid re-inventing the wheel.  I have used awxRenamer in the past because it had that feature, but I found its Perl(?) expression syntax even more inscrutable.

**Comment by stefankueng** [comment]
That's what the "Add to Presets" and "Presets" buttons are for.
