### ISSUE TITLE
Regex search for Arabic words with diacritics doesn't bring results sometimes

### ISSUE THREAD

**Issue by wisemike2** [stefankueng/grepWin#58]
When searching for the word أَمَامَ for example in Text search it bring results, however using Regex search to find \bأَمَامَ\b only without any letters before or after it, it brings results for word that include that word like وأَمَامَي or فأَمَامَهم.  However it should bring only أَمَامَ word

**Comment by stefankueng** [comment]
\b matches a word boundary.
There are three different positions that qualify as word boundaries:

- Before the first character in the string, if the first character is a word character.
- After the last character in the string, if the last character is a word character.
- Between two characters in the string, where one is a word character and the other is not a word character.

problem is that in Arabic, the word boundaries are not always defined that way a regex engine does. And regex engines don't understand languages.

Sorry, but there's nothing I can do about that.
