### ISSUE TITLE
WIndows 7 Pro w/ SP1 (or so it says).

### ISSUE THREAD

**Issue by skiutah1** [stefankueng/grepWin#59]
To stefankueng / grepWin:

A few days ago, I downloaded a setup program(grepWin). I tried to install 'grepWin' onto my laptop, and during the initial installation, I get the error: "The installation package is not supported by this processor type". According to my laptop, it is running Windows 7 Pro, and it says that I have SP1.  Is there a way of really finding out you really have SP1??  This is closed 'issue' called:  "No Results under Win7 SP1 #12" which has no relationship to.  I would like to install it on my laptop, so what do I need to do.  
GitHub/skiutah1                       Thanks. / Nov 21, 2018

**Comment by stefankueng** [comment]
"The installation package is not supported by this **processor type**"
meaning: you're trying to install the x64 version on a 32-bit OS.
Use the win32 installer and you'll be fine.

**Comment by skiutah1** [comment]
I downloaded grepWin.1.9.0.user and it worked alright. But a couple of questions please....
1) is the C source code for the 64 bit and the 32 bit the same.
2) what is the 'boost' and 'nuget' stuff for??
3) If someone reworks the code, can someone easily take out any reference to the different languages and make it straight engish?

 Thanks for your help on my initial question.    skiutah1.    Rsvp Please.

**Comment by stefankueng** [comment]
1. Yes
2. And 3. If you knew c++ and coding you would know. So why do you want to know this?
