### ISSUE TITLE
Regex Issues

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#60]
hello, I use notepad++ with the regex below to remove all empty spaces from the html tag `<p class="text_obisnuit">`. In notepad++ works PERFECT. But, with grepWin is not working. Doesn't replace the `(?1$0)(?2\x20) `

-----------
SEARCH:  

`(?s)(?:\G|<p class="text_obisnuit">)(?:(?!<|>).)*?\K(?:(^\h+)|\h+$|(?<=>)\h+|\h+(?=</p>)|(\h{2,})(?=[^<\h]))`

REPLACE BY:  

`(?1$0)(?2\x20) `
--------------------

EXAMPLE:   `<p class="text_obisnuit">       Avoid opening an issue     that may already exist            by quickly scanning   through    related issues with          similar titles and content.</p>`

**Comment by stefankueng** [comment]
The "Test Regex" button opens another dialog where you can try out your regex and how it matches and replaces texts.
Also, grepWin uses Boost.Regex engine to do its work:
https://www.boost.org/doc/libs/1_68_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html

**Comment by me-suzy** [comment]
hello, so with what I should change that `(?1$0)(?2\x20)` to go well the replace ?
