### ISSUE TITLE
Regex bug?

### ISSUE THREAD

**Issue by wisemike2** [stefankueng/grepWin#61]
In Notepad++ I use the following regex **(\([^()]*(?:(?R)[^()]*)+\))** to search for sentences with more than one parentheses.  However in grepWin it brings "no match" through the Regex Text, although NP++ and grepWin use Boost.

**Comment by stefankueng** [comment]
when I try that regex in npp, it always matches the whole file.

**Comment by wisemike2** [comment]
even so, why doesn't even work in grepWin?

**Comment by tamim555** [comment]
### test ### 
**test**

> test 
`test `

- 1
