### ISSUE TITLE
Exclude subdirectories

### ISSUE THREAD

**Issue by ghost** [stefankueng/grepWin#64]
It might be my misunderstanding, but i tried over and over with several forms, and still can't exclude deeper subdirectories. pls confirm this is either a bug or a documentation failure
The intuitive form for the exclude dirs i used is: "node_modules|_build|_dist|www|web\shared|mobile\shared", which works for excluding the node_modules, _build, etc subdirectories, but not for the more complex paths web\shared or mobile\shared. 
Tried it with backslashes, forwardslashes, double back- or forward-slashes, combined back-/forward-slash, with single or double quotes around the sub-path, but i keep getting results from the sub-paths
What is the problem?

**Comment by stefankueng** [comment]
It's a regex. And you should read the example in the tooltip:
^node_modules|^_build|^_dist|...
you have to use the '^' char to mark the beginning of the path

**Comment by ghost** [comment]
@Stefan, the problem is not the multiple excluded directories: that works fine
Whether i use the form ^aaa$|^bbb$ or ^(aaa|bbb)$ or just simply aaa|bbb : no problem
But excluding files from subdirectories like aaa\bbb (so include files from aaa but not files from subdirectory bbb of directory aaa) still does not work for me, though online regex checkers say the form is OK and works
