### ISSUE TITLE
Feature Request: preview of the results

### ISSUE THREAD

**Issue by effemmeffe** [stefankueng/grepWin#66]
After a successful search it would be great to see the results: let say I search for the word "dummy" and grep finds it in three files, at the end of the search I can see the list of the files with the word in it.
I'd like to select one file and see all the occurrence of the word in a pane under the file list.

**Comment by stefankueng** [comment]
Clicking the "Content" radio button at the bottom right of the window is not enough?

**Comment by effemmeffe** [comment]
Yep. It is, and I'm feeling dumb right now for not seeing it.
Thanks.
