### ISSUE TITLE
In what order are files deleted in grepWin?

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#67]
hello, can anyone knows in what order are files deleted in grepWin? By date, by size, by extension, by selection.. ? What criteria?

**Comment by stefankueng** [comment]
What has grepWin to do with TotalCommander?

**Comment by me-suzy** [comment]
sorry, I mean, in what order are files deleted in grepWin. I test .txt files in totalcommander to see the change by size and date.

**Comment by stefankueng** [comment]
grepWin is a search tool. It doesn't delete files.
Do you mean in what order are they modified if you do a replace?

**Comment by me-suzy** [comment]
yes, in what order are they modified if you do a replace?

**Comment by stefankueng** [comment]
In the order they're found. And that order is not defined.
See https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findfirstfileexw

**Comment by me-suzy** [comment]
lpFileName ...so, by name
