### ISSUE TITLE
Request for the ability to search zipped files with .tar.gz extension

### ISSUE THREAD

**Issue by pom2** [stefankueng/grepWin#69]
Unless I am using grepWin wrongly it does not seem able to search compressed files with the .tar.gz extension. grepWin reports on the status line that it is searching the file OK but does not find textual content which I know is contained within the file.

**Comment by stefankueng** [comment]
grepWin searches all files for text. It does neither uncompress nor decrypt the files first but searches for text in the files as they are.
That's won't change.

**Comment by dorsdn** [comment]
Hello Stefan Kueng,

I have the same problem that grepWin does not search for Text in files in plain ZIP Files. I checked all possible options with no results.

**Comment by hvkooten** [comment]
Too bad you won't add functionality to include search within compressed files. This makes this tool unusable for me. I hope you change you mind

**Comment by Joeppie** [comment]
I have the same problem, that grepwin doesn't search through compressed .zip files, but instead I am more interested in `.xslx` files, which are by themselves a combination of various files which are then zipped.

This limitation means that grepwin cannot be used in a very common scenario, namely that of word and excel files.
