### ISSUE TITLE
Feature request: keep tooltips open as long as mouse is hovering above a result

### ISSUE THREAD

**Issue by LupinIII** [stefankueng/grepWin#7]
When you hover the mouse pointer over a result a tooltip appears showing matching lines. Unfortunately those tooltip closes way too quickly (a few seconds) to be useful, if there are either multiple matching lines or the lines are very long. Is there a way to keep the tooltips open indefinitely as long as the mouse pointer is hovering over the respective result?

**Comment by stefankueng** [comment]
the max time I can set the tooltip to stay visible is SHRT_MAX milliseconds, i.e. about 32 seconds.
That's not indefinitely, but it should be enough - the default time is about 5 seconds, so it's a big improvement.
