### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by SY6502** [stefankueng/grepWin#70]
The menu bar in Windows 7 is not ok. It is narrow and lower line is not visible.

**Comment by stefankueng** [comment]
grepWin does not have a menu bar.
please explain and if possible attach a screenshot.

**Comment by SY6502** [comment]
Attached is a shot. See Press F1 and About text. I am not sure it is real menu bar, but looks like menu. I saw shot from Windows 10 and it was ok there.

![gw](https://user-images.githubusercontent.com/35701909/52336513-cd5ee300-2a0d-11e9-9d5a-77614ffa315d.png)

**Comment by stefankueng** [comment]
It's narrow to save space. And everything is visible. It doesn't have a "lower line".
