### ISSUE TITLE
How to change (Editor) for Edit files

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#72]
right click on file -> Edit

the problem is that the .txt file opens with ms word, instead of notepad++.

How can I change the Editor so as to Edit/open files with Notepad++?

Check this PrintScreen:  https://snag.gy/lyjI3R.jpg

**Comment by stefankueng** [comment]
that's the same command as in the windows explorer. It would open there in ms word for you too.
you have to configure the windows explorer to open txt files in notepad++ with the "edit" command.

Or you can open the settings in grepWin and configure notepad++ there.
