### ISSUE TITLE
Feature Request: Save previous results in GUI

### ISSUE THREAD

**Issue by tommyhosman** [stefankueng/grepWin#73]
Hello,

I first want to say thanks for the creation/maintenance of such a valuable and easy to use program!

I keep wanting to look at the results of my previous searches, but as far as I can tell, grepWin only displays/keeps the most recent search. 

Adding the functionality to toggle to previous searches (for a current session) would be very useful. I can imagine this could be shown either in a tabbed interface, or a drop-down menu method, like the history of previously "Search in" folders.

While this is similar to #23 (which would also be a nice feature to have), I believe it is different enough to warrant a new request.

Thank you.

**Comment by stefankueng** [comment]
I'm sorry, but I think I won't implement this one.
There are users who search really big files or millions of files, which means a result list can get several gigs in size. Storing those would simply consume too much memory, and even if we save them to disk for restoring later, such sizes would make even loading/saving the list very slow.

Just look at issue #110 or #91 or #3
