### ISSUE TITLE
Feature Request: Ability to exclude/ignore certain text search terms, will not appear in results

### ISSUE THREAD

**Issue by ghost** [stefankueng/grepWin#79]
The most common problem I come across is that when I search for short terms such as file extensions, MKV, AVI, and other abbreviations, etc., it will also obviously match to everything else containing that term, including common language words.

While grepWin supports excluding files and directories, but what about the contents it self?

For example, the term `behavior` contains `avi`so all the behavior-s show up, the issue is larger when there is mixed case results that are wanted (all) so I can't just search for upper case `AVI`.

The risky workaround is to rename all behavior-s to some kind of temporary uniqe placeholder term but doing that all the time probably doesn't encourage good use practices among other things.

**Comment by stefankueng** [comment]
grepWin uses regex. So just specify a regex that searches for "avi" as a whole word.
Please have a look at a regex tutorial, e.g. https://www.regular-expressions.info/tutorial.html
especially the \b specifier for word boundary: https://www.regular-expressions.info/wordboundaries.html
Or you could even use lookaheads: https://www.regular-expressions.info/lookaround.html

**Comment by ghost** [comment]
Oh, allright. Thanks.
