### ISSUE TITLE
Russian language for grepWin

### ISSUE THREAD

**Issue by ext5** [stefankueng/grepWin#8]
[Russian.zip](https://github.com/stefankueng/grepWin/files/1946425/Russian.zip)
I made a language file for the Russian language for the program grepWin.
I send it to you. But some GUI elements of the interface require adjustments. Is it possible to somehow fix it?
![image 1](https://user-images.githubusercontent.com/8058418/39238650-77193f94-4887-11e8-8b9e-4dd54e108e03.png)

**Comment by stefankueng** [comment]
If I make the controls wider, then grepWin won't fit into monitors with low resolutions anymore.
Can you maybe use abbreviations in your translated texts?

**Comment by ext5** [comment]
OK
