### ISSUE TITLE
Feature Request: Highlight searched string in the results

### ISSUE THREAD

**Issue by kenijo** [stefankueng/grepWin#83]
It would be nice to highlight the searched string in the results in order to make it much easier to spot it when the displayed resulting line is long.

**Comment by kenijo** [comment]
Here is what I imagine (or something similar):
![Image 022](https://user-images.githubusercontent.com/5394591/81875655-9f801c80-9535-11ea-9639-ec18c44a8dfc.png)

**Comment by garry-ut99** [comment]
Yes, highlighting the searched phrase is a must-have and very important feature of every serious find & replace tool, most of such tools have it (for example dnGrep), a pity that some excellent tools like Notepad++ or grepWin still miss such a basic and important feature, it's like having a good car without lights.

**Comment by zhanglongqiang** [comment]
Any progress on this issue？It‘s really a necessary feature.

**Comment by lifenjoiner** [comment]
Try the latest from https://github.com/stefankueng/grepWin/actions.

**Comment by garry-ut99** [comment]
When searching in text-compatible files (word: "map"), the highlight is in a proper position:
![2](https://github.com/stefankueng/grepWin/assets/72945564/2a8bb272-1402-432a-9489-58734a28e7da)

But when searching binary files in binary mode or text files in binary mode, the highlight offset is 2 chars to the left:
![1](https://github.com/stefankueng/grepWin/assets/72945564/563738a1-0a7e-45d0-9666-001128e049f1)

dnGrep doesn't have that problem.

**Comment by stefankueng** [comment]
works now
