### ISSUE TITLE
[PENDING] Polishing UI 

### ISSUE THREAD

**Issue by sergeevabc** [stefankueng/grepWin#85]
Dear Stefan,
I believe there is a room for improvement related to how grepWin looks with alternative Windows themes. For example, when [this theme][1] is set, grepWin partially looks too dark as follows.

![2]

[1]: https://www.deviantart.com/liuxiaofei/art/Photoshop-CC-2014-VS-for-Windows-7-531779251 
[2]: https://i2.imageban.ru/out/2019/04/06/e3efd8401c22bf63dc8f5de14ae32917.png

**Comment by stefankueng** [comment]
isn't that the theme's fault?

**Comment by sergeevabc** [comment]
Faults are possible, Stefan, but usually I see none, hence the question. Since you’ve already placed “Press F1 for help” and “about grepWin” rather unusually, perhaps, you might consider tuning that element’s color as well.

![1]

[1]: https://i2.imageban.ru/out/2019/04/06/100a4df884dd84c22464408e5001f85e.png

**Comment by sergeevabc** [comment]
Looking forward to verify, Stefan, so I subscribed to new releases notifications.
