### ISSUE TITLE
Explorer context menu issue

### ISSUE THREAD

**Issue by owillebo** [stefankueng/grepWin#86]
Explorer context menu entries holding %W (Expanded to the folder that holds the clicked item) result in dialog below when invoked from grepWin;

![Untitled](https://user-images.githubusercontent.com/15666730/56639765-ba08fe80-6671-11e9-8bfa-1e6f2ebdb5bc.png)

When the same entry is invoked from the explorer for the same item things work as expected.

Please add support for %W.

%W is mentioned in the following web page;

[https://web.archive.org/web/20111002101214/http://msdn.microsoft.com/en-us/library/windows/desktop/cc144101(v=vs.85).aspx](https://web.archive.org/web/20111002101214/http://msdn.microsoft.com/en-us/library/windows/desktop/cc144101(v=vs.85).aspx)

**Comment by stefankueng** [comment]
What entry do you click in the context menu?

**Comment by stefankueng** [comment]
Hmm - just found some docs:
%W is only available from explorer and won't be set for other apps that use the shell context menu.
maybe that's why there's no official documentation about this, apart from that "community content" comment on the archived MS doc page.

**Comment by owillebo** [comment]
For instance I have;

`[HKEY_CLASSES_ROOT\*\shell\Scite\command]
@="\"C:\\Windows\\system32\\cmd.exe\" /C START \"\" development_prompt.pyw \"%W \" /C START \"\" Scite.exe \"%V \""`

This works fine from explorer and results in the error dialog in grepWin.
