### ISSUE TITLE
Adding a feature to show lines before or after the match.

### ISSUE THREAD

**Issue by Joergens-Mi** [stefankueng/grepWin#87]
I'm using your tool and it works fine on win 7 and win 10. I've a small suggestion to improve it.
It would be fine to have a feature to show a number of lines before or after the match, to have a possibilty to see the context.

Serching for **REV** in all files. Found on line 23, the lines from 22 to 24 are displayed.  This for all matches, The number of lines should be configurable 

00022: PN="123927-1100"
00023: REV="A"
00024: DESCR="last/asd-100"

**Comment by stefankueng** [comment]
The tooltip shows you that.
![image](https://user-images.githubusercontent.com/665591/56845695-6131a400-68c5-11e9-8492-814611244b6e.png)

Or you can switch to "Content" view (bottom right radio button), then you have all matches with the line numbers.

**Comment by Joergens-Mi** [comment]
I think there was a small misunderstanding.  I know how to display the found lines.

I'd like to see the lines before and after each match, to see the context of the match. As you can see in my example the match is on line 23 the Rev.  I want to see although the lines 22 and 24 in the output.  The number before and after the match should be selectable from 1 to 5   (Have a look at  what windows grep does with ''match window xx lines'',  It is not longer available and fails sometimes on windows 7  and higher  with big sets of data)

Thanks for your quick reply

**Comment by Joergens-Mi** [comment]
Hello,
i've commted on the closed item.


Thanks in advance

joergens.mi

Am Sa., 27. Apr. 2019 um 08:21 Uhr schrieb Stefan Küng <
notifications@github.com>:
