### ISSUE TITLE
matching words in a line

### ISSUE THREAD

**Issue by harryray33** [stefankueng/grepWin#88]
I'm trying to find a words that are  placed anywhere.

ie. the line 'I will listen to you' and I want to search for I listen you. Presumably this would have to be done with regex.

Thanks.

**Comment by stefankueng** [comment]
I.*listen.*you

Please have a look at any regex tutorials out there, e.g. https://www.regular-expressions.info/tutorial.html
And please don't open issues - questions like this don't belong here but can be asked on the various forums out there, e.g. https://stackoverflow.com/
