### ISSUE TITLE
Does not search files, where filename contains more than one extension

### ISSUE THREAD

**Issue by Tech997** [stefankueng/grepWin#90]
Does not search filenames, where name contains multiple extensions fex. file.tmp.xml

**Comment by RoyiAvital** [comment]
Does `grepWin` have a mode to search filenames only and not their content?

**Comment by stefankueng** [comment]
Search works fine for me.
Even using *.xml and *.tmp.xml as the "File Names match" works as well.

**Comment by RoyiAvital** [comment]
@stefankueng , How do you use `File Name Match`?

**Comment by stefankueng** [comment]
`File Name Match` filters the files to be searched for. If you set it to e.g. `*.txt` then only files that have the `.txt` extension are searched.

**Comment by RoyiAvital** [comment]
My intention is to use `grepWin` to search files by their name using patterns. How can I do that?

**Comment by stefankueng** [comment]
I don't think that's very hard to figure out.
Use the `File Names match` box and enter there either a regex which will match your filenames, or a text match using `*` and `?` as placeholders.
