### ISSUE TITLE
Consumes a lot of memory with Regex search

### ISSUE THREAD

**Issue by Danarman** [stefankueng/grepWin#91]
Recovered a lot of files from a damaged hard drive, but a lot of files only were recovered with NULLS.
Used grepWin with Regex search for "\A\0+\Z"
![image](https://user-images.githubusercontent.com/19614459/57398600-08032380-7195-11e9-86c7-43ccc4b3d756.png)
When found files, and number of found files increases, the memory a lot. Running on an Intel NUC Core-i3-7100U with 12GB RAM, Windows 10 Home, the memory reaches maximum, swap file too, until program stopped working. Seems like a part of code is not freeing memory, as search is performed. The turnaround is stop grepWin when up to 4000 files is reached. When launched context menu (to delete those invalid files filled with NULLs), tooks a while (looks freezed) and memory consumption increased a lot too.
![image](https://user-images.githubusercontent.com/19614459/57399816-aa240b00-7197-11e9-9aeb-c2ac5235fd92.png)

**Comment by stefankueng** [comment]
Well, you're matching the whole file content. And grepWin stores the matches to show in the "content" view. Which means each file that matches is kept in memory fully (since the match is over the whole file).

I guess I have to find a way to only store 'visible' matches...
