### ISSUE TITLE
Can the grepWin support for search again

### ISSUE THREAD

**Issue by wangshuai-007** [stefankueng/grepWin#93]
I now use grepWin to search for the keyword A; but in fact I want to find files with both A and B; the actual situation is that there are too many results for A and B alone, it is difficult to find the answer I want directly; therefore I hope grepWin can use the previous search result as the source of the next search result, so it is easy to find the result I want.

**Comment by stefankueng** [comment]
it's a regex search tool. So search for:
(?=match this expression)(?=match this too)(?=oh, and this)
