### ISSUE TITLE
Text is too short in Content

### ISSUE THREAD

**Issue by irwir** [stefankueng/grepWin#98]
The found lines in _Content_ display could be selected and pasted into a text file.
But _Text_ appears to be limited to 260 characters, which is insufficient for further inspection of logs or other files with longer lines.
Increased limit, or direct export to text/csv files could help here.

**Comment by 4evermaat** [comment]
I think this tool can help:  https://regex101.com/   (PCRE flavor)
But I agree that maybe the search preview window could hold some more text.

**Comment by stefankueng** [comment]
export was done in #23
