### ISSUE TITLE
feature request:  latest xx days for date filter

### ISSUE THREAD

**Issue by 4evermaat** [stefankueng/grepWin#99]
date filters require that you know the date ahead of time.  But with a regular execution of regex on similar files (automated command line grep) this becomes cumbersome to always change the date in which file was last modified.   

I propose that we also have `days (or minutes) since date` filter.  With option to use the current date as the  start date.

So if I say 72 hours before today, the search will only consider files that are 72 hours older than the time script ran. 72 hours = 3 days.

**Comment by 4evermaat** [comment]
can you comment on why you don't think this would be useful?

**Comment by stefankueng** [comment]
there's already a date filter.
Also there's limited space.
If we do that, then the next user requests "last xx days", then "last xx months". I have to draw a line somewhere.

**Comment by 4evermaat** [comment]
the date filter is not the same as being able to create a dynamic range by look back from a specific date or current date.   Because last xx days could be reoccurring.  So it could be last xx days from today's date.

And minutes/days can be scaled up to months/years by simply adding more days.  so 2 years would be 730 days  or 1051200 minutes.

It's easy to scale time.  Use at minimum days units.  for a better intraday precision, use minutes.
